### ISSUE TITLE
warnings in vector_tools_project_qpmf.cc

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#3652] opened 2016-12-01 13:57 UTC
I am getting the following warnings with gcc 4.6.3 and I couldn't immediately find what is wrong. Anybody got an idea?
```
In file included from /ssd/deal-git/include/deal.II/matrix_free/operators.h:30:0,
                 from /ssd/deal-git/include/deal.II/numerics/vector_tools.templates.h:43,
                 from /ssd/deal-git/source/numerics/vector_tools_project_qpmf.cc:17:
/ssd/deal-git/include/deal.II/base/vectorization.h: In static member function ‘static void dealii::internal::FEEvaluationImpl<type, dim, fe_degree, n_q_points_1d, n_components, Number>::evaluate(const dealii::internal::MatrixFreeFunctions::ShapeInfo<Number>&, dealii::VectorizedArray<Number>**, dealii::VectorizedArray<Number>**, dealii::VectorizedArray<Number>* (*)[dim], dealii::VectorizedArray<Number>* (*)[((dim * (dim + 1)) / 2)], bool, bool, bool) [with dealii::internal::MatrixFreeFunctions::ElementType type = (dealii::internal::MatrixFreeFunctions::ElementType)3u, int dim = 2, int fe_degree = 1, int n_q_points_1d = 2, int n_components = 1, Number = double]’:
/ssd/deal-git/include/deal.II/base/vectorization.h:1586:21: warning: ‘*((void*)(& temp1)+48).dealii::VectorizedArray<double>::data’ may be used uninitialized in this function [-Wuninitialized]
/ssd/deal-git/include/deal.II/matrix_free/fe_evaluation.h:6254:37: note: ‘*((void*)(& temp1)+48).dealii::VectorizedArray<double>::data’ was declared here
/ssd/deal-git/include/deal.II/base/vectorization.h:1586:21: warning: ‘*((void*)(& temp1)+32).dealii::VectorizedArray<double>::data’ may be used uninitialized in this function [-Wuninitialized]
/ssd/deal-git/include/deal.II/matrix_free/fe_evaluation.h:6254:37: note: ‘*((void*)(& temp1)+32).dealii::VectorizedArray<double>::data’ was declared here
/ssd/deal-git/include/deal.II/base/vectorization.h:1586:21: warning: ‘*((void*)(& temp1)+16).dealii::VectorizedArray<double>::data’ may be used uninitialized in this function [-Wuninitialized]
/ssd/deal-git/include/deal.II/matrix_free/fe_evaluation.h:6254:37: note: ‘*((void*)(& temp1)+16).dealii::VectorizedArray<double>::data’ was declared here
/ssd/deal-git/include/deal.II/base/vectorization.h:1586:21: warning: ‘temp1.dealii::VectorizedArray<double>::data’ may be used uninitialized in this function [-Wuninitialized]
/ssd/deal-git/include/deal.II/matrix_free/fe_evaluation.h:6254:37: note: ‘temp1.dealii::VectorizedArray<double>::data’ was declared here
/ssd/deal-git/include/deal.II/base/vectorization.h: In static member function ‘static void dealii::internal::FEEvaluationImpl<type, dim, fe_degree, n_q_points_1d, n_components, Number>::evaluate(const dealii::internal::MatrixFreeFunctions::ShapeInfo<Number>&, dealii::VectorizedArray<Number>**, dealii::VectorizedArray<Number>**, dealii::VectorizedArray<Number>* (*)[dim], dealii::VectorizedArray<Number>* (*)[((dim * (dim + 1)) / 2)], bool, bool, bool) [with dealii::internal::MatrixFreeFunctions::ElementType type = (dealii::internal::MatrixFreeFunctions::ElementType)3u, int dim = 2, int fe_degree = 1, int n_q_points_1d = 2, int n_components = 1, Number = float]’:
/ssd/deal-git/include/deal.II/base/vectorization.h:1856:21: warning: ‘*((void*)(& temp1)+48).dealii::VectorizedArray<float>::data’ may be used uninitialized in this function [-Wuninitialized]
/ssd/deal-git/include/deal.II/matrix_free/fe_evaluation.h:6254:37: note: ‘*((void*)(& temp1)+48).dealii::VectorizedArray<float>::data’ was declared here
/ssd/deal-git/include/deal.II/base/vectorization.h:1856:21: warning: ‘*((void*)(& temp1)+32).dealii::VectorizedArray<float>::data’ may be used uninitialized in this function [-Wuninitialized]
/ssd/deal-git/include/deal.II/matrix_free/fe_evaluation.h:6254:37: note: ‘*((void*)(& temp1)+32).dealii::VectorizedArray<float>::data’ was declared here
/ssd/deal-git/include/deal.II/base/vectorization.h:1856:21: warning: ‘*((void*)(& temp1)+16).dealii::VectorizedArray<float>::data’ may be used uninitialized in this function [-Wuninitialized]
/ssd/deal-git/include/deal.II/matrix_free/fe_evaluation.h:6254:37: note: ‘*((void*)(& temp1)+16).dealii::VectorizedArray<float>::data’ was declared here
/ssd/deal-git/include/deal.II/base/vectorization.h:1856:21: warning: ‘temp1.dealii::VectorizedArray<float>::data’ may be used uninitialized in this function [-Wuninitialized]
/ssd/deal-git/include/deal.II/matrix_free/fe_evaluation.h:6254:37: note: ‘temp1.dealii::VectorizedArray<float>::data’ was declared here
/ssd/deal-git/include/deal.II/base/vectorization.h: In static member function ‘static void dealii::internal::FEEvaluationImpl<type, dim, fe_degree, n_q_points_1d, n_components, Number>::evaluate(const dealii::internal::MatrixFreeFunctions::ShapeInfo<Number>&, dealii::VectorizedArray<Number>**, dealii::VectorizedArray<Number>**, dealii::VectorizedArray<Number>* (*)[dim], dealii::VectorizedArray<Number>* (*)[((dim * (dim + 1)) / 2)], bool, bool, bool) [with dealii::internal::MatrixFreeFunctions::ElementType type = (dealii::internal::MatrixFreeFunctions::ElementType)1u, int dim = 2, int fe_degree = 1, int n_q_points_1d = 2, int n_components = 1, Number = float]’:
/ssd/deal-git/include/deal.II/base/vectorization.h:1856:21: warning: ‘*((void*)(& temp1)+48).dealii::VectorizedArray<float>::data’ may be used uninitialized in this function [-Wuninitialized]
/ssd/deal-git/include/deal.II/matrix_free/fe_evaluation.h:6254:37: note: ‘*((void*)(& temp1)+48).dealii::VectorizedArray<float>::data’ was declared here
/ssd/deal-git/include/deal.II/base/vectorization.h:1856:21: warning: ‘*((void*)(& temp1)+32).dealii::VectorizedArray<float>::data’ may be used uninitialized in this function [-Wuninitialized]
/ssd/deal-git/include/deal.II/matrix_free/fe_evaluation.h:6254:37: note: ‘*((void*)(& temp1)+32).dealii::VectorizedArray<float>::data’ was declared here
/ssd/deal-git/include/deal.II/base/vectorization.h:1856:21: warning: ‘*((void*)(& temp1)+16).dealii::VectorizedArray<float>::data’ may be used uninitialized in this function [-Wuninitialized]
/ssd/deal-git/include/deal.II/matrix_free/fe_evaluation.h:6254:37: note: ‘*((void*)(& temp1)+16).dealii::VectorizedArray<float>::data’ was declared here
/ssd/deal-git/include/deal.II/base/vectorization.h:1856:21: warning: ‘temp1.dealii::VectorizedArray<float>::data’ may be used uninitialized in this function [-Wuninitialized]
/ssd/deal-git/include/deal.II/matrix_free/fe_evaluation.h:6254:37: note: ‘temp1.dealii::VectorizedArray<float>::data’ was declared here
/ssd/deal-git/include/deal.II/base/vectorization.h: In static member function ‘static void dealii::internal::FEEvaluationImpl<type, dim, fe_degree, n_q_points_1d, n_components, Number>::evaluate(const dealii::internal::MatrixFreeFunctions::ShapeInfo<Number>&, dealii::VectorizedArray<Number>**, dealii::VectorizedArray<Number>**, dealii::VectorizedArray<Number>* (*)[dim], dealii::VectorizedArray<Number>* (*)[((dim * (dim + 1)) / 2)], bool, bool, bool) [with dealii::internal::MatrixFreeFunctions::ElementType type = (dealii::internal::MatrixFreeFunctions::ElementType)1u, int dim = 2, int fe_degree = 1, int n_q_points_1d = 2, int n_components = 1, Number = double]’:
/ssd/deal-git/include/deal.II/base/vectorization.h:1586:21: warning: ‘*((void*)(& temp1)+48).dealii::VectorizedArray<double>::data’ may be used uninitialized in this function [-Wuninitialized]
/ssd/deal-git/include/deal.II/matrix_free/fe_evaluation.h:6254:37: note: ‘*((void*)(& temp1)+48).dealii::VectorizedArray<double>::data’ was declared here
/ssd/deal-git/include/deal.II/base/vectorization.h:1586:21: warning: ‘*((void*)(& temp1)+32).dealii::VectorizedArray<double>::data’ may be used uninitialized in this function [-Wuninitialized]
/ssd/deal-git/include/deal.II/matrix_free/fe_evaluation.h:6254:37: note: ‘*((void*)(& temp1)+32).dealii::VectorizedArray<double>::data’ was declared here
/ssd/deal-git/include/deal.II/base/vectorization.h:1586:21: warning: ‘*((void*)(& temp1)+16).dealii::VectorizedArray<double>::data’ may be used uninitialized in this function [-Wuninitialized]
/ssd/deal-git/include/deal.II/matrix_free/fe_evaluation.h:6254:37: note: ‘*((void*)(& temp1)+16).dealii::VectorizedArray<double>::data’ was declared here
/ssd/deal-git/include/deal.II/base/vectorization.h:1586:21: warning: ‘temp1.dealii::VectorizedArray<double>::data’ may be used uninitialized in this function [-Wuninitialized]
/ssd/deal-git/include/deal.II/matrix_free/fe_evaluation.h:6254:37: note: ‘temp1.dealii::VectorizedArray<double>::data’ was declared here
```

**Comment by kronbichler** [comment] 2016-12-01 20:15
I've seen that before. The problem is that the compiler is not able to see that the combination of `if` statements that results in the (false positive) report of unused variables is already caught on the top of the function by
```
if (evaluate_val == false && evaluate_grad == false && evaluate_lapl == false)
```
I do not have it high on my priority list but I agree that it would be nice to get rid of it... Newer gcc versions seem to have fixed that problem, so it is not easy for me to reproduce.

**Comment by drwells** [comment] 2017-05-04 14:33
Since we now require a newer version of GCC, may we close this issue?

**Comment by kronbichler** [comment] 2017-05-04 15:02
I can confirm that there are no warnings with gcc-4.8.3 both for `vector_tools_project_qpmf.cc` and when compiling code that involves this part.

**Closed by kronbichler** 2017-05-04 15:02 UTC
Labels: Tests
