### ISSUE TITLE
Grainsize unreasonably small in vector_operations_internal.h

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#7851] opened 2019-03-21 16:17 UTC
As mentioned in #7836, the file `include/deal.II/lac/vector_operations_internal.h` has two calls to `parallel::internal::parallel_for()` in which the minimum grain size is specified as 1. Specifically, these are here:
```
    template <typename Functor>
    void
    parallel_for(
      Functor &                                                  functor,
      const size_type                                            start,
      const size_type                                            end,
      const std::shared_ptr<parallel::internal::TBBPartitioner> &partitioner)
    {
#ifdef DEAL_II_WITH_THREADS
      const size_type vec_size = end - start;
      // only go to the parallel function in case there are at least 4 parallel
      // items, otherwise the overhead is too large
      if (vec_size >=
            4 * internal::VectorImplementation::minimum_parallel_grain_size &&
          MultithreadInfo::n_threads() > 1)
        {
          Assert(partitioner.get() != nullptr,
                 ExcInternalError(
                   "Unexpected initialization of Vector that does "
                   "not set the TBB partitioner to a usable state."));
          std::shared_ptr<tbb::affinity_partitioner> tbb_partitioner =
            partitioner->acquire_one_partitioner();

          TBBForFunctor<Functor> generic_functor(functor, start, end);
          parallel::internal::parallel_for(
            0U, generic_functor.n_chunks, generic_functor, 1, tbb_partitioner);  *********************
          partitioner->release_one_partitioner(tbb_partitioner);
        }
      else if (vec_size > 0)
        functor(start, end);
#else
      functor(start, end);
      (void)partitioner;
#endif
    }
```
and
```
    /**
     * This is the general caller for parallel reduction operations that work in
     * parallel.
     */
    template <typename Operation, typename ResultType>
    void
    parallel_reduce(
      const Operation &                                          op,
      const size_type                                            start,
      const size_type                                            end,
      ResultType &                                               result,
      const std::shared_ptr<parallel::internal::TBBPartitioner> &partitioner)
    {
#ifdef DEAL_II_WITH_THREADS
      const size_type vec_size = end - start;
      // only go to the parallel function in case there are at least 4 parallel
      // items, otherwise the overhead is too large
      if (vec_size >=
            4 * internal::VectorImplementation::minimum_parallel_grain_size &&
          MultithreadInfo::n_threads() > 1)
        {
          Assert(partitioner.get() != nullptr,
                 ExcInternalError(
                   "Unexpected initialization of Vector that does "
                   "not set the TBB partitioner to a usable state."));
          std::shared_ptr<tbb::affinity_partitioner> tbb_partitioner =
            partitioner->acquire_one_partitioner();

          TBBReduceFunctor<Operation, ResultType> generic_functor(op,
                                                                  start,
                                                                  end);
          parallel::internal::parallel_for(
            0U, generic_functor.n_chunks, generic_functor, 1, tbb_partitioner); ******************
          partitioner->release_one_partitioner(tbb_partitioner);
          result = generic_functor.do_sum();
        }
      else
        accumulate_recursive(op, start, end, result);
#else
      accumulate_recursive(op, start, end, result);
      (void)partitioner;
#endif
    }
```

This makes no sense -- these functions are intended to be called for operations acting on individual vector elements. The minimum grain size should be much larger.

Or do I completely misunderstand and we already break things into chunks, and then call these functions on a range of chunks?

**Comment by drwells** [comment] 2019-03-21 17:59
AFAICT you are right: see also

**Comment by drwells** [comment] 2019-03-21 18:16
No, I am wrong. We use, e.g., `TBBForFunctor` as the functor argument in the first code example. `TBBForFunctor` uses `internal::VectorImplementation::minimum_parallel_grain_size`. Hence the grain size of 1 is right since we set the vector element grain size inside the functor itself.

Hence I think the code is correct.

**Comment by bangerth** [comment] 2019-03-21 18:28
OK. Anyone else wants to chime in?

**Comment by kronbichler** [comment] 2019-03-21 20:35
The grain size of 1 is by design and implemented following a discussion in #2496. We have four times as many chunks as we have threads, so there are big chunks inside the loops here, and every thread will get up to four chunks and a grain size of 1 is reasonable. This was done because we wanted to express the reductions as `for` loops to use the same TBB partitioner for all vector operations to support NUMA machines.

**Comment by drwells** [comment] 2019-04-01 12:50
@bangerth are you satisfied with the grain size logic? If so, lets close this.

**Comment by bangerth** [comment] 2019-04-01 15:56
Yes, though I think it would be nice to leave a couple of comments in those places where we use the grainsize=1 so we don't later trip over this again...

**Closed** 2019-05-06 12:52 UTC
Labels: Question :grey_question:
