### ISSUE TITLE
build broken on clang 9.1.0 on macOS

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#6728] opened 2018-06-07 11:44 UTC
subj:
```
 >> 3484    Undefined symbols for architecture x86_64:
     3485      "dealii::VectorizedArray<double>::n_array_elements", referenced from:
     3486          dealii::MatrixFree<1, double>::n_active_entries_per_cell_batch(unsigned int) const in matrix_free.cc.o
     3487          dealii::MatrixFree<1, double>::n_active_entries_per_face_batch(unsigned int) const in matrix_free.cc.o
     3488          dealii::MatrixFree<2, double>::n_active_entries_per_cell_batch(unsigned int) const in matrix_free.cc.o
     3489          dealii::MatrixFree<2, double>::n_active_entries_per_face_batch(unsigned int) const in matrix_free.cc.o
     3490          dealii::MatrixFree<3, double>::n_active_entries_per_cell_batch(unsigned int) const in matrix_free.cc.o
```

in reference to https://github.com/dealii/dealii/pull/6720
@masterleinad ping.

**Comment by masterleinad** [comment] 2018-06-07 11:55
Is this still a problem after #6718?

**Comment by davydden** [comment] 2018-06-07 11:56
> Is this still a problem after #6718?

let me try building again...

**Comment by davydden** [comment] 2018-06-07 13:07
> Is this still a problem after #6718?

yes, I double checked that I am building with this PR and unfortunately it's still broken.

**Comment by masterleinad** [comment] 2018-06-07 13:36
Hmm... then I don't have a clue. We declare `VectorizedArray<double>::n_array_elements` in `vectorization.h` and define it in `vectorization.cc`. This last step is required by older compilers, but not newer ones. Hence, the symbol should definitely exist.
As far as I know, `clang-9.1.0` corresponds to `clang-6.*` and I used `clang-6.0` for #6718.

**Comment by masterleinad** [comment] 2018-06-07 13:38
Can you upload the failing build to `CDash`?

**Comment by davydden** [comment] 2018-06-07 13:38
> Can you upload the failing build to CDash?

how do I do that? I never submitted the build-only

**Comment by kronbichler** [comment] 2018-06-07 13:42
This looks similar to what we fixed in #5383, doesn't it? So the problem is that the exception takes a reference rather than a value?

**Comment by masterleinad** [comment] 2018-06-07 13:43
In the end, we store a value nevertheless.

**Comment by masterleinad** [comment] 2018-06-07 13:45
> how do I do that? I never submitted the build-only

Have a look at https://www.dealii.org/developer/developers/testsuite.html#build_tests

**Comment by davydden** [comment] 2018-06-07 15:59
@masterleinad 

> Can you upload the failing build to CDash?

I am running the build for CDash, should appear soon...

**Comment by tamiko** [comment] 2018-06-07 16:58
@masterleinad @davydden https://cdash.kyomu.43-1.org/viewBuildError.php?buildid=2396

**Closed** 2018-06-08 01:59 UTC
Labels: Bug, High Priority :warning:

**Comment by tamiko** [comment] 2018-06-09 15:20
Actually, clang-5 didn't like it: https://cdash.kyomu.43-1.org/buildSummary.php?buildid=2407
