### ISSUE TITLE
Fast path of FEPointEvaluation for FEDG_Q with n_components>1 broken

### ISSUE THREAD

**Issue by jh66637** [dealii/dealii#15337] opened 2023-06-09 17:36 UTC
If `FEPointEvaluation` is used with a `FESystem` with `n_components>1` of `FEDG_Q` internally, the fast path is set up. However, there seems to be a problem with the fast path in this specific scenario. If I use the slow path, everything works as expected. I wrote a test which shows the failure and which is located here: https://github.com/dealii/dealii/pull/15336

I will try to trace this down soon, but I will probably not make it until next week. I am happy for any hint, so if someone who is familiar with the code (maybe @peterrum @kronbichler ?) has an immediate idea what could be the problem, please let me know.

**Comment by peterrum** [comment] 2023-06-09 19:35
I have added the `release 9.5` tag, since this seems to be a bug and should be fixed before the next release. Let me also ping @bergbauer who has done the most in this class in the last few months and might have a better feeling about where to start with debugging.

**Comment by peterrum** [comment] 2023-06-09 19:37
@jh66637 One question: `FE_Q` is working? If yes, the problem is probably due renumbering/not renumbering, which should be the only difference in both cases.

**Comment by peterrum** [comment] 2023-06-09 20:18
Yes it is a renumbering issue.

The following changes fixes it.
```diff
diff --git a/include/deal.II/matrix_free/fe_point_evaluation.h b/include/deal.II/matrix_free/fe_point_evaluation.h
index 79c3aed..6a622ac 100644
--- a/include/deal.II/matrix_free/fe_point_evaluation.h
+++ b/include/deal.II/matrix_free/fe_point_evaluation.h
@@ -1763,7 +1763,11 @@ FEPointEvaluation<n_components_, dim, spacedim, Number>::prepare_evaluate_fast(
         {
           if (renumber.empty())
             for (unsigned int i = 0; i < dofs_per_component; ++i)
-              ETT::read_value(solution_values[i], comp, solution_renumbered[i]);
+              ETT::read_value(
+                solution_values[i + (component_in_base_element + comp) *
+                                      dofs_per_component],
+                comp,
+                solution_renumbered[i]);
           else
             {
               const unsigned int *renumber_ptr =
```

But I guess similar issues are also in integrate!?

**Comment by jh66637** [comment] 2023-06-10 13:02
> @jh66637 One question: `FE_Q` is working? If yes, the problem is probably due renumbering/not renumbering, which should be the only difference in both cases.

Exactly `FE_Q` is working. 

> The following changes fixes it.

Thank you, I added the diff to the PR :)

>But I guess similar issues are also in integrate!?

I will further investigate this, but it seems that integrate is doing the right thing. I will let you know when I am sure.

**Comment by jh66637** [comment] 2023-06-10 16:15
@peterrum The face path also needed an adjustment (I need to extend the test for this). With that, everything works in my applications again. So I can confirm `integrate()` is behaving as expected.

**Closed** 2023-06-12 12:51 UTC
Labels: Bug, Matrix-free, Non-matching
