### ISSUE TITLE
Bug using MappingFEField and refinements

### ISSUE THREAD

**Issue by nicola-giuliani** [dealii/dealii#5715] opened 2018-01-10 14:50 UTC
Working with @luca-heltai we discover that the following code fails. We don't know yet who or what introduced this issue. The code fails because the subscriptor of gradient_dh, which is needed from MappingFEField, is not zero when the second distribute_dofs comes in place. With version 8.5 the code is functioning just fine.

```
#include <deal.II/base/utilities.h>
#include <deal.II/base/quadrature_lib.h>
#include <deal.II/base/geometry_info.h>
#include<deal.II/dofs/dof_handler.h>
#include<deal.II/dofs/dof_accessor.h>
#include<deal.II/dofs/dof_tools.h>
#include<deal.II/fe/fe_q.h>
#include<deal.II/fe/fe_values.h>
#include<deal.II/fe/fe_system.h>
#include<deal.II/fe/mapping_q1_eulerian.h>
#include<deal.II/fe/mapping_q1.h>
#include <deal.II/fe/mapping_fe_field.h>
#include <deal.II/grid/grid_generator.h>
#include<deal.II/numerics/vector_tools.h>

using namespace dealii;
int main()
{


  Triangulation<2> tria;
  GridGenerator::hyper_cube (tria);
  tria.refine_global (1);
  FE_Q<2> fe(1);
  FESystem<2> gradient_fe(FE_Q<2> (1),1,FE_Q<2> (1),1);
  DoFHandler<2,2> dh(tria);
  DoFHandler<2,2> gradient_dh(tria);
  dh.distribute_dofs(fe);
  gradient_dh.distribute_dofs(gradient_fe);
  std::cout<<tria.n_active_cells()<<" "<<dh.n_dofs()<<std::endl;
  Vector<double> map_vector;
  map_vector.reinit(gradient_dh.n_dofs());
  VectorTools::get_position_vector(gradient_dh, map_vector);
  MappingFEField<2, 2> mapping(gradient_dh, map_vector);
  tria.refine_global (1);
  dh.distribute_dofs(fe);
  gradient_dh.distribute_dofs(gradient_fe);
  std::cout<<tria.n_active_cells()<<" "<<dh.n_dofs()<<std::endl;
}
```

**Comment by luca-heltai** [comment] 2018-01-10 15:39
The problem seems to be there also with `MappingQ`

**Comment by luca-heltai** [comment] 2018-01-10 17:36
So, this all boils down to:

~~~
 Triangulation<dim,spacedim> tria;
  GridGenerator::hyper_cube (tria);
  FE_Q<dim,spacedim> fe(1);

  DoFHandler<dim,spacedim> dh(tria);
  dh.distribute_dofs(fe);

  SmartPointer<const FiniteElement<dim,spacedim>> fe_p(&dh.get_fe());

  tria.refine_global (1);
  dh.distribute_dofs(fe);
~~~
and the last distribute dofs is the one that is failing. I don't know wether this is the intended behaviour, but this code breaks for example all cases where the `fe` is not changing.

Apparently the behaviour changed somewhere between 8.5.1 and now. It looks like the dofhandler creates a new copy of the finite element internally (instead of storing a smart pointer to the outside object), and then destroys it and recreates it when calling `distribute_dofs`.

Does this classify as a bug?

**Comment by bangerth** [comment] 2018-01-10 18:17
Yes, in the process of making `DoFHandler` look more like `hp::DoFHandler`, @masterleinad (I think) had a patch that makes `DoFHandler` clone the element. I think yours is sort of a corner case -- why create the `fe_p` pointer instead of just keep using the `fe` object?

**Comment by bangerth** [comment] 2018-01-10 18:17
By the way, what is the error message you get?

**Comment by masterleinad** [comment] 2018-01-10 18:59
We could probably save on recreating the `FiniteElement` if it is the same class.

Why would one want to call `distribute_dofs` a second time without expecting that the `FiniteElement` stored being invalidated?

**Comment by masterleinad** [comment] 2018-01-10 22:47
> By the way, what is the error message you get?

The call to the destructor of `FE_Q<2>` results in
```
--------------------------------------------------------
An error occurred in line <104> of file </mnt/data/darndt/Sources/dealii/source/base/subscriptor.cc> in function
    void dealii::Subscriptor::check_no_subscribers() const
The violated condition was: 
    counter == 0
Additional information: 
    (none)
--------------------------------------------------------
```
for the `SmartPointer` `fe_p`

**Comment by bangerth** [comment] 2018-01-10 22:54
But that's because the `SmartPointer` outlived the `DoFHandler` object -- which believes that it owns the copy of the FE object and destroys it at the end of the time. There is nothing you can do about this: both objects believe that they own the finite element, but only one can legally delete it. I don't see how you can change this.

**Comment by masterleinad** [comment] 2018-01-10 23:10
At least, we can avoid recreating the same `FECollection` when calling `distribute_dofs` so that the above code works again.

**Comment by bangerth** [comment] 2018-01-10 23:19
No. We can avoid cloning the element a *second* time, but since we now store an FE collection, we have to clone at least once. This clone is owned by `DoFHandler`, and trying to get a `SmartPointer` to point to it and believe that it owns the element is always going to fail.

**Comment by bangerth** [comment] 2018-01-10 23:20
By the way, the original code was *also* faulty in this regard: The `DoFHandler` originally only stored a reference to the element. The `SmartPointer` now points to that reference and tries to delete it, but at a later time, the object itself goes out of scope and is destroyed a second time. This has never worked correctly.

**Comment by luca-heltai** [comment] 2018-01-10 23:47
smartpointer in dealii do not try to delete the object, nor they think they own it. 

The current version breaks all codes that use mappingqeulerian or mappingfefield, since they both store a smartpointer to the fe extracted from dofhandler (as you can see in the original snippet posted by Nicola). 

One solution is to fix this in mappingqeulerian and mappingfefield, by not storing the fe, and simply querying from dh when needed...

**Comment by masterleinad** [comment] 2018-01-10 23:47
> No. We can avoid cloning the element a second time, but since we now store an FE collection, we have to clone at least once.

That is what I meant.



> The SmartPointer now points to that reference and tries to delete it, but at a later time, the object itself goes out of scope and is destroyed a second time. This has never worked correctly.

But a `SmartPointer` doesn't delete the actual object in its desctuctor, isn't it?

**Comment by luca-heltai** [comment] 2018-01-10 23:54
In the past this has worked correctly because dh did not clone the fe, so you had to keep the fe around, and you could use the same fe in mappingqeulerian or mappingfefield. 

Tomorrow (unless you beat me to it), I'll fix this. I know what needs to be done. The new implementation underlined a weak design of mappingqeulerian and mappingfefield.

**Comment by bangerth** [comment] 2018-01-10 23:59
Oh, doh, you are right that `SmartPointer` doesn't delete the object. But it's still correct that one way or the other, you need to release the `SmartPointer` before the object it points to is deleted. For this, you need to have some sort of control over when exactly that happens.

**Closed** 2018-04-27 14:36 UTC
Labels: Bug, DoFs, Mapping
