### ISSUE TITLE
Cannot link tutorial with static executable

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#324] opened 2014-12-15 16:37 UTC
_From [Bruno.Tu...@gmail.com](https://code.google.com/u/108807043379354454976/) on June 11, 2014 18:05:26_

When compiling deal.II with -DDEAL_II_STATIC_EXECUTABLE=ON, I cannot link the tutorials.

I tried on different computers but none of them work and the errors are different on each machine :( 

gcc 4.8.2 on Titan
/usr/bin/ld: warning: libsci_gnu_48_mp.so.3, needed by /opt/cray/tpsl/1.3.04/GNU/48/x86_64/lib/libsuperlu_gnu.so, may conflict with libsci_gnu_48_mp.so.4
/usr/bin/ld: dynamic STT_GNU_IFUNC symbol `strcmp' with pointer equality in`/opt/cray/xe-sysroot/4.2.34/usr/lib64/libc.a(strcmp.o)' can not be used when making an executable; recompile with -fPIE and relink with -pie

clang 3.4.1 with libstc++ 4.6
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.6/libstdc++.a(eh_globals.o): undefined reference to symbol '__tls_get_addr@@GLIBC_2.3'
/usr/bin/ld: note: '__tls_get_addr@@GLIBC_2.3' is defined in DSO /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 so try adding it to the linker command line
/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2: could not read symbols: Invalid operation
clang: error: linker command failed with exit code 1 (use -v to see invocation)

gcc 4.8.2 on Ubuntu 14.04:
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libpthread.a(lowlevellock.o): In function `__lll_lock_wait_private':
/build/buildd/eglibc-2.19/nptl/../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:78: multiple definition of`__lll_lock_wait_private'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc.a(libc-lowlevellock.o):(.text+0x0): first defined here
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libpthread.a(lowlevellock.o): In function `__lll_unlock_wake_private':
/build/buildd/eglibc-2.19/nptl/../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:328: multiple definition of`__lll_unlock_wake_private'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libc.a(libc-lowlevellock.o):(.text+0x30): first defined here
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/libstdc++.a(eh_globals.o): undefined reference to symbol '__tls_get_addr@@GLIBC_2.3'
//lib/x86_64-linux-gnu/ld-linux-x86-64.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

_Original issue: http://code.google.com/p/dealii/issues/detail?id=222_

**Comment by Rombur** [comment] 2015-06-10 08:16
Compiling PETSc using  --with-batch=1 and --known-mpi-shared-libraries=0 should fix  the problem but I still need to try it.

**Comment by Rombur** [comment] 2015-06-10 08:34
Maybe we also need --with-shared-ld=ar

**Comment by bangerth** [comment] 2015-06-10 17:25
Fascinating -- I would have no idea what each of these options do. Do you know?

**Comment by Rombur** [comment] 2015-06-10 17:52
-with-batch=1  --known-mpi-shared-libraries=0 are needed for cross-compiling
--with-shared-ld=ar I don't know but I assume it's just make sure that we use ar instead of ld

**Comment by agrayver** [comment] 2015-06-11 07:44
I can confirm now that the deal.II + p4est + PETSc + SLEPc runs on Cray XC30 cluster and gives correct results.
for details see: https://groups.google.com/forum/#!topic/dealii/2rSdfcsgfbE

**Comment by bangerth** [comment] 2016-11-16 14:04
Let's close this one -- we're not currently running on Titan, and the last comment (and linked to thread) suggests that one just needs to pass the appropriate flags. Hopefully this kind of system dies out soon -- although I've been hoping for this since I started using clusters around 1999...

**Closed** 2016-11-16 14:04 UTC
Labels: Bug
