### ISSUE TITLE
Use a consistent way to cite/reference papers in documentation (either inline full-text or bibtex cite keys)

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9354] opened 2020-01-16 21:06 UTC
This issue is just about making a consistent choice in the library for presenting reference material such as journal articles. In the `master` branch, most of the tutorials seem to use the `bib`/`cite` combination.  However, I just stumbled upon this page (documentation of the FE_Nothing class) that inlines the reference to a full paper _A. Cangiani, J. Chapman, E. Georgoulis, M. Jensen: Implementation of the Continuous-Discontinuous Galerkin Finite Element Method, arXiv:1201.2878v1 [math.NA], 2012 (see http://arxiv.org/abs/1201.2878)._

If the maintainers think it is worth doing so, if I am happy to submit a PR with cite keys. However, I don't clearly know how to set up the doxygen system for this task.

**Comment by bangerth** [comment] 2020-01-16 21:18
Yes, we switched to the `@cite` approach, but not all places have been converted. Help is certainly appreciated.

The file with the references is `doc/doxygen/references.bib`.

**Comment by bangerth** [comment] 2020-01-16 21:18
For the one you cite, it might also be useful to find the actual paper (rather than preprint). I've generally used https://doi2bib.org to get standardized bibtex entries.

**Comment by tamiko** [comment] 2020-01-20 19:29
Duplicate of #8152 closing in favor of the other issue :smiley_cat:

**Closed by tamiko** 2020-01-20 19:29 UTC

**Comment by krishnakumarg1984** [comment] 2020-01-20 19:31
@tamiko I am afraid this issue isn't connected at all with the other one you linked. Can you please reopen this?
