### ISSUE TITLE
Slepc 3.6.3 compatibility

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#4089] opened 2017-03-21 16:57 UTC
With slepc-3.6.3 + petsc-3.6.4 freshly installed with candi I get the following:

~~~
/usr/tmp/heltai/dealii/build/lib/libdeal_II.g.so.8.5.0-pre: error: undefined reference to 'EPSComputeResidualNorm'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
~~~

anyone else?

The documentation of slepc seems to refer to a different interface. Apparently they maintained the definition but not the implementation...

**Comment by oneliefleft** [comment] 2017-03-21 17:30
Thanks Luca, I will check it out tomorrow morning. I am using petsc/slepc
dev without this peroblem. I may have missed something.

Best;
   Toby


21.03.2017 17:57 "Luca Heltai" <notifications@github.com> napisał(a):

With slepc-3.6.3 + petsc-3.6.4 freshly installed with candi I get the
following:

/usr/tmp/heltai/dealii/build/lib/libdeal_II.g.so.8.5.0-pre: error:
undefined reference to 'EPSComputeResidualNorm'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

anyone else?

The documentation of slepc seems to refer to a different interface.
Apparently they maintained the definition but not the implementation...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dealii/dealii/issues/4089>, or mute the thread

**Comment by oneliefleft** [comment] 2017-03-22 10:29
> With slepc-3.6.3 + petsc-3.6.4 freshly installed with candi I get the
> following:
> 
> ~~~
> /usr/tmp/heltai/dealii/build/lib/libdeal_II.g.so.8.5.0-pre: error:
> undefined reference to 'EPSComputeResidualNorm' collect2: error: ld
> returned 1 exit status ninja: build stopped: subcommand failed.
> ~~~
> 
> anyone else?
> 

My deal.II is building with the same petsc/slepc version numbers you
quoted (candi free). That will take a while. ;-)

> The documentation of slepc seems to refer to a different interface.
> Apparently they maintained the definition but not the
> implementation... 

Yes, the SLEPc manual states, "Interface changes:
EPSComputeRelativeError and EPSComputeResidualNorm have been deprecated
(use EPSComputeError instead)". 

I don't know how SLEPc "deprecates" functions, though I assume the
function implementation should still be there. Which means something is
broken. Does candi run the petsc and slepc tests? These pass for me.

(Not much help, sorry).

**Comment by davydden** [comment] 2017-03-22 21:17
will check if I see this with `$ spack install dealii+mpi+petsc+slepc~int64 ^petsc@3.6.4 ^slepc@3.6.3`...

**Comment by davydden** [comment] 2017-03-23 06:37
@luca-heltai i can't reproduce this: `==> Successfully installed dealii`.

**Comment by oneliefleft** [comment] 2017-03-23 09:42
> will check if I see this with `$ spack install
> dealii+mpi+petsc+slepc~int64 ^petsc@3.6.4 ^slepc@3.6.3`...

This setup works when compiled by hand. I wonder if something strange
happens in the candi setup of PETSc?

**Comment by davydden** [comment] 2017-03-23 09:53
> This setup works when compiled by hand.

since @oneliefleft also does not have problems compiling by hand, most likely the reasons is that 

> something strange happens in the candi setup of PETSc

I thereby close this issue, if nobody minds.

**Comment by luca-heltai** [comment] 2017-03-23 12:16
(Y)

**Comment by luca-heltai** [comment] 2017-03-23 12:18
From the documentation of slepc:

~~~
Changes in Version 3.6
...
Interface changes: EPSComputeRelativeError and EPSComputeResidualNorm have been deprecated (use EPSComputeError instead); the same for PEP, NEP and SVD; PEPSetScale now allows passing two Vecs for diagonal scaling; XXXPrintSolution has been replaced with XXXErrorView; 
...
~~~

This might be worth fixing anyway....

**Comment by davydden** [comment] 2017-03-23 12:19
@luca-heltai still don't udnerstand why neither myself nor @oneliefleft see this issue...

**Comment by luca-heltai** [comment] 2017-03-23 12:23
I think it depends on what the compiler does with their *deprecated* functions. This happens to me on SUSE, with 
~~~
g++ (SUSE Linux) 4.8.3 20140627 [gcc-4_8-branch revision 212064]
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
~~~
but works ok on mac.

**Comment by oneliefleft** [comment] 2017-03-23 12:24
@luca-heltai <https://github.com/luca-heltai> still don't udnerstand why
neither myself nor @oneliefleft <https://github.com/oneliefleft> see this
issue...


Me too, this is a bad kind of weird. :-( I going to give candi a shot on my
home machine over the weekend and see if that blows up. I'll report back on
what happens.

**Comment by luca-heltai** [comment] 2017-03-23 12:27
I think we can skip this for 8.5, but it might be worth keeping it in mind, since they will likely remove that function in the future...

**Comment by oneliefleft** [comment] 2017-03-23 12:27
Good thought Luca!


23.03.2017 13:23 "Luca Heltai" <notifications@github.com> napisał(a):

I think it depends on what the compiler does with their *deprecated*
functions. This happens to me on SUSE, with

g++ (SUSE Linux) 4.8.3 20140627 [gcc-4_8-branch revision 212064]
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

but works ok on mac.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/dealii/dealii/issues/4089#issuecomment-288702161>, or mute
the thread

**Comment by oneliefleft** [comment] 2017-03-23 12:31
I think we can skip this for 8.5, but it might be worth keeping it in mind,
since they will likely remove that function in the future...


@Luca-Heltai Yes and please let's leave the issue open I will come back to
this in a couple of weeks when I will have more time available.

**Comment by drwells** [comment] 2018-03-28 14:58
Out of curiousity I recompiled deal.II with slepc 3.6.3 and PETSc 3.6.4: the `reinit_preconditioner_01` and `reinit_preconditioner_02` both fail due to an issue in ParaSails, but otherwise all PETSc and SLEPc tests pass.

We still use one of the deprecated functions (`EPSComputeResidualNorm`). I'll put together a patch to move to the replacement (`EPSComputeError`).

**Closed** 2018-03-31 06:50 UTC
Labels: Bug
