### ISSUE TITLE
[8.5.0 release] Test lac/schur_complement_05 fails

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#3913] opened 2017-02-03 05:13 UTC
$ ctest -R "linear_operator|linear-operator|schur_complement"
...
94% tests passed, 4 tests failed out of 70
The following tests FAILED:
	319 - lac/schur_complement_05.mpirun=1.debug (Failed)
	320 - lac/schur_complement_05.mpirun=1.release (Failed)
	321 - lac/schur_complement_05.mpirun=3.debug (Failed)
	322 - lac/schur_complement_05.mpirun=3.release (Failed)
Errors while running CTest

**Comment by jppelteret** [comment] 2017-02-03 09:25
I'm trying to look at this on my Linux box ([configuration](https://github.com/dealii/dealii/files/749914/summary.log.txt) [summary](https://github.com/dealii/dealii/files/749913/detailed.log.txt) attached), but have run into a bit of a problem that I don't quite understand. When I try to run some of the tests, the compiler complains that it can't find some symbols related to `TrilinosPayload`.
```
build/tests/lac/linear_operator_12.debug/linear_operator_12.debug: symbol lookup error: <path>/build/tests/lac/linear_operator_12.debug/linear_operator_12.debug: undefined symbol: vtable for dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload
```
However, here's the list of related symbols in the debug library.
```
build$ nm -D lib/libdeal_II.g.so | grep TrilinosPayload     
0000000006e9f9a2 T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::SetUseTranspose(bool)
0000000006e961ec T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::transpose()
0000000006ea55be T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::TrilinosPayload(dealii::TrilinosWrappers::SparseMatrix const&, dealii::TrilinosWrappers::PreconditionBase const&)
0000000006ea59ce T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::TrilinosPayload(dealii::TrilinosWrappers::SparseMatrix const&, dealii::TrilinosWrappers::SparseMatrix const&)
0000000006ea51c2 T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::TrilinosPayload(dealii::TrilinosWrappers::PreconditionBase const&, dealii::TrilinosWrappers::PreconditionBase const&)
0000000006ea5070 T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::TrilinosPayload(dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload const&)
0000000006ea4f4c T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::TrilinosPayload(dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload const&, dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload const&)
0000000006ea5e34 T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::TrilinosPayload()
0000000006ea55be T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::TrilinosPayload(dealii::TrilinosWrappers::SparseMatrix const&, dealii::TrilinosWrappers::PreconditionBase const&)
0000000006ea59ce T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::TrilinosPayload(dealii::TrilinosWrappers::SparseMatrix const&, dealii::TrilinosWrappers::SparseMatrix const&)
0000000006ea51c2 T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::TrilinosPayload(dealii::TrilinosWrappers::PreconditionBase const&, dealii::TrilinosWrappers::PreconditionBase const&)
0000000006ea5070 T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::TrilinosPayload(dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload const&)
0000000006ea4f4c T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::TrilinosPayload(dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload const&, dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload const&)
0000000006ea5e34 T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::TrilinosPayload()
0000000006eb2fc8 W dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::~TrilinosPayload()
0000000006eb2f26 W dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::~TrilinosPayload()
0000000006eb2f26 W dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::~TrilinosPayload()
0000000006ea6daf T dealii::TrilinosWrappers::internal::LinearOperator::operator*(dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload const&, dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload const&)
0000000006ea76b1 T dealii::TrilinosWrappers::internal::LinearOperator::operator+(dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload const&, dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload const&)
0000000006e945e8 T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::HasNormInf() const
0000000006e9b53a T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::ApplyInverse(Epetra_MultiVector const&, Epetra_MultiVector&) const
0000000006ea8386 T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::null_payload() const
0000000006e945c0 T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::UseTranspose() const
0000000006ea85be T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::identity_payload() const
0000000006e945e0 T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::OperatorRangeMap() const
0000000006e945d8 T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::OperatorDomainMap() const
0000000006ea8350 T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::transpose_payload() const
0000000006e961e0 T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::get_mpi_communicator() const
0000000006e961ca T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::locally_owned_range_indices() const
0000000006e961b4 T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::locally_owned_domain_indices() const
0000000006e945d0 T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::Comm() const
0000000006e9b55a T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::Apply(Epetra_MultiVector const&, Epetra_MultiVector&) const
0000000006e945c8 T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::Label() const
0000000006e98baa T dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload::NormInf() const
000000000a11b780 V typeinfo for dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload
0000000009057800 V typeinfo name for dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload
000000000a11ba00 V vtable for dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload
```
and from what I can tell, the last symbol in that list is the one its complaining that it can't find.
Additionally, buried somewhere in the output of `build$ nm -D tests/lac/linear_operator_12.debug/linear_operator_12.debug | grep Payload
` is
```
000000000045bc00 V vtable for dealii::LinearOperator<dealii::TrilinosWrappers::MPI::Vector, dealii::TrilinosWrappers::MPI::Vector, dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload>
                 U vtable for dealii::TrilinosWrappers::internal::LinearOperator::TrilinosPayload
```
presumably with the `U` marker specifying that the symbol is undefined?

I have no idea as to what the problem might be. A google search hasn't been particularly enlightening either. As last-resort ideas, I've tried moving this class' destructor to the source file, and then removing it entirely. Neither had any effect. I've also nuked the build directory and rebuilt the library from scratch.

The same problem applies to `lac/schur_complement_05`, so I kind of need to get this fixed to start debugging this test. Can anyone offer me some suggestions as to how to proceed with resolving this issue? Unfortunately it doesn't show up on my Mac, so I didn't encounter the problem earlier.

**Comment by bangerth** [comment] 2017-02-03 18:10
Yes, `U` means undefined. Which, in the object file for the test it actually should be; it just should be found in the library. Moving the destructor's implementation to `.cc` file would have been my first suggestion as well.

I wonder whether the two symbols (the one missing and the one provided by the library) are really the same. Can you omit the `-D` in your invocation of `nm`, and do something like
```
  nm build/tests/lac/linear_operator_12.debug/linear_operator_12.debug  \
  | grep internal | grep TrilinosPayload | grep U
```
? This should give you the mangled name of the symbol that is missing. Then grep for this mangled string in the library.

**Comment by jppelteret** [comment] 2017-02-06 10:50
Thanks for the help @bangerth . Here are output of grepping for the symbols in the executable
```sh
build$ nm tests/lac/linear_operator_12.debug/linear_operator_12.debug | grep internal | grep TrilinosPayload | grep " U "

 U _ZN6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload15SetUseTransposeEb
 U _ZN6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload9transposeEv
 U _ZN6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayloadC1ERKNS0_12SparseMatrixES6_
 U _ZN6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayloadC1ERKS3_
 U _ZN6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayloadC2ERKS3_
 U _ZN6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayloadD1Ev
 U _ZN6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayloadD2Ev
 U _ZNK6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload10HasNormInfEv
 U _ZNK6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload12ApplyInverseERK18Epetra_MultiVectorRS4_
 U _ZNK6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload12UseTransposeEv
 U _ZNK6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload16OperatorRangeMapEv
 U _ZNK6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload17OperatorDomainMapEv
 U _ZNK6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload17transpose_payloadEv
 U _ZNK6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload4CommEv
 U _ZNK6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload5ApplyERK18Epetra_MultiVectorRS4_
 U _ZNK6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload5LabelEv
 U _ZNK6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload7NormInfEv
 U _ZTIN6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayloadE
```
and, picking out the destructor, from the library itself
```sh
build$ nm lib/libdeal_II.g.so | grep _ZN6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayloadD2Ev
0000000006ea4f4c T _ZN6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayloadD2Ev
```
In a few minutes I'll post the equivalent output from my Mac so we can compare.

Apart from this being a quirk of `gcc` itself, could this have something to do with the fact that `LinearOperator` is header-only, and so we never actually create an instance of the payload classes in the `deal.II` library? I'll also try to move all of the `TrilinosPayload` definitions to the header to see if that has an effect.

**Comment by jppelteret** [comment] 2017-02-06 11:16
The output from my Mac looks much the same :-/
```sh
build$ nm tests/lac/linear_operator_12.debug/linear_operator_12.debug | grep internal | grep TrilinosPayload | grep " U "
                 U __ZN6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload15SetUseTransposeEb
                 U __ZN6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload9transposeEv
                 U __ZN6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayloadC1ERKNS0_12SparseMatrixES6_
                 U __ZN6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayloadC1ERKS3_
                 U __ZN6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayloadC2ERKS3_
                 U __ZN6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayloadD1Ev
                 U __ZN6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayloadD2Ev
                 U __ZNK6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload10HasNormInfEv
                 U __ZNK6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload12ApplyInverseERK18Epetra_MultiVectorRS4_
                 U __ZNK6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload12UseTransposeEv
                 U __ZNK6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload16OperatorRangeMapEv
                 U __ZNK6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload17OperatorDomainMapEv
                 U __ZNK6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload17transpose_payloadEv
                 U __ZNK6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload4CommEv
                 U __ZNK6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload5ApplyERK18Epetra_MultiVectorRS4_
                 U __ZNK6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload5LabelEv
                 U __ZNK6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayload7NormInfEv
                 U __ZTIN6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayloadE
```
and
```sh
build$ nm lib/libdeal_II.g.dylib | grep __ZN6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayloadD2Ev
000000000764a870 T __ZN6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayloadD2Ev
```

And yet...
```sh
build$ ctest -R "lac/linear_operator_12.mpirun=1.debug"
Test project <path>/build
    Start 223: lac/linear_operator_12.mpirun=1.debug
1/1 Test #223: lac/linear_operator_12.mpirun=1.debug ...   Passed    0.76 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.93 sec
```

**Comment by bangerth** [comment] 2017-02-06 15:33
So now you've found out which symbols the test requires. Can you run the same command on the deal.II library? That should tell you which symbols are actually available, and maybe we can verify which one isn't available on linux but is on Mac?

**Comment by jppelteret** [comment] 2017-02-06 15:59
Ah yes. That would have been the clever thing to do :-)

They're a bit lengthy, so here's the output for [linux](https://github.com/dealii/dealii/files/755098/TrilinosPayload_symbols-linux.txt) and [osx](https://github.com/dealii/dealii/files/755099/TrilinosPayload_symbols-osx.txt).

I've had a go at understanding the [output that `nm` gives](https://sourceware.org/binutils/docs/binutils/nm.html), and I don't see any markers for undefined symbols in either of those lists. What is interesting is that the number of symbols emitted by `clang` is much greater than `gcc`. The symbol for the destructor (`_ZN6dealii16TrilinosWrappers8internal14LinearOperator15TrilinosPayloadD2Ev`) is in both of them.

**Comment by bangerth** [comment] 2017-02-06 17:17
You won't get a marker for an undefined symbol. It just lists what the library exports. The one symbol the compiler complains about as missing is simply not going to be there. In other words, what's necessary is the *difference* in symbols exported by the two compilers. I think you might be able to get that by sorting both outputs, removing the second leading underscore from the Mac compiler, and then applying `diff`.

**Comment by jppelteret** [comment] 2017-02-06 17:27
Wow, ok I’ll give that a look tomorrow! Thanks a lot :-)

**Comment by jppelteret** [comment] 2017-02-07 16:32
@bangerth I gave this a go using `sort -k3`, I'm sorry to say, the output remains meaningless to me and I don't see a way to compare the two lists, even with diff. The sizes are completely different (`osx` 765 entries vs 272 for `gcc`) and the mangled lines differ considerably even for (what I presume) are matching entries. This is going completely over my head.

**Comment by tamiko** [comment] 2017-02-07 19:21
@jppelteret You have a symbol lookup error on Mac and Linux is fine? What is the compiler in question? Maybe there is simply a name mangler bug (we had that on Windows quite a couple of times for cygwin).

**Comment by jppelteret** [comment] 2017-02-07 19:29
@tamiko No, its the other way round. There's a problem with `gcc 4.9.4` on linux but no problem with `clang 8.0.0` on MacOS.

**Comment by davydden** [comment] 2017-02-07 19:31
@jppelteret sorry to report, but I have problem on macOS Sierra with `clang@8.0.0`
```
5199 - lac/schur_complement_05.mpirun=1.debug (Failed)
	5200 - lac/schur_complement_05.mpirun=1.release (Failed)
	5201 - lac/schur_complement_05.mpirun=3.debug (Failed)
	5202 - lac/schur_complement_05.mpirun=3.release (Failed)
```

**Comment by jppelteret** [comment] 2017-02-07 19:34
@davydden This branch fails for you? Sigh. I must have a magic Mac :-/

**Comment by jppelteret** [comment] 2017-02-07 19:35
@davydden I meant the branch in #3931 with the fix...

**Comment by davydden** [comment] 2017-02-07 19:36
@jppelteret No idea, i just tried the master

**Comment by jppelteret** [comment] 2017-02-07 19:40
Ok thats not a huge surprise 😄 There was a necessary refactoring of `schur_complement` that somehow eluded me when I implemented the `TrilinosPayload`. Its a WIP, so this test may fail until its merged.

**Comment by tamiko** [comment] 2017-02-07 19:44
@jppelteret Yes, the convergence is unstable:
```
5177: ! DEAL:ManualSchur:cg::Starting value 5.38429e-06
5177:   DEAL:ManualSchur:cg::Convergence step 11 value 0
5177:   DEAL:SchurComplementOp:Pre::Starting value 16.9566
5177: ! DEAL:SchurComplementOp:Pre::Convergence step 59 value 1.46447e-05
5177: ! DEAL:SchurComplementOp:Main::Starting value 5.38429e-06
5177: ! DEAL:SchurComplementOp:Main::Convergence step 34 value 8.46507e-10
5177:   DEAL:SchurComplementOp:Post::Starting value 16.9566
5177: ! DEAL:SchurComplementOp:Post::Convergence step 105 value 1.46447e-05
5177: ! DEAL::Rel. norm of error in SchurOperator solve: 0.000266920
```

**Comment by bangerth** [comment] 2017-02-07 20:26
As far as the symbol thing is concerned, I'm a bit at a loss. It wouldn't be the first time we have a compiler bug about mangling, but I don't know what else to do. Do you have a way to just work around this? E.g., by moving all functions into the .cc file, or all into the .h file?

**Comment by jppelteret** [comment] 2017-02-07 20:48
I haven't seen any failures on the tester, but I'm worried that since this occurs on the last stable version of `gcc 4.x.x` that someone else will hit the problem in the future. What I can do is double check that its not a `spack` related issue. I'll install `deal.II` via `candi` in a VM tomorrow and test it again.

I wanted to more all the function definitions into the header, but I aborted that when I realised I'd have to include `trilinos_precondtion.h` to make it work (since we have a payload constructor for both sparse matrices and preconditioners). That didn't seem sensible to me but I can give it a go if you think it would pass as a work-around. They can't all go in the source file since `inverse_payload` is templatised on the solver and preconditioner.

**Comment by bangerth** [comment] 2017-02-07 20:54
Yes, that's seems awkward. What if you just moved all non-template functions into the .cc file. Does this help?

**Comment by jppelteret** [comment] 2017-02-07 20:59
That's how it is right now. All function definitions except `inverse_payload` are in `trilinos_sparse_matrix.cc`.

**Comment by bangerth** [comment] 2017-02-08 00:12
But you still see the problem?

**Comment by jppelteret** [comment] 2017-02-08 15:45
Yes, I do. As I said I'm trying this in a VM to see if its something wrong with my particular installation or whether its the compiler itself. Unfortunately I didn't originally allocate enough HDD space to the VM (and I deleted files in `deal.ii-candi/tmp/build` which has now caused the build to start over again), so I'll only be able to give further details tomorrow. Sorry!

**Closed** 2017-02-08 23:10 UTC
Labels: Bug, High Priority, Tests

**Comment by davydden** [comment] 2017-02-09 10:37
@jppelteret i can confirm that in the current master these tests work for me on Sierra! 🎉 :+1:

**Comment by jppelteret** [comment] 2017-02-09 10:38
Thanks great news indeed!

**Comment by jppelteret** [comment] 2017-02-09 12:22
@bangerth A quick report back on the symbols issue. This must be a problem with the setup on my machine. I've run the same set of tests for `master@8038274` on an `Ubuntu 14.04` VM configured with `gcc 4.9.4` and all packages installed through `apt` or `candi`. The `linear_operator`-related tests pass. On my mac these tests pass as well but on my main linux box they continue to fail. It must be time for a reinstall... Thanks for slogging through all of that with me, even though it was for nothing. I appreciate it!
