### ISSUE TITLE
MGConstrainedDoFs::initialize does not check if cells are of same level

### ISSUE THREAD

**Issue by alexrobomind** [dealii/dealii#7046] opened 2018-08-11 09:21 UTC
When constructing level constraints, MGConstrainedDoFs uses `CellAccessor::periodic_neighbor` to find face pairs which must be identically constrained onto each other. However, this function can return a cell of the same level or one level coarser (which should be covered by the hanging node constraints of the Multigrid engine). In the second case the constraint assembly will fail because the MG DoFs for the neighboring cell are not available on the present level (or, in a distributed setting, potentially because it is artificial).

A simple fix should be to change line 213 in include/deal.II/multigrid/mg_constrained_dofs.h from
`if (cell->has_periodic_neighbor(f))`
to
`if (cell->has_periodic_neighbor(f) && cell -> periodic_neighbor(f) -> level() == cell -> level())`
but I didn't have time to test that yet.

The MWE

	#include <deal.II/grid/tria.h>
	#include <deal.II/grid/grid_tools.h>
	#include <deal.II/grid/grid_generator.h>
	#include <deal.II/dofs/dof_handler.h>
	#include <deal.II/multigrid/mg_constrained_dofs.h>

	#include <vector>

	constexpr int DIM = 2;

	using namespace dealii;

	int main() {
		typedef Triangulation<DIM> Tria;
		// Create triangulation
		Tria tria(
			Tria::limit_level_difference_at_vertices
		);

		// Create coarse grid
		GridGenerator::hyper_cube(tria, -1, 1, true);

		// Create periodic boundary along x axis
		std::vector<GridTools::PeriodicFacePair<Tria::cell_iterator>> face_pairs;

		GridTools::collect_periodic_faces(
			tria,
			0, 1,
			0,
			face_pairs
		);

		tria.add_periodicity(face_pairs);

		// Refine once and then refine the corner again
		tria.refine_global(1);

		tria.begin_active() -> set_refine_flag();
		tria.prepare_coarsening_and_refinement();
		tria.execute_coarsening_and_refinement();
		
		// Assemble DoFs
		DoFHandler<DIM> dof_handler(tria);
		FE_Q<DIM> fe_q(1);

		dof_handler.distribute_dofs(fe_q);
		dof_handler.distribute_mg_dofs();

		// Try to assemble MGConstrainedDofs
		MGConstrainedDoFs constrained_dofs;
		constrained_dofs.initialize(dof_handler);

		return 0;
	}

fails on my system (spack build from the development branch) with

	--------------------------------------------------------
	An error occurred in line <1587> of file </home/alexander/git_repos/spack/opt/spack/linux-ubuntu17.10-x86_64/gcc-7.2.0/dealii-develop-urwe6fvrjadj3b6pzx62d5ghb4dndjvx/include/deal.II/dofs/dof_handler.h> in function
		dealii::types::global_dof_index dealii::DoFHandler<dim, spacedim>::MGVertexDoFs::get_index(unsigned int, unsigned int, unsigned int) const [with int dim = 2; int spacedim = 2; dealii::types::global_dof_index = unsigned int]
	The violated condition was: 
		(level >= coarsest_level) && (level <= finest_level)
	Additional information: 
		The given level 2 is not in the valid range!

	Stacktrace:
	-----------
	#0  ./mwe: void dealii::internal::DoFAccessorImplementation::get_mg_dof_indices<dealii::DoFHandler<2, 2>, false>(dealii::DoFAccessor<1, dealii::DoFHandler<2, 2>, false> const&, int, std::vector<unsigned int, std::allocator<unsigned int> >&, unsigned int)
	#1  ./mwe: void dealii::MGConstrainedDoFs::initialize<2, 2>(dealii::DoFHandler<2, 2> const&)
	#2  ./mwe: main
	--------------------------------------------------------

**Comment by masterleinad** [comment] 2018-08-11 17:13
The fix works fine. Would you mind creating a PR for this or do you prefer us to apply the fix?

**Comment by alexrobomind** [comment] 2018-08-11 19:30
Sure, I can do that. Should I add the above example as a test case?

**Comment by masterleinad** [comment] 2018-08-11 19:54
Yes, that would be great! Maybe, also test `dim==3` and make sure that `level_constraints` and `refinement_edge_indices` are correct as well.

**Comment by alexrobomind** [comment] 2018-08-11 20:43
> Maybe, also test `dim==3`

Sure thing. I'll just set it up for all 3 dimensions (nothing funky should happen for `dim==1` but it doesn't hurt). 

> and make sure that `level_constraints `and `refinement_edge_indices `are correct as well.
What would be the best way to check those? My gut guess would be to print:
- All faces which only have a coarser neighbor (with indication whether the connection internal or via periodic boundary)
- All faces which connect to faces of the same level via periodic connection
- `level_constraints` and `refinement_edge_indices` via standard print() methods

**Comment by masterleinad** [comment] 2018-08-11 20:54
I would just print `level_constraints` and `refinement_edge_indices`but, of course, you can output more if you want.

**Comment by alexrobomind** [comment] 2018-08-12 00:28
I think I have found another problem during testing. When putting out the geometry I noticed that in the case of the 2D Level 2 DoFs there seems to be an entry missing for refinement_edge_indices (the one corresponding to the "hanging node" across the periodic boundary). Indeed the function `MGTools::extract_inner_interface_dofs` does not seem to be aware of periodic neighbors. I see three possible courses from here: Either enhance / modify the method to treat periodic neighbors like internal faces, add a second method that processes periodic neighbors only, or add a second method that processes internal faces and periodic neighbors. I tend towards option 3 (keeps things simple in the `MGConstrainedDoFs` class and doesn't modify existing interfaces), but I would like to hear other peoples' opinions first.

Test output:

	--- DIM 2 OK ---
	Level 0: 
	  Faces neighboring coarser cells:
	  Refinement edge DoFs: {}

	  Faces having periodic neighbors of same level:
	    0, 2 <-> 1, 3 via periodic boundary
	    1, 3 <-> 0, 2 via periodic boundary
	  Constraint matrix:
	    0 1:  1
	    2 3:  1
	Level 1: 
	  Faces neighboring coarser cells:
	  Refinement edge DoFs: {}

	  Faces having periodic neighbors of same level:
	    0, 2 <-> 4, 5 via periodic boundary
	    2, 6 <-> 5, 8 via periodic boundary
	  Constraint matrix:
	    0 4:  1
	    2 5:  1
	    6 8:  1
	Level 2: 
	  Faces neighboring coarser cells:
	    0, 2 via periodic boundary
	    4, 5 via internal face
	    2, 6 via periodic boundary
	    6, 7 via internal face
	    5, 8 via internal face
	    7, 8 via internal face
	  Refinement edge DoFs: {[4,8]}

	  Faces having periodic neighbors of same level:
	  Constraint matrix:

Based on that I infer the following DoF topology on Level 2 in 2D (with the periodic boundary being top-down):

	  0--2--6-----?
	  |  |  |     |
	  ?--?--7     |
	  |  |  |     |
	  4--5--8-----?
	  |     |     |
	  |     |     |
	  |     |     |
	  0-----6-----?

The DoFs 0 and 2 are missing from the refinement edge DoF list.

**Comment by alexrobomind** [comment] 2018-08-12 08:31
Now that's better

	--- DIM 2 OK ---
	Level 0: 
	  Faces neighboring coarser cells:
	  Refinement edge DoFs: {}

	  Faces having periodic neighbors of same level:
	    0, 2 <-> 1, 3 via periodic boundary
	    1, 3 <-> 0, 2 via periodic boundary
	  Constraint matrix:
	    0 1:  1
	    2 3:  1
	Level 1: 
	  Faces neighboring coarser cells:
	  Refinement edge DoFs: {}

	  Faces having periodic neighbors of same level:
	    0, 2 <-> 4, 5 via periodic boundary
	    2, 6 <-> 5, 8 via periodic boundary
	  Constraint matrix:
	    0 4:  1
	    2 5:  1
	    6 8:  1
	Level 2: 
	  Faces neighboring coarser cells:
	    0, 2 via periodic boundary
	    4, 5 via internal face
	    2, 6 via periodic boundary
	    6, 7 via internal face
	    5, 8 via internal face
	    7, 8 via internal face
	  Refinement edge DoFs: {0, 2, [4,8]}

	  Faces having periodic neighbors of same level:
	  Constraint matrix:
	--- DIM 3 OK ---
	Level 0: 
	  Faces neighboring coarser cells:
	  Refinement edge DoFs: {}

	  Faces having periodic neighbors of same level:
	    0, 2, 4, 6 <-> 1, 3, 5, 7 via periodic boundary
	    1, 3, 5, 7 <-> 0, 2, 4, 6 via periodic boundary
	  Constraint matrix:
	    0 1:  1
	    2 3:  1
	    4 5:  1
	    6 7:  1
	Level 1: 
	  Faces neighboring coarser cells:
	  Refinement edge DoFs: {}

	  Faces having periodic neighbors of same level:
	    0, 2, 4, 6 <-> 8, 9, 10, 11 via periodic boundary
	    2, 12, 6, 14 <-> 9, 16, 11, 17 via periodic boundary
	    4, 6, 18, 20 <-> 10, 11, 22, 23 via periodic boundary
	    6, 14, 20, 24 <-> 11, 17, 23, 26 via periodic boundary
	  Constraint matrix:
	    0 8:  1
	    2 9:  1
	    4 10:  1
	    6 11:  1
	    12 16:  1
	    14 17:  1
	    18 22:  1
	    20 23:  1
	    24 26:  1
	Level 2: 
	  Faces neighboring coarser cells:
	    0, 2, 4, 6 via periodic boundary
	    8, 9, 10, 11 via internal face
	    2, 12, 6, 14 via periodic boundary
	    12, 14, 13, 15 via internal face
	    9, 16, 11, 17 via internal face
	    13, 15, 16, 17 via internal face
	    4, 6, 18, 20 via periodic boundary
	    18, 19, 20, 21 via internal face
	    10, 11, 22, 23 via internal face
	    19, 22, 21, 23 via internal face
	    6, 14, 20, 24 via periodic boundary
	    14, 24, 15, 25 via internal face
	    20, 21, 24, 25 via internal face
	    11, 17, 23, 26 via internal face
	    15, 25, 17, 26 via internal face
	    21, 23, 25, 26 via internal face
	  Refinement edge DoFs: {0, 2, 4, 6, [8,26]}

	  Faces having periodic neighbors of same level:
	  Constraint matrix:

**Comment by bangerth** [comment] 2018-08-13 22:35
When you say "Now that's better", do you mean that the issue is fixed by the patch you propose in #7050?

**Comment by alexrobomind** [comment] 2018-08-14 09:46
Yes, that's what I mean. Specificially I meant that the issue with the refinement edge DoFs was fixed in the second iteration.

**Closed** 2018-08-15 17:55 UTC
