### ISSUE TITLE
SolutionTransfer does not work with p::s::Triangulation when allow_artificial_cells=true

### ISSUE THREAD

**Issue by adamqc** [dealii/dealii#11668] opened 2021-02-03 07:48 UTC
When using `::SolutionTransfer` with `p::s::Triangulation` with `allow_artificial_cells=true`, it will run into assertion failure
```
An error occurred in line <2579> of file </.../include/deal.II/dofs/dof_accessor.templates.h> in function
    void dealii::DoFCellAccessor<3, 3, false>::get_dof_indices(std::vector<types::global_dof_index> &) const [dim = 3, spacedim = 3, lda = false]
The violated condition was: 
    this->is_artificial() == false
Additional information: 
    Can't ask for DoF indices on artificial cells.
```
Is this a bug or known limitation?

Here is a MWE
```
#include <deal.II/fe/fe_dgq.h>

#include <deal.II/distributed/shared_tria.h>

#include <deal.II/dofs/dof_handler.h>

#include <deal.II/grid/tria.h>
#include <deal.II/grid/grid_generator.h>

#include <deal.II/lac/vector.h>

#include <deal.II/numerics/solution_transfer.h>

int main(int argc, char** argv) {
  dealii::Utilities::MPI::MPI_InitFinalize mpi_initialization(argc, argv, 1);

  dealii::parallel::shared::Triangulation<3> tria(
      MPI_COMM_WORLD, dealii::Triangulation<3>::none, /* allow_artificial_cells */ true); 
  dealii::GridGenerator::subdivided_hyper_cube(tria, 4);

  dealii::FE_DGQ<3> fe(0);

  dealii::DoFHandler<3> dh(tria);
  dh.distribute_dofs(fe);

  dealii::SolutionTransfer<3> soltrans(dh);

  dealii::Vector<double> sol_old(dh.n_dofs());
  sol_old = 0.0;

  tria.set_all_refine_flags();

  tria.prepare_coarsening_and_refinement();
  soltrans.prepare_for_coarsening_and_refinement(sol_old);

  tria.execute_coarsening_and_refinement();

  dh.distribute_dofs(fe);
  dealii::Vector<double> sol_new(dh.n_dofs());

  soltrans.interpolate(sol_old, sol_new);

  return 0;
}

```

**Comment by peterrum** [comment] 2021-02-03 08:36
To me it looks like it does not work. In the (parallel) distributed case (what you more or less mimic with `allow_artificial_cells=true`), we normally use `parallel::distributed::SolutionTransfer` but that does not accept `p:s:T`. Is there a chance to switch to `p:d:T`?

**Comment by adamqc** [comment] 2021-02-03 08:54
The reason that I use `allow_artificial_cells=true` is that `allow_artificial_cells=false` does not compatible with `construct_multigrid_hierarchy`.
I prefer to use `p::d::Triangulation`. But it also has some limitations, e.g., we can't copy a locally refined triangulation into `p::d::Triangulation`. I am trying to overcome this but it will need some time.

**Comment by adamqc** [comment] 2021-02-07 14:37
Is there any possibility to make `SolutionTransfer` working with `p::s::Triangulation(allow_artificial_cells=true)`? If not, I will close this issue.

**Comment by bangerth** [comment] 2021-02-07 18:40
It's a bug that there is no way to do what you want to do, but it's not clear to me that `::SolutionTransfer` is the class that should do this. Maybe @marcfehling has an immediate idea of where to hook in. I could imagine that extending `p::d::SolutionTransfer` might not actually be that difficult, but then I don't know for sure either.

**Comment by marcfehling** [comment] 2021-02-08 05:26
> Maybe @marcfehling has an immediate idea of where to hook in. I could imagine that extending `p::d::SolutionTransfer` might not actually be that difficult, but then I don't know for sure either.

Maybe a simple check for artifical cells in both `prepare()` and `interpolate()` will do the trick. We can then merge all `cell_maps` via global communication.

Or we may have to use the trick and temporarily set and unset the true subdomain ids in `::SolutionTransfer` in both `prepare()` and `interpolate()`. Conceptually for `p::s::Triangulations`, the process of transferring a solution should be the same with or without artificial cells. Since we enumerate dofs also on artifical cells for `p::s::Triangulations`, I think this option should be the preferred way to deal with this.

I will have a look soon.

**Comment by marcfehling** [comment] 2021-02-10 03:50
I have a patch prepared in this [branch](https://github.com/marcfehling/dealii/tree/soltrans-shared), but the provided test fails and I don't know why. I'll figure out the cause and will open a PR once this works.

**Comment by peterrum** [comment] 2021-02-10 10:14
> I have a patch prepared in this branch, but the provided test fails and I don't know why. I'll figure out the cause and will open a PR once this works.

**Comment by peterrum** [comment] 2021-02-10 10:18
> I have a patch prepared in this branch, but the provided test fails and I don't know why. I'll figure out the cause and will open a PR once this works.

@marcfehling  A general question: are you sure that `SolutionTransfer` works for `p:s:T` without artificial cells? I have the feeling it does not and you might have to use in any case `p::d::SolutionTransfer`. At least after having a look at the code for a minute, I cannot see any communication within the relevant functions of `SolutionTransfer`.

**Comment by marcfehling** [comment] 2021-02-10 18:29
> @marcfehling A general question: are you sure that `SolutionTransfer` works for `p:s:T` without artificial cells? I have the feeling it does not and you might have to use in any case `p::d::SolutionTransfer`. At least after having a look at the code for a minute, I cannot see any communication within the relevant functions of `SolutionTransfer`.

@peterrum Well we mention to use the basic `SolutionTransfer` class as a possible extension for `step-18`. And I recall that we have tests for `p::s::Triangulation` and the basic `SolutionTransfer` class, but I can't find them at the moment.

There is also the possibility to use the more abstract `CellDataTransfer` class for this. Right now in this moment, I think of rewriting the `SolutionTransfer` classes to become descendants of the `CellDataTransfer` one. They both do essentially the same, with the latter being more general. And I know this works for `p::s::Triangulations` both with and without artificial cells as I remember spending a lot of time to make it work :-) I need to advertise this class more...

**Comment by marcfehling** [comment] 2021-02-11 19:09
> I prefer to use `p::d::Triangulation`. But it also has some limitations, e.g., we can't copy a locally refined triangulation into `p::d::Triangulation`. I am trying to overcome this but it will need some time.

I don't know your use case in detail. Would it be possible for you to begin with `p::d::Triangulation` right from the start? Why do you need locally refined `::Triangulation` objects in the first place? You should be able to copy a standard Triangulation, but you would need to do build a `p::d::Triangulation` manually layer by layer I presume.

Anyways, please try #11733 and confirm that this works in your use case.

**Closed** 2021-02-17 12:12 UTC
