### ISSUE TITLE
Improve performance of ChartManifold::get_new_point

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#2895] opened 2016-07-31 18:02 UTC
When working on a spherical geometry (I attached a `SphericalManifold` to a hyper_shell), I realized that computing the mapping support points takes almost half the computation time of one of my programs when using polynomial degree 5 for the mapping and 4 for the solution (this is 2D for simpler analysis, I have the same problem in 3D). I ran the program through my favorite profiler callgrind (well, the one with way best visualization of problematic regions):
![mapping_manifold_callgrind](https://cloud.githubusercontent.com/assets/8276200/17278232/7e18d24a-5758-11e6-9317-f69985bb28b1.png)
While there is probably little to complain about the `atan2`, `sin_avx` and `cos_avx` calls as that describes the geometry, I am concerned about the other half which consists of `malloc` and `free` calls that appear to be the main problem on my cluster (28 cores sharing memory). The reason for that is that we repeatedly create and destroy `Quadrature` objects in this function. The two places in question are `mapping_q_generic.cc:3514` and `manifold.cc:538` where a new quadrature formula is created for **every point** we compute. We really need find a better style for passing information around. I can work on this, but I would like to hear the opinions of @luca-heltai and others before I start doing. My idea is to either teach

**Comment by bangerth** [comment] 2016-07-31 19:01
Duplicate of #2896.

**Closed by bangerth** 2016-07-31 19:01 UTC
