### ISSUE TITLE
Configure error with fedora 29

### ISSUE THREAD

**Issue by ztdepztdep** [dealii/dealii#7888] opened 2019-04-03 13:30 UTC
Include /home/ztdep/Downloads/dealii-9.0.0/cmake/setup_finalize.cmake
CMake Error at cmake/setup_finalize.cmake:95 (MESSAGE):
  

    Configuration error: Cannot compile a test program with the final set of
    compiler and linker flags:
      CXX flags (DEBUG): -pedantic -fPIC -Wall -Wextra -Wpointer-arith -Wwrite-strings -Wsynth -Wsign-compare -Wswitch -Woverloaded-virtual -Wno-placement-new -Wno-deprecated-declarations -Wno-literal-suffix -fopenmp-simd -std=c++17 -Wno-parentheses -Wno-unused-local-typedefs -Og -ggdb -Wa,--compress-debug-sections
      LD flags  (DEBUG): -Wl,--as-needed -rdynamic -fuse-ld=gold -Wl,-rpath -Wl,/usr/local/lib -Wl,--enable-new-dtags -pthread -ggdb
      LIBRARIES (DEBUG): /usr/local/lib/libmpicxx.so;/usr/lib64/libz.so;/usr/lib64/libboost_iostreams.so;/usr/lib64/libboost_serialization.so;/usr/lib64/libboost_system.so;/usr/lib64/libboost_thread.so;-pthread;/usr/lib64/libboost_regex.so;/usr/lib64/libboost_chrono.so;/usr/lib64/libboost_date_time.so;/usr/lib64/libboost_atomic.so;/usr/lib64/libmetis.so;/home/ztdep/lib/petsc-3.10.3/lib/libpetsc.so;/home/ztdep/lib/petsc-3.10.3/lib/libscalapack.a;/home/ztdep/lib/petsc-3.10.3/lib/libHYPRE.a;/usr/lib64/liblapack.so;/usr/lib64/libblas.so;/home/ztdep/lib/petsc-3.10.3/lib/libhdf5hl_fortran.so;/home/ztdep/lib/petsc-3.10.3/lib/libhdf5_fortran.so;/home/ztdep/lib/petsc-3.10.3/lib/libmetis.so;/usr/lib64/libX11.so;pthread;/usr/local/lib/libmpifort.so;dl;/usr/lib64/libarpack.so;/usr/lib64/libopenblas.so;gfortran;quadmath;m;c;gcc_s;gcc;/home/ztdep/lib/petsc-3.10.3/lib/libhdf5_hl.so;/home/ztdep/lib/petsc-3.10.3/lib/libhdf5.so;/usr/local/lib/libmpi.so;/home/ztdep/Downloads/muparser-2.2.6.1/lib/libmuparser.so;
    

  

Call Stack (most recent call first):
  cmake/macros/macro_verbose_include.cmake:19 (INCLUDE)
  CMakeLists.txt:132 (VERBOSE_INCLUDE)

**Comment by tamiko** [comment] 2019-04-03 14:12
Would you mind sending us the error message of the compiler invocation?
This one you can find in the file CMakeFiles/CMakeError.log

Close to the end of the file there should be corresponding test. The
output should start with the string

  Performing C++ SOURCE FILE Test DEAL_II_HAVE_USABLE_FLAGS_DEBUG

We need the log output following that line.

Best,
Matthias

**Comment by tamiko** [comment] 2019-05-12 21:55
@ztdepztdep *ping*

**Comment by drwells** [comment] 2021-06-11 17:19
We cannot reproduce without more information. Closing.

**Closed by drwells** 2021-06-11 17:19 UTC
