### ISSUE TITLE
[C++17] Use <filesystem> in gmsh/utilities.cc

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#6510] opened 2018-05-07 07:33 UTC
In `gmsh/create_triangulation` we are currently (as of #6508) using the `POSIX` `mkdtemp`.
After the release, we should use `boost::filesystem` resp. `std::filesystem` (C++17) for creating files and directories in a suitable manner.
This requires to enforce that the `Boost` library used is built with the `filesystem` module. In particualr, we need to include the module in our bundled package.

**Comment by kronbichler** [comment] 2020-03-20 16:27
In the new boost-1.70, we include the `filesystem` module. Thus, I adjust the title that we should use boost's facilities for the relevant file in `source/gmsh/utilities.cc`.

**Comment by bangerth** [comment] 2020-03-20 16:51
The problem is that we only require boost 1.59 when using the external boost. Does that version have the `fileystem` lib?

**Comment by masterleinad** [comment] 2020-03-20 17:05
> The problem is that we only require boost 1.59 when using the external boost. Does that version have the `fileystem` lib?

Yes, `unique_path` is at least in 1.44. Unfortunately, `unique_path` is ont part of `std::filesystem` and I have no good idea for a path forward that doesn't rely on platform-dependent functions.

**Comment by masterleinad** [comment] 2020-04-25 18:31
No priority here. Moving.

**Comment by marcfehling** [comment] 2021-05-01 02:54
We'll move to the C++17 standard with release 10.0. Then this will be trivial to solve. I'll move the milestone forward.

**Comment by bangerth** [comment] 2021-12-29 01:37
Let's do this once we have C++17, like in #12080.

**Comment by bangerth** [comment] 2023-10-30 17:47
If anyone had an interest, this can now be done!

**Comment by bangerth** [comment] 2023-11-01 00:53
The issue in question here is to replace the call to `mkdtemp`, a function that creates a temporary directory with a unique name. Unfortunately, there is no C++17 facility to do that -- only functions that create directories with names *we* select, but that defeats the atomic nature of `mkdtemp`.

So I think we need to close this issue.

**Closed by bangerth** 2023-11-01 00:53 UTC
Labels: Enhancement, Starter project, Miscellaneous, C++17
