### ISSUE TITLE
dealii 9.0.1: cmake failing with petsc 3.10.2

### ISSUE THREAD

**Issue by zeli86** [dealii/dealii#7423] opened 2018-11-06 18:54 UTC
I've tried to compile deal.ii 9.0.1 with petsc-3.10.2 and the following error occured:

-- Include /home/zeli/local/src/dealii-9.0.1/cmake/configure/configure_3_petsc.cmake
-- Found PETSC_LIBRARY
-- Found PETSC_INCLUDE_DIR_ARCH
-- Found PETSC_INCLUDE_DIR_COMMON
-- Found PETSC_PETSCVARIABLES
CMake Error at cmake/modules/FindPETSC.cmake:157 (LIST):
  list index: 1 out of range (-1, 0)
Call Stack (most recent call first):
  cmake/macros/macro_find_package.cmake:27 (_FIND_PACKAGE)
  cmake/configure/configure_3_petsc.cmake:24 (FIND_PACKAGE)
  build/CMakeFiles/CMakeTmp/evaluate_expression.tmp:1 (FEATURE_PETSC_FIND_EXTERNAL)
  cmake/macros/macro_evaluate_expression.cmake:30 (INCLUDE)
  cmake/macros/macro_configure_feature.cmake:237 (EVALUATE_EXPRESSION)
  cmake/configure/configure_3_petsc.cmake:141 (CONFIGURE_FEATURE)
  cmake/macros/macro_verbose_include.cmake:19 (INCLUDE)
  CMakeLists.txt:124 (VERBOSE_INCLUDE)

Without setting the petsc path everything works fine.

**Comment by drwells** [comment] 2018-11-06 18:58
Could you please post some more information about what went wrong? In particular, could you post `detailed.log` from the build directory?

**Comment by zeli86** [comment] 2018-11-06 19:02
content detailed.log

###
#
#  deal.II configuration:
#        CMAKE_BUILD_TYPE:       Release
#        BUILD_SHARED_LIBS:      ON
#        CMAKE_INSTALL_PREFIX:   /home/zeli/local/opt/deal.ii-9.0.1
#        CMAKE_SOURCE_DIR:       /home/zeli/local/src/dealii-9.0.1
#                                (version 9.0.1)
#        CMAKE_BINARY_DIR:       /home/zeli/local/src/dealii-9.0.1/build
#        CMAKE_CXX_COMPILER:     GNU 8.2.1 on platform Linux x86_64
#                                /home/zeli/local/opt/openmpi-3.1.3/bin/mpicxx
#        CMAKE_C_COMPILER:       /home/zeli/local/opt/openmpi-3.1.3/bin/mpicc
#        CMAKE_Fortran_COMPILER: /home/zeli/local/opt/openmpi-3.1.3/bin/mpif90
#        CMAKE_GENERATOR:        Unix Makefiles
#
#  Base configuration (prior to feature configuration):
#        DEAL_II_CXX_FLAGS:            -pedantic -fPIC -Wall -Wextra -Wpointer-arith -Wwrite-strings -Wsynth -Wsign-compare -Wswitch -Woverloaded-virtual -Wno-placement-new -Wno-deprecated-declarations -Wno-literal-suffix -fopenmp-simd -std=c++17
#        DEAL_II_CXX_FLAGS_RELEASE:    -O2 -funroll-loops -funroll-all-loops -fstrict-aliasing -Wno-unused-local-typedefs
#        DEAL_II_LINKER_FLAGS:         -Wl,--as-needed -rdynamic
#        DEAL_II_LINKER_FLAGS_RELEASE: 
#        DEAL_II_DEFINITIONS:          
#        DEAL_II_DEFINITIONS_RELEASE:  
#        DEAL_II_USER_DEFINITIONS:     
#        DEAL_II_USER_DEFINITIONS_REL: 
#        DEAL_II_INCLUDE_DIRS          
#        DEAL_II_USER_INCLUDE_DIRS:    
#        DEAL_II_BUNDLED_INCLUDE_DIRS: 
#        DEAL_II_LIBRARIES:            m
#        DEAL_II_LIBRARIES_RELEASE:    
#        DEAL_II_COMPILER_VECTORIZATION_LEVEL: 1
#
#  Configured Features (DEAL_II_ALLOW_BUNDLED = ON, DEAL_II_ALLOW_AUTODETECTION = ON):
#      ( DEAL_II_WITH_64BIT_INDICES = OFF )
#      ( DEAL_II_WITH_ADOLC = OFF )
#      ( DEAL_II_WITH_ARPACK = OFF )
#      ( DEAL_II_WITH_ASSIMP = OFF )
#        DEAL_II_WITH_BOOST set up with bundled packages
#            BOOST_CXX_FLAGS = -Wno-unused-local-typedefs
#            BOOST_DEFINITIONS = BOOST_NO_AUTO_PTR
#            BOOST_USER_DEFINITIONS = BOOST_NO_AUTO_PTR
#            BOOST_BUNDLED_INCLUDE_DIRS = /home/zeli/local/src/dealii-9.0.1/bundled/boost-1.62.0/include
#            BOOST_LIBRARIES = rt
#      ( DEAL_II_WITH_CUDA = OFF )
#        DEAL_II_WITH_CXX14 = ON
#        DEAL_II_WITH_CXX17 = ON
#      ( DEAL_II_WITH_GMSH = OFF )
#        DEAL_II_WITH_GSL set up with external dependencies
#            GSL_VERSION = 2.5
#            GSL_DIR = /home/zeli/local/opt/gsl-2.5
#            GSL_INCLUDE_DIRS = /home/zeli/local/opt/gsl-2.5/include
#            GSL_USER_INCLUDE_DIRS = /home/zeli/local/opt/gsl-2.5/include
#            GSL_LIBRARIES = /home/zeli/local/opt/gsl-2.5/lib64/libgsl.so;/home/zeli/local/opt/gsl-2.5/lib64/libgslcblas.so
#      ( DEAL_II_WITH_HDF5 = OFF )
#        DEAL_II_WITH_LAPACK set up with external dependencies
#            LAPACK_DIR = /home/zeli/local/opt/lapack-3.8.0
#            LAPACK_WITH_64BIT_BLAS_INDICES = OFF
#            LAPACK_LINKER_FLAGS = 
#            LAPACK_LIBRARIES = /home/zeli/local/opt/lapack-3.8.0/lib64/liblapack.so;/home/zeli/local/opt/lapack-3.8.0/lib64/libblas.so;mpi_usempif08;mpi_usempi_ignore_tkr;mpi_mpifh;mpi;gfortran;quadmath;m;pthread;c
#      ( DEAL_II_WITH_METIS = OFF )
#        DEAL_II_WITH_MPI set up with external dependencies
#            MPI_VERSION = 3.1
#            MPI_C_COMPILER = /home/zeli/local/opt/openmpi-3.1.3/bin/mpicc
#            MPI_CXX_COMPILER = /home/zeli/local/opt/openmpi-3.1.3/bin/mpicxx
#            MPI_Fortran_COMPILER = /home/zeli/local/opt/openmpi-3.1.3/bin/mpif90
#            MPI_CXX_FLAGS = 
#            MPI_LINKER_FLAGS = -Wl,-rpath  -Wl,/home/zeli/local/opt/openmpi-3.1.3/lib64  -Wl,--enable-new-dtags
#            MPI_INCLUDE_DIRS = /home/zeli/local/opt/openmpi-3.1.3/include
#            MPI_USER_INCLUDE_DIRS = /home/zeli/local/opt/openmpi-3.1.3/include
#            MPI_LIBRARIES = /home/zeli/local/opt/openmpi-3.1.3/lib64/libmpi_usempif08.so;/home/zeli/local/opt/openmpi-3.1.3/lib64/libmpi_usempi_ignore_tkr.so;/home/zeli/local/opt/openmpi-3.1.3/lib64/libmpi_mpifh.so;/home/zeli/local/opt/openmpi-3.1.3/lib64/libmpi.so
#        DEAL_II_WITH_MUPARSER set up with external dependencies
#            MUPARSER_VERSION = 2.2.6
#            MUPARSER_DIR = /home/zeli/local/opt/muparser-2.2.6.1
#            MUPARSER_INCLUDE_DIRS = /home/zeli/local/opt/muparser-2.2.6.1/include
#            MUPARSER_LIBRARIES = /home/zeli/local/opt/muparser-2.2.6.1/lib64/libmuparser.so
#      ( DEAL_II_WITH_NANOFLANN = OFF )
#      ( DEAL_II_WITH_NETCDF = OFF )
#      ( DEAL_II_WITH_OPENCASCADE = OFF )
#        DEAL_II_WITH_P4EST set up with external dependencies
#            P4EST_VERSION = 2.0
#            P4EST_DIR = /home/zeli/local/opt/p4est-2.0
#            P4EST_INCLUDE_DIRS = /home/zeli/local/opt/p4est-2.0/include
#            P4EST_USER_INCLUDE_DIRS = /home/zeli/local/opt/p4est-2.0/include
#            P4EST_LIBRARIES = /home/zeli/local/opt/p4est-2.0/lib64/libp4est.so;/home/zeli/local/opt/p4est-2.0/lib64/libsc.so;/home/zeli/local/opt/lapack-3.8.0/lib64/liblapack.so;/home/zeli/local/opt/lapack-3.8.0/lib64/libblas.so;mpi_usempif08;mpi_usempi_ignore_tkr;mpi_mpifh;mpi;gfortran;quadmath;m;pthread;c;/home/zeli/local/opt/openmpi-3.1.3/lib64/libmpi.so
#        DEAL_II_WITH_PETSC set up with external dependencies
#            PETSC_VERSION = 3.10.2.0
#            PETSC_DIR = /home/zeli/local/opt/petsc-3.10.2
#            PETSC_INCLUDE_DIRS = /home/zeli/local/opt/petsc-3.10.2/include
#            PETSC_USER_INCLUDE_DIRS = /home/zeli/local/opt/petsc-3.10.2/include
#            PETSC_LIBRARIES = /home/zeli/local/opt/petsc-3.10.2/lib/libpetsc.so;/home/zeli/local/opt/petsc-3.10.2/lib/libcmumps.a;/home/zeli/local/opt/petsc-3.10.2/lib/libdmumps.a;/home/zeli/local/opt/petsc-3.10.2/lib/libsmumps.a;/home/zeli/local/opt/petsc-3.10.2/lib/libzmumps.a;/home/zeli/local/opt/petsc-3.10.2/lib/libmumps_common.a;/home/zeli/local/opt/petsc-3.10.2/lib/libpord.a;/home/zeli/local/opt/petsc-3.10.2/lib/libscalapack.a;/home/zeli/local/opt/petsc-3.10.2/lib/libHYPRE.a;/home/zeli/local/opt/petsc-3.10.2/lib/libflapack.a;/home/zeli/local/opt/petsc-3.10.2/lib/libfblas.a;/home/zeli/local/opt/petsc-3.10.2/lib/libptesmumps.a;/home/zeli/local/opt/petsc-3.10.2/lib/libptscotchparmetis.a;/home/zeli/local/opt/petsc-3.10.2/lib/libptscotch.a;/home/zeli/local/opt/petsc-3.10.2/lib/libptscotcherr.a;/home/zeli/local/opt/petsc-3.10.2/lib/libesmumps.a;/home/zeli/local/opt/petsc-3.10.2/lib/libscotch.a;/home/zeli/local/opt/petsc-3.10.2/lib/libscotcherr.a;/home/zeli/local/opt/openmpi-3.1.3/lib64/libmpi_usempif08.so;/home/zeli/local/opt/openmpi-3.1.3/lib64/libmpi_usempi_ignore_tkr.so;/home/zeli/local/opt/openmpi-3.1.3/lib64/libmpi_mpifh.so;/home/zeli/local/opt/openmpi-3.1.3/lib64/libmpi.so;gfortran;quadmath;rt;m;pthread;/usr/lib64/libz.so;dl
#      ( DEAL_II_WITH_SCALAPACK = OFF )
#      ( DEAL_II_WITH_SLEPC = OFF )
#      ( DEAL_II_WITH_SUNDIALS = OFF )
#      ( DEAL_II_WITH_THREADS = OFF )
#      ( DEAL_II_WITH_TRILINOS = OFF )
#        DEAL_II_WITH_UMFPACK set up with bundled packages
#            UMFPACK_BUNDLED_INCLUDE_DIRS = /home/zeli/local/src/dealii-9.0.1/bundled/umfpack/UMFPACK/Include;/home/zeli/local/src/dealii-9.0.1/bundled/umfpack/AMD/Include
#        DEAL_II_WITH_ZLIB set up with external dependencies
#            ZLIB_VERSION = 1.2.8
#            ZLIB_INCLUDE_DIRS = /usr/include
#            ZLIB_LIBRARIES = /usr/lib64/libz.so
#
#  Component configuration:
#      ( DEAL_II_COMPONENT_DOCUMENTATION = OFF )
#        DEAL_II_COMPONENT_EXAMPLES
#      ( DEAL_II_COMPONENT_PACKAGE = OFF )
#      ( DEAL_II_COMPONENT_PYTHON_BINDINGS = OFF )
#
###

**Comment by bangerth** [comment] 2018-11-06 21:48
Not that I would know what the problem is, but the error happens here:
```
CMake Error at cmake/modules/FindPETSC.cmake:157 (LIST):
list index: 1 out of range (-1, 0)
```
and the code in question is this, at least on master:
```
  # Remove petsc's own include directories:
  IF(NOT "${_petsc_includes}" STREQUAL "")
    LIST(REMOVE_AT _petsc_includes 0 1)                    #### line 157
  ENDIF()
```

**Comment by tamiko** [comment] 2018-11-06 22:17
Wow this is some pretty terrible piece of CMake logic: If the variable is not an empty string, remove the first and second element.

It turns out that this is also entirely irrelevant. The final list of includes gets deduplicated nowadays.

**Comment by drwells** [comment] 2018-11-06 22:43
Should we keep this open until we get another 9.0 fix?

**Comment by tamiko** [comment] 2018-11-07 01:07
@zeli86 Can you please check whether applying the following diff
  https://github.com/dealii/dealii/commit/e359a202361f33e4694372c9b43922c6850853b2.diff
resolves the issue?

**Comment by drwells** [comment] 2018-11-08 23:19
I can build and test 9.0.1 with PETSc 3.10.2 successfully.

**Comment by drwells** [comment] 2018-11-19 20:42
Since I can successfully build with 9.0.1 (both the release and the present state of the branch) on two different machines (Arch Linux and Ubuntu 16.04) lets close this. We can always open another issue if this was not a complete fix.

**Closed by drwells** 2018-11-19 20:42 UTC
Labels: Build system
