### ISSUE TITLE
Serialization failures with boost-1.65.0

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#5085] opened 2017-09-14 15:37 UTC
With (almost) newest boost 1.65.0 I get a number of serialization failures [1]

```
In file included from /usr/include/boost/serialization/vector.hpp:26:0,
                 from /srv/testsuite/dealii/include/deal.II/base/index_set.h:23,
                 from /srv/testsuite/dealii/include/deal.II/lac/vector.h:24,
                 from /srv/testsuite/dealii/include/deal.II/lac/petsc_vector_base.h:26,
                 from /srv/testsuite/dealii/tests/distributed_grids/../tests.h:74,
                 from /srv/testsuite/dealii/tests/distributed_grids/grid_tools_exchange_cell_data_01.cc:19:
/usr/include/boost/serialization/access.hpp: In instantiation of ‘static void boost::serialization::access::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::binary_oarchive; T = std::array<unsigned int, 4ul>]’:
/usr/include/boost/serialization/serialization.hpp:68:69:   required from ‘void boost::serialization::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::binary_oarchive; T = std::array<unsigned int, 4ul>]’
/usr/include/boost/serialization/serialization.hpp:126:23:   required from ‘void boost::serialization::serialize_adl(Archive&, T&, unsigned int) [with Archive = boost::archive::binary_oarchive; T = std::array<unsigned int, 4ul>]’
/usr/include/boost/archive/detail/oserializer.hpp:154:5:   required from ‘void boost::archive::detail::oserializer<Archive, T>::save_object_data(boost::archive::detail::basic_oarchive&, const void*) const [with Archive = boost::archive::binary_oarchive; T = std::array<unsigned int, 4ul>]’
/usr/include/boost/archive/detail/oserializer.hpp:103:1:   required from ‘class boost::archive::detail::oserializer<boost::archive::binary_oarchive, std::array<unsigned int, 4ul> >’
/usr/include/boost/archive/detail/oserializer.hpp:255:13:   required from ‘static void boost::archive::detail::save_non_pointer_type<Archive>::save_standard::invoke(Archive&, const T&) [with T = std::array<unsigned int, 4ul>; Archive = boost::archive::binary_oarchive]’
/usr/include/boost/archive/detail/oserializer.hpp:310:28:   [ skipping 22 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/boost/archive/binary_oarchive_impl.hpp:59:9:   required from ‘void boost::archive::binary_oarchive_impl<Archive, Elem, Tr>::save_override(T&) [with T = const dealii::parallel::GridTools::internal::CellDataTransferBuffer<2, double>; Archive = boost::archive::binary_oarchive; Elem = char; Tr = std::char_traits<char>]’
/usr/include/boost/archive/detail/interface_oarchive.hpp:70:9:   required from ‘Archive& boost::archive::detail::interface_oarchive<Archive>::operator<<(const T&) [with T = dealii::parallel::GridTools::internal::CellDataTransferBuffer<2, double>; Archive = boost::archive::binary_oarchive]’
/srv/testsuite/dealii/include/deal.II/distributed/grid_tools.h:221:21:   required from ‘std::vector<char> dealii::parallel::GridTools::internal::CellDataTransferBuffer<dim, T>::pack_data() const [with int dim = 2; T = double]’
/srv/testsuite/dealii/include/deal.II/distributed/grid_tools.h:353:28:   required from ‘void dealii::parallel::GridTools::exchange_cell_data_to_ghosts(const MeshType&, std::function<boost::optional<T>(const typename MeshType::active_cell_iterator&)>, std::function<void(const typename MeshType::active_cell_iterator&, const DataType&)>) [with DataType = double; MeshType = dealii::parallel::distributed::Triangulation<2, 2>; typename MeshType::active_cell_iterator = dealii::TriaActiveIterator<dealii::CellAccessor<2, 2> >]’
/srv/testsuite/dealii/tests/distributed_grids/grid_tools_exchange_cell_data_01.cc:70:4:   required from ‘void test() [with int dim = 2]’
/srv/testsuite/dealii/tests/distributed_grids/grid_tools_exchange_cell_data_01.cc:83:12:   required from here
/usr/include/boost/serialization/access.hpp:116:9: error: ‘struct std::array<unsigned int, 4ul>’ has no member named ‘serialize’
         t.serialize(ar, file_version);
         ^
/usr/include/boost/serialization/access.hpp: In instantiation of ‘static void boost::serialization::access::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::binary_iarchive; T = std::array<unsigned int, 4ul>]’:
/usr/include/boost/serialization/serialization.hpp:68:69:   required from ‘void boost::serialization::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::binary_iarchive; T = std::array<unsigned int, 4ul>]’
/usr/include/boost/serialization/serialization.hpp:126:23:   required from ‘void boost::serialization::serialize_adl(Archive&, T&, unsigned int) [with Archive = boost::archive::binary_iarchive; T = std::array<unsigned int, 4ul>]’
/usr/include/boost/archive/detail/iserializer.hpp:192:5:   required from ‘void boost::archive::detail::iserializer<Archive, T>::load_object_data(boost::archive::detail::basic_iarchive&, void*, unsigned int) const [with Archive = boost::archive::binary_iarchive; T = std::array<unsigned int, 4ul>]’
/usr/include/boost/archive/detail/iserializer.hpp:120:1:   required from ‘class boost::archive::detail::iserializer<boost::archive::binary_iarchive, std::array<unsigned int, 4ul> >’
/usr/include/boost/archive/detail/iserializer.hpp:410:13:   required from ‘static void boost::archive::detail::load_non_pointer_type<Archive>::load_standard::invoke(Archive&, const T&) [with T = std::array<unsigned int, 4ul>; Archive = boost::archive::binary_iarchive]’
/usr/include/boost/archive/detail/iserializer.hpp:462:28:   [ skipping 22 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/boost/archive/binary_iarchive_impl.hpp:58:9:   required from ‘void boost::archive::binary_iarchive_impl<Archive, Elem, Tr>::load_override(T&) [with T = dealii::parallel::GridTools::internal::CellDataTransferBuffer<2, double>; Archive = boost::archive::binary_iarchive; Elem = char; Tr = std::char_traits<char>]’
/usr/include/boost/archive/detail/interface_iarchive.hpp:68:9:   required from ‘Archive& boost::archive::detail::interface_iarchive<Archive>::operator>>(T&) [with T = dealii::parallel::GridTools::internal::CellDataTransferBuffer<2, double>; Archive = boost::archive::binary_iarchive]’
/srv/testsuite/dealii/include/deal.II/distributed/grid_tools.h:251:19:   required from ‘void dealii::parallel::GridTools::internal::CellDataTransferBuffer<dim, T>::unpack_data(const std::vector<char>&) [with int dim = 2; T = double]’
/srv/testsuite/dealii/include/deal.II/distributed/grid_tools.h:379:11:   required from ‘void dealii::parallel::GridTools::exchange_cell_data_to_ghosts(const MeshType&, std::function<boost::optional<T>(const typename MeshType::active_cell_iterator&)>, std::function<void(const typename MeshType::active_cell_iterator&, const DataType&)>) [with DataType = double; MeshType = dealii::parallel::distributed::Triangulation<2, 2>; typename MeshType::active_cell_iterator = dealii::TriaActiveIterator<dealii::CellAccessor<2, 2> >]’
/srv/testsuite/dealii/tests/distributed_grids/grid_tools_exchange_cell_data_01.cc:70:4:   required from ‘void test() [with int dim = 2]’
/srv/testsuite/dealii/tests/distributed_grids/grid_tools_exchange_cell_data_01.cc:83:12:   required from here
/usr/include/boost/serialization/access.hpp:116:9: error: ‘struct std::array<unsigned int, 4ul>’ has no member named ‘serialize’
```

@tjhei *ping*

[1] https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=11385

**Comment by tjhei** [comment] 2017-09-14 16:59
On it. I can reproduce it.

**Comment by tamiko** [comment] 2017-09-14 17:43
Very nice!

**Comment by tjhei** [comment] 2017-09-14 19:58
Uhoh, I think this won't fix it.

**Comment by tjhei** [comment] 2017-09-15 18:14
While #5089 makes the tests compile, they fail with a segfault now. I am looking at it.

**Comment by tjhei** [comment] 2017-09-15 18:18
It looks like many serialization tests crash with clang5.0: https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=11412

**Comment by tamiko** [comment] 2017-09-15 19:32
@tjhei For more context: This is clang-5.0.0 with libc++-5.0.0 and newest boost.
I will try to reproduce by linking against gnu's libstdc++ to rule out an issue with combining newest boost and libc++5.0.0

**Comment by tjhei** [comment] 2017-09-15 19:40
I see crashes with older clang versions too (3.7.1).

**Comment by tamiko** [comment] 2017-09-16 00:16
@tjhei I also get crashes of the form (serialization/triangulation_01)
```
Thread 1 "triangulation_0" received signal SIGSEGV, Segmentation fault.
0x00007fffcde6ba44 in boost::serialization::typeid_system::extended_type_info_typeid_0::type_unregister() () from /usr/lib64/libboost_serialization.so.1.65.0
(gdb) bt
#0  0x00007fffcde6ba44 in boost::serialization::typeid_system::extended_type_info_typeid_0::type_unregister() () from /usr/lib64/libboost_serialization.so.1.65.0
#1  0x0000000000643ed2 in boost::serialization::extended_type_info_typeid<std::__1::vector<unsigned int, std::__1::allocator<unsigned int> > >::~extended_type_info_typeid (
    this=0x959df8 <boost::serialization::singleton<boost::serialization::extended_type_info_typeid<std::__1::vector<unsigned int, std::__1::allocator<unsigned int> > > >::get_instance()::t>)
    at /usr/include/boost/serialization/extended_type_info_typeid.hpp:96
#2  0x00007fffc27541c8 in ?? () from /lib64/libc.so.6
#3  0x00007fffc275422a in exit () from /lib64/libc.so.6
#4  0x00007fffc273c431 in __libc_start_main () from /lib64/libc.so.6
#5  0x0000000000627e9a in _start () at /usr/include/boost/serialization/singleton.hpp:155
```
but only if compiled with `WITH_MPI=ON`.

**Comment by tamiko** [comment] 2017-09-16 00:42
here is a better backtrace (again clang-5.0) this time with libstdc++:
```
#0  0x00007fffc13c2f60 in raise () from /lib64/libc.so.6
#1  0x00007fffc13c4c2a in abort () from /lib64/libc.so.6
#2  0x00007fffc13bacc7 in ?? () from /lib64/libc.so.6
#3  0x00007fffc13bad82 in __assert_fail () from /lib64/libc.so.6
#4  0x000000000066dd2d in boost::archive::detail::pointer_oserializer<boost::archive::text_oarchive, dealii::internal::Triangulation::TriaFaces<1> >::save_object_ptr (this=<optimized out>, 
    ar=..., x=0x0) at /usr/include/boost/archive/detail/oserializer.hpp:191
#5  0x00007fffcc862798 in ?? () from /usr/lib64/libboost_serialization.so.1.65.0
#6  0x000000000066d9aa in boost::archive::detail::interface_oarchive<boost::archive::text_oarchive>::operator<< <dealii::internal::Triangulation::TriaFaces<1> const*> (this=0x7fffffffda70, 
    t=@0x7fffffffd150: 0x0) at /usr/include/boost/archive/detail/interface_oarchive.hpp:70
#7  0x000000000066d8fa in boost::serialization::serialize_adl<boost::archive::text_oarchive, boost::serialization::nvp<dealii::internal::Triangulation::TriaFaces<1> const* const> > (ar=..., 
    t=..., file_version=0) at /usr/include/boost/serialization/serialization.hpp:126
#8  0x000000000066d7ca in boost::archive::detail::interface_oarchive<boost::archive::text_oarchive>::operator<< <boost::serialization::nvp<dealii::internal::Triangulation::TriaFaces<1> const* const> > (this=0x7fffffffda70, t=...) at /usr/include/boost/archive/detail/interface_oarchive.hpp:70
#9  0x000000000066d798 in boost::serialization::save<boost::archive::text_oarchive, dealii::internal::Triangulation::TriaFaces<1> > (ar=..., t=...)
    at /usr/include/boost/serialization/unique_ptr.hpp:38
#10 0x000000000066d74a in boost::serialization::free_saver<boost::archive::text_oarchive, std::unique_ptr<dealii::internal::Triangulation::TriaFaces<1>, std::default_delete<dealii::internal::Triangulation::TriaFaces<1> > > >::invoke (ar=..., t=std::unique_ptr<dealii::internal::Triangulation::TriaFaces<1>> containing 0x0, file_version=0)
    at /usr/include/boost/serialization/split_free.hpp:45
#11 0x000000000066d6da in boost::serialization::serialize_adl<boost::archive::text_oarchive, std::unique_ptr<dealii::internal::Triangulation::TriaFaces<1>, std::default_delete<dealii::internal::Triangulation::TriaFaces<1> > > > (ar=..., t=std::unique_ptr<dealii::internal::Triangulation::TriaFaces<1>> containing 0x0, file_version=0)
    at /usr/include/boost/serialization/serialization.hpp:126
#12 0x000000000066d5fd in boost::archive::detail::oserializer<boost::archive::text_oarchive, std::unique_ptr<dealii::internal::Triangulation::TriaFaces<1>, std::default_delete<dealii::internal::Triangulation::TriaFaces<1> > > >::save_object_data (
    this=0x996318 <boost::serialization::singleton<boost::archive::detail::oserializer<boost::archive::text_oarchive, std::unique_ptr<dealii::internal::Triangulation::TriaFaces<1>, std::default_delete<dealii::internal::Triangulation::TriaFaces<1> > > > >::get_instance()::t>, ar=..., x=0x7fffffffd150) at /usr/include/boost/archive/detail/oserializer.hpp:150
#13 0x00007fffcc86235b in ?? () from /usr/lib64/libboost_serialization.so.1.65.0
#14 0x0000000000661d0a in boost::archive::detail::interface_oarchive<boost::archive::text_oarchive>::operator<< <std::unique_ptr<dealii::internal::Triangulation::TriaFaces<1>, std::default_delete<dealii::internal::Triangulation::TriaFaces<1> > > > (this=0x7fffffffda70, t=std::unique_ptr<dealii::internal::Triangulation::TriaFaces<1>> containing 0x0)
    at /usr/include/boost/archive/detail/interface_oarchive.hpp:70
#15 0x00000000006614e6 in dealii::Triangulation<1, 1>::save<boost::archive::text_oarchive> (this=0x7fffffffdf40, ar=...) at /srv/testsuite/dealii/include/deal.II/grid/tria.h:3689
#16 0x000000000066139a in boost::serialization::serialize_adl<boost::archive::text_oarchive, dealii::Triangulation<1, 1> > (ar=..., t=..., file_version=0)
    at /usr/include/boost/serialization/serialization.hpp:126
#17 0x00000000006612bd in boost::archive::detail::oserializer<boost::archive::text_oarchive, dealii::Triangulation<1, 1> >::save_object_data (
    this=0x995cd0 <boost::serialization::singleton<boost::archive::detail::oserializer<boost::archive::text_oarchive, dealii::Triangulation<1, 1> > >::get_instance()::t>, ar=..., 
    x=0x7fffffffd150) at /usr/include/boost/archive/detail/oserializer.hpp:150
#18 0x00007fffcc86235b in ?? () from /usr/lib64/libboost_serialization.so.1.65.0
#19 0x000000000065c43a in boost::archive::detail::interface_oarchive<boost::archive::text_oarchive>::operator<< <dealii::Triangulation<1, 1> > (this=0x7fffffffda70, t=...)
    at /usr/include/boost/archive/detail/interface_oarchive.hpp:70
#20 0x000000000065ad2c in verify<dealii::Triangulation<1, 1> > (t1=..., t2=...) at /srv/testsuite/dealii/tests/serialization/serialization.h:52
#21 0x000000000064dfb6 in test<1, 1> () at /srv/testsuite/dealii/tests/serialization/triangulation_01.cc:160
#22 0x000000000064d4f4 in main () at /srv/testsuite/dealii/tests/serialization/triangulation_01.cc:170
```

**Closed** 2017-09-20 15:31 UTC
Labels: Bug
