### ISSUE TITLE
Bug in DoFRenumbering::hierarchical()

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#5686] opened 2017-12-30 22:11 UTC
This is something @tjhei caused, and because it's his birthday today, let me call him out on it with all the friendship in my warm heart! ;-)

Fundamentally, `DoFRenumbering::hierarchical()` should renumber DoFs in a way that reflects the tree structure of the mesh, using the z-order defined on the cell. As such, it should produce an ordering that is independent of the previous DoF numbering. Alas, that is not the case. Here is a small testcase with 4 cells in 2d, to be run on 4 processors:
```
// ---------------------------------------------------------------------
//
// Copyright (C) 2017 by the deal.II authors
//
// This file is part of the deal.II library.
//
// The deal.II library is free software; you can use it, redistribute
// it, and/or modify it under the terms of the GNU Lesser General
// Public License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
// The full text of the license can be found in the file LICENSE at
// the top level of the deal.II distribution.
//
// ---------------------------------------------------------------------



// Test that DofRenumbering::hierarchical() gives the same DoF numbers
// independent their previous ordering. This was broken before where
// the hierarchical numbering on each processor re-used the indices
// the processor previously owned. This worked just fine with the
// original ordering used by default by DoFHandler, but not if there
// was another reordering step in between


#include "../tests.h"
#include <deal.II/base/quadrature_lib.h>
#include <deal.II/base/tensor.h>
#include <deal.II/grid/tria.h>
#include <deal.II/distributed/tria.h>
#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_out.h>
#include <deal.II/dofs/dof_handler.h>
#include <deal.II/dofs/dof_handler.h>
#include <deal.II/dofs/dof_tools.h>
#include <deal.II/grid/tria_accessor.h>
#include <deal.II/grid/tria_iterator.h>
#include <deal.II/dofs/dof_accessor.h>
#include <deal.II/lac/trilinos_vector.h>
#include <deal.II/dofs/dof_renumbering.h>
#include <deal.II/fe/fe_q.h>
#include <deal.II/fe/fe_values.h>

#include <boost/concept_check.hpp>


void test()
{
  unsigned int myid = Utilities::MPI::this_mpi_process (MPI_COMM_WORLD);

  parallel::distributed::Triangulation<2> tr (MPI_COMM_WORLD);
  GridGenerator::subdivided_hyper_rectangle (tr, std::vector<unsigned int>{{2,2}}, Point<2>(), Point<2>(2,2));

  const FE_Q<2> fe (1);

  for (unsigned int test=0; test<2; ++test)
    {
      DoFHandler<2> dof_handler (tr);
      dof_handler.distribute_dofs (fe);

      // in the second test run, revert the global order of DoF
      // indices. the point is to make sure that processors do not
      // have strictly increasing, contiguous groups of DoF indices.
      if (test==1)
        {
          IndexSet locally_owned_dofs = dof_handler.locally_owned_dofs ();
          std::vector<types::global_dof_index> new_numbers (locally_owned_dofs.n_elements());
          for (auto i : locally_owned_dofs)
            new_numbers[locally_owned_dofs.index_within_set(i)]
              = dof_handler.n_dofs() - i - 1;
          dof_handler.renumber_dofs (new_numbers);  
        }
      
      // next, let the hierarchical numbering work on it. the
      // important aspect is that the result of hierarchical
      // renumbering should not depend on the *previous* numbering. so
      // we should be getting the same output as in the first run
      DoFRenumbering::hierarchical (dof_handler);

      // output DoF indices
      deallog << (test == 0 ? "Without " : "With ") << "prior reordering:" << std::endl;
      const unsigned int dofs_per_cell = fe.dofs_per_cell;
      std::vector<types::global_dof_index> local_dof_indices (dofs_per_cell);
      DoFHandler<2>::active_cell_iterator
        cell = dof_handler.begin_active(),
        endc = dof_handler.end();
      for (; cell != endc; ++cell)
        if (cell->subdomain_id() == tr.locally_owned_subdomain())
          {
            deallog << "Cell=" << cell << std::endl;
            cell->get_dof_indices (local_dof_indices);
            for (auto i : local_dof_indices)
              deallog << i << ' ';
            deallog << std::endl;
          }
    }
}


int main (int argc, char *argv[])
{
  Utilities::MPI::MPI_InitFinalize mpi_initialization (argc, argv, 1);
  MPILogInitAll log;

  test();
}
```

This yields the following output that clearly shows the problem (with/without previous reordering should make no difference):
```
DEAL:0::Without prior reordering:
DEAL:0::Cell=0.0
DEAL:0::0 1 2 3 
DEAL:0::With prior reordering:
DEAL:0::Cell=0.0
DEAL:0::5 6 7 8 

DEAL:1::Without prior reordering:
DEAL:1::Cell=0.1
DEAL:1::1 4 3 5 
DEAL:1::With prior reordering:
DEAL:1::Cell=0.1
DEAL:1::6 3 8 4 


DEAL:2::Without prior reordering:
DEAL:2::Cell=0.2
DEAL:2::2 3 6 7 
DEAL:2::With prior reordering:
DEAL:2::Cell=0.2
DEAL:2::7 8 1 2 


DEAL:3::Without prior reordering:
DEAL:3::Cell=0.3
DEAL:3::3 5 7 8 
DEAL:3::With prior reordering:
DEAL:3::Cell=0.3
DEAL:3::8 4 2 0 
```

The problem is here, in `dof_renumbering.cc`:
```
    template <int dim, class CellIteratorType>
    types::global_dof_index
    compute_hierarchical_recursive (const types::global_dof_index         next_free_dof_index,
                                    std::vector<types::global_dof_index> &new_indices,
                                    const CellIteratorType               &cell,
                                    const IndexSet                       &locally_owned_dof_indices)
    {
      types::global_dof_index current_dof_index = next_free_dof_index;

      if (cell->has_children())
        {
           ...recurse...
        }
      else
        {
          if (cell->is_locally_owned())
            {
              // first get the existing DoF indices
              const unsigned int dofs_per_cell = cell->get_fe().dofs_per_cell;
              std::vector<types::global_dof_index> local_dof_indices (dofs_per_cell);
              cell->get_dof_indices (local_dof_indices);

              // then loop over the existing DoF indices on this cell
              // and see whether it has already been re-numbered (it
              // may have been on a face or vertex to a neighboring
              // cell that we have encountered before). if not,
              // give it a new number and store that number in the
              // output array (new_indices)
              //
              // if this is a parallel triangulation and a DoF index is
              // not locally owned, then don't touch it. since
              // we don't actually *change* DoF indices (just record new
              // numbers in an array), we don't need to worry about
              // the decision whether a DoF is locally owned or not changing
              // as we progress in renumbering DoFs -- all adjacent cells
              // will always agree that a DoF is locally owned or not
              for (unsigned int i = 0; i < dofs_per_cell; ++i)
                if (locally_owned_dof_indices.is_element (local_dof_indices[i]))
                  {
                    // this is a locally owned DoF, assign new number if not assigned a number yet
                    const unsigned int idx = locally_owned_dof_indices.index_within_set (local_dof_indices[i]);
                    if (new_indices[idx] == numbers::invalid_dof_index)
                      {
                        new_indices[idx] = locally_owned_dof_indices.nth_index_in_set (current_dof_index);   // **************
                        ++current_dof_index;
                      }
                  }
            }
        }

      return current_dof_index;
    }
```
In the marked cell, we re-use the DoF indices previously owned by this process, rather than starting from scratch with a clean slate.

I know how to fix this, but won't get to it today. 

Part of looking into #5622.

**Comment by tjhei** [comment] 2017-12-31 10:00
> Fundamentally, DoFRenumbering::hierarchical() should renumber DoFs in a way that reflects the tree structure of the mesh, using the z-order defined on the cell. As such, it should produce an ordering that is independent of the previous DoF numbering

Maybe this is just an issue of documentation? It depends on the previous ordering like most reordering functions. Reading the documentation again, it actually says "renumber (...) cell by cell". ;-)

By the way, the main goal of the function is that a checkpoint/resume only works if the same mesh gives the same DoF numbering. This is not given if multiple refine/coarsen steps before the checkpoint (this influences the ordering of the cells inside the triangulation and thus the default numbering).

That said, we typically use it to do ``hierarchical()`` first and then apply ``component_wise`` or similar reorderings next. So I won't consider it a bug, just something we should document.

One could also argue that we should always run ``hierarchical()`` by default after distributing DoFs because not using it might be very confusing.

**Comment by bangerth** [comment] 2017-12-31 22:36
>     Fundamentally, DoFRenumbering::hierarchical() should renumber DoFs in a
>     way that reflects the tree structure of the mesh, using the z-order
>     defined on the cell. As such, it should produce an ordering that is
>     independent of the previous DoF numbering
> 
> Maybe this is just an issue of documentation? It depends on the previous 
> ordering like most reordering functions. Reading the documentation again, it 
> actually says "renumber (...) cell by cell". ;-)
> 
> By the way, the main goal of the function is that a checkpoint/resume only 
> works if the same mesh gives the same DoF numbering. This is not given if 
> multiple refine/coarsen steps before the checkpoint (this influences the 
> ordering of the cells inside the triangulation and thus the default numbering).

Yes. The reason why I want to change the function in such a way that it 
doesn't depend on the previous DoF indices is because it can then be used for 
p::s::Triangulation -- there, you currently get different indices on the same 
cell, depending on how many processors you use. I think that after I fix this 
function, you will actually get a DoF numbering that is independent of the 
number of processors that divvy up the mesh. This is the point of #5622.


> That said, we typically use it to do |hierarchical()| first and then apply 
> |component_wise| or similar reorderings next. So I won't consider it a bug, 
> just something we should document.

But do you object to me "fixing" the function? You're right that it won't 
actually affect anyone I can think of.


> One could also argue that we should always run |hierarchical()| by default 
> after distributing DoFs because not using it might be very confusing.

Why? The partitioning of DoFs is exactly the same, it's just that the DoFs on 
each processor's locally owned cells are numbered differently.

**Comment by tjhei** [comment] 2018-01-01 09:25
> I think that after I fix this
> function, you will actually get a DoF numbering that is independent of the
> number of processors that divvy up the mesh.

That would mean the locally owned set will no longer be contiguous in every situation, right? I don't think that is useful for a shared Triangulation because you basically throw the partitioning (for example done using METIS) away and distribute DoFs by the inferior z-order after the fact. So this will degrade performance, right?

Another problem is that we currently do not allow  ``DoFRenumbering::renumber_dofs()``  to reassign DoF ownership (just permutation of DoFs on each processor) for a distributed Tria if I remember correctly.

> But do you object to me "fixing" the function? You're right that it won't
> actually affect anyone I can think of.

I am still not sure what the "correct" behavior for a shared triangulation should be and I think the current implementation is correct for a distributed one. To me it doesn't make sense to use "hierarchical" unless your partitioning is also done hierarchical (in z-order / p4est ordering). I think part of the problem is a misunderstanding of the purpose of this function. The discussion here and the documentation says "this makes dof numbers independent of the number of processors", but I wrote this method and see its role as "no matter how you reached a given mesh by coarsening/refining, the dof numbering will be identical".

> Why? The partitioning of DoFs is exactly the same, it's just that the DoFs on
> each processor's locally owned cells are numbered differently.

Because it is confusing that the DoF numbering depends on the refine/coarsen history and not only on the current state of the mesh.

So:
1. I don't think one should use hierarchical() for a shared triangulation
2. I don't think there is value in having "identical numbering independent of the number of processors" unless for debugging.
3. I think it is correct for p::d::Tria and would be difficult to get "right" (you basically need to reimplement ``DoFHandler::distribute_dofs()``)

Complicated issue for sure!

**Comment by bangerth** [comment] 2018-01-01 19:57
> That would mean the locally owned set will no longer be contiguous in every 
> situation, right?

That's not correct, at least for p::d::Triangulation. That's because the set 
of cells that are locally owned are consecutive in hierarchical order, and so 
we encounter them in a consecutive range when numbering DoFs -- consequently, 
the range of locally owned DoFs are contiguous as well.

You are correct for p::s::Triangulation, however. It is, however, unclear to 
me why you would want to call this function for such a triangulation unless 
you specifically want a DoF enumeration that is independent of the number of 
processors.


> I don't think that is useful for a shared Triangulation 
> because you basically throw the partitioning (for example done using METIS) 
> away and distribute DoFs by the inferior z-order after the fact. So this will 
> degrade performance, right?

If you mean that this will degrade performance because the locally owned DoF 
indices range is no longer contiguous, then you're right. But as stated above, 
the function is not particularly useful for a shared triangulation anyway. If 
you call it, you presumably do so for a reason. As it stands right now, the 
function is not useful for shared triangulations.


> Another problem is that we currently do not allow 
> |DoFRenumbering::renumber_dofs()| to reassign DoF ownership (just permutation 
> of DoFs on each processor) for a distributed Tria if I remember correctly.

That's not true. Otherwise, DoFRenumbering::component_wise() would not work -- 
it produces a non-contiguous set of DoF indices, which can't result from just 
a permutation.


>     But do you object to me "fixing" the function? You're right that it won't
>     actually affect anyone I can think of.
> 
> I am still not sure what the "correct" behavior for a shared triangulation 
> should be and I think the current implementation is correct for a distributed 
> one.

That's correct if you call it right after DoFHandler::distribute_dofs(). And I 
have no intention of changing this. I think it's arguable what the correct 
behavior should be if it's called after another renumbering function -- and 
that's the only case I want to change.



>     Why? The partitioning of DoFs is exactly the same, it's just that the DoFs on
>     each processor's locally owned cells are numbered differently.
> 
> Because it is confusing that the DoF numbering depends on the refine/coarsen 
> history and not only on the current state of the mesh.

Maybe. But so is the order in which we traverse cells. It makes sense (for 
example for cache locality) to enumerate DoFs in the order in which we 
traverse cells -- which is what we currently do.


>  1. I don't think one should use hierarchical() for a shared triangulation
>  2. I don't think there is value in having "identical numbering independent of
>     the number of processors" unless for debugging.
>  3. I think it is correct for p::d::Tria and would be difficult to get "right"
>     (you basically need to reimplement |DoFHandler::distribute_dofs()|)

I don't disagree with any of these points. I also don't intend to change the 
behavior for the case where the function is currently used (namely, for 
p::d::T and right after distribute_dofs()). I just want to make the function 
work for a case someone has apparently found useful (in #5622) and that go 
beyond what the function is currently used for.

**Comment by tjhei** [comment] 2018-01-03 09:57
> You are correct for p::s::Triangulation, however. It is, however, unclear to
> me why you would want to call this function for such a triangulation unless
> you specifically want a DoF enumeration that is independent of the number of
> processors.
> As it stands right now, the function is not useful for shared triangulations.

Agreed. The function should work (and is useful) for shared::Tria when using the ``zorder`` partitioning only. This needs to be tested/fixed/asserted of course. 

> I also don't intend to change the
> behavior for the case where the function is currently used (namely, for
> p::d::T and right after distribute_dofs()). 

Alright. I would have just documented the current logic. I think the current implementation is more in line with all other renumber functions in that they preserve existing renumbering instead of what you propose (ignore all existing renumbering). I don't feel strongly about it.

> I just want to make the function
> work for a case someone has apparently found useful (in #5622) and that go
> beyond what the function is currently used for.

I don't see a reason for calling some other renumbering functions before ``hierarchical`` and then expecting the same answer as if you had not done so. Can you explain how the issue you link to related to this fact (the code example calls hierarchical first)?

**Comment by bangerth** [comment] 2018-01-11 02:09
As for point 1 in the previous comment (testing in case of Z order partitioning): This is done in #5718 now.

#5622 also has a comment now about in the case of general partitioning, the Z order renumbering of DoFs would yield a non-contiguous range. @tjhei may have mentioned this explicitly or implicitly above, but I did not understand it. In any case, while possible with Trilinos, non-contiguous DoF index ranges are unpleasant and undesirable. I can think of a way to implement this, but I don't think I want to.

**Closed** 2018-01-16 21:15 UTC
Labels: Bug, DoFs
