### ISSUE TITLE
Instantiations missing in static build

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3599] opened 2016-11-17 03:04 UTC
Based on this report here (https://groups.google.com/forum/#!topic/dealii/f_iJJGYhpjk), we are missing some instantiations. Concretely, at least these are missing:
```
/home/ycc/tool_download/STATIC_deal/dealii-8.4.1/source/fe/fe_system.cc:1445: undefined reference to `dealii::internal::FEValues::FiniteElementRelatedData<1, 3>::initialize(unsigned int, dealii::FiniteElement<1, 3> const&, dealii::UpdateFlags)'

/home/ycc/test/deal/lib/libdeal_II.g.a(fe_system.cc.o): In function `dealii::FESystem<1, 3>::get_subface_data(dealii::UpdateFlags, dealii::Mapping<1, 3> const&, dealii::Quadrature<0> const&, dealii::internal::FEValues::FiniteElementRelatedData<1, 3>&) const':

/home/ycc/tool_download/STATIC_deal/dealii-8.4.1/source/fe/fe_system.cc:1503: undefined reference to `dealii::internal::FEValues::FiniteElementRelatedData<1, 3>::initialize(unsigned int, dealii::FiniteElement<1, 3> const&, dealii::UpdateFlags)'

/home/ycc/tool_download/STATIC_deal/dealii-8.4.1/source/dofs/dof_tools_sparsity.cc:447: undefined reference to `dealii::DoFHandler<2, 2>::n_boundary_dofs(std::map<unsigned char, dealii::Function<2, double> const*, std::less<unsigned char>, std::allocator<std::pair<unsigned char const, dealii::Function<2, double> const*> > > const&) const'

/home/ycc/tool_download/STATIC_deal/dealii-8.4.1/source/dofs/dof_tools_sparsity.cc:447: undefined reference to `dealii::DoFHandler<2, 2>::n_boundary_dofs(std::map<unsigned char, dealii::Function<2, double> const*, std::less<unsigned char>, std::allocator<std::pair<unsigned char const, dealii::Function<2, double> const*> > > const&) const'
```

**Comment by bangerth** [comment] 2016-11-21 03:01
Here are more from a more recent email in the same thread:
```
unsigned int DoFHandler<1, 1>::get_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int) const
unsigned int DoFHandler<1, 2>::get_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int) const
unsigned int DoFHandler<1, 3>::get_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int) const
unsigned int DoFHandler<2, 2>::get_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int) const
unsigned int DoFHandler<2, 2>::get_dof_index<2>(unsigned int, unsigned int, unsigned int, unsigned int) const
unsigned int DoFHandler<2, 3>::get_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int) const
unsigned int DoFHandler<2, 3>::get_dof_index<2>(unsigned int, unsigned int, unsigned int, unsigned int) const
unsigned int DoFHandler<3, 3>::get_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int) const
unsigned int DoFHandler<3, 3>::get_dof_index<2>(unsigned int, unsigned int, unsigned int, unsigned int) const
unsigned int DoFHandler<3, 3>::get_dof_index<3>(unsigned int, unsigned int, unsigned int, unsigned int) const
void DoFHandler<1, 1>::set_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const
void DoFHandler<1, 2>::set_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const
void DoFHandler<2, 2>::set_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const
void DoFHandler<2, 2>::set_dof_index<2>(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const
void DoFHandler<2, 3>::set_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const
void DoFHandler<2, 3>::set_dof_index<2>(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const
void DoFHandler<3, 3>::set_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const
void DoFHandler<3, 3>::set_dof_index<2>(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const
void DoFHandler<3, 3>::set_dof_index<3>(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const
void FEFaceValues<1, 1>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<1, 1>, false> > const&, unsigned int)
void FEFaceValues<1, 1>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<1, 1>, false> > const&, unsigned int)
void FEFaceValues<1, 2>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<1, 2>, false> > const&, unsigned int)
void FEFaceValues<1, 2>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<1, 2>, false> > const&, unsigned int)
void FEFaceValues<1, 3>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<1, 3>, false> > const&, unsigned int)
void FEFaceValues<1, 3>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<1, 3>, false> > const&, unsigned int)
void FEFaceValues<2, 2>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<2, 2>, false> > const&, unsigned int)
void FEFaceValues<2, 2>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<2, 2>, false> > const&, unsigned int)
void FEFaceValues<2, 3>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<2, 3>, false> > const&, unsigned int)
void FEFaceValues<2, 3>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<2, 3>, false> > const&, unsigned int)
void FEFaceValues<3, 3>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<3, 3>, false> > const&, unsigned int)
void FEFaceValues<3, 3>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<3, 3>, false> > const&, unsigned int)
void FESubfaceValues<1, 1>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<1, 1>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<1, 1>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<1, 1>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<1, 2>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<1, 2>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<1, 2>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<1, 2>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<1, 3>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<1, 3>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<1, 3>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<1, 3>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<2, 2>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<2, 2>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<2, 2>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<2, 2>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<2, 3>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<2, 3>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<2, 3>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<2, 3>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<3, 3>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<3, 3>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<3, 3>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<3, 3>, false> > const&, unsigned int, unsigned int)
void FEValues<1, 1>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<1, 1>, false> > const&)
void FEValues<1, 1>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<1, 1>, false> > const&)
void FEValues<1, 2>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<1, 2>, false> > const&)
void FEValues<1, 2>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<1, 2>, false> > const&)
void FEValues<1, 3>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<1, 3>, false> > const&)
void FEValues<1, 3>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<1, 3>, false> > const&)
void FEValues<2, 2>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<2, 2>, false> > const&)
void FEValues<2, 2>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<2, 2>, false> > const&)
void FEValues<2, 3>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<2, 3>, false> > const&)
void FEValues<2, 3>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<2, 3>, false> > const&)
void FEValues<3, 3>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<3, 3>, false> > const&)
void FEValues<3, 3>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<3, 3>, false> > const&)
internal::FEValues::FiniteElementRelatedData<1, 1>::initialize(unsigned int, FiniteElement<1, 1> const&, UpdateFlags)
internal::FEValues::FiniteElementRelatedData<1, 3>::initialize(unsigned int, FiniteElement<1, 3> const&, UpdateFlags)
internal::FEValues::FiniteElementRelatedData<2, 2>::initialize(unsigned int, FiniteElement<2, 2> const&, UpdateFlags)
internal::FEValues::FiniteElementRelatedData<3, 3>::initialize(unsigned int, FiniteElement<3, 3> const&, UpdateFlags)
unsigned int DoFHandler<1, 1>::get_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int) const
unsigned int DoFHandler<1, 2>::get_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int) const
unsigned int DoFHandler<1, 3>::get_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int) const
unsigned int DoFHandler<2, 2>::get_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int) const
unsigned int DoFHandler<2, 2>::get_dof_index<2>(unsigned int, unsigned int, unsigned int, unsigned int) const
unsigned int DoFHandler<2, 3>::get_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int) const
unsigned int DoFHandler<2, 3>::get_dof_index<2>(unsigned int, unsigned int, unsigned int, unsigned int) const
unsigned int DoFHandler<3, 3>::get_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int) const
unsigned int DoFHandler<3, 3>::get_dof_index<2>(unsigned int, unsigned int, unsigned int, unsigned int) const
unsigned int DoFHandler<3, 3>::get_dof_index<3>(unsigned int, unsigned int, unsigned int, unsigned int) const
void DoFHandler<1, 1>::set_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const
void DoFHandler<1, 2>::set_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const
void DoFHandler<2, 2>::set_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const
void DoFHandler<2, 2>::set_dof_index<2>(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const
void DoFHandler<2, 3>::set_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const
void DoFHandler<2, 3>::set_dof_index<2>(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const
void DoFHandler<3, 3>::set_dof_index<1>(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const
void DoFHandler<3, 3>::set_dof_index<2>(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const
void DoFHandler<3, 3>::set_dof_index<3>(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const
void FEFaceValues<1, 1>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<1, 1>, false> > const&, unsigned int)
void FEFaceValues<1, 1>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<1, 1>, false> > const&, unsigned int)
void FEFaceValues<1, 2>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<1, 2>, false> > const&, unsigned int)
void FEFaceValues<1, 2>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<1, 2>, false> > const&, unsigned int)
void FEFaceValues<1, 3>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<1, 3>, false> > const&, unsigned int)
void FEFaceValues<1, 3>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<1, 3>, false> > const&, unsigned int)
void FEFaceValues<2, 2>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<2, 2>, false> > const&, unsigned int)
void FEFaceValues<2, 2>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<2, 2>, false> > const&, unsigned int)
void FEFaceValues<2, 3>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<2, 3>, false> > const&, unsigned int)
void FEFaceValues<2, 3>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<2, 3>, false> > const&, unsigned int)
void FEFaceValues<3, 3>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<3, 3>, false> > const&, unsigned int)
void FEFaceValues<3, 3>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<3, 3>, false> > const&, unsigned int)
void FESubfaceValues<1, 1>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<1, 1>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<1, 1>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<1, 1>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<1, 2>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<1, 2>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<1, 2>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<1, 2>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<1, 3>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<1, 3>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<1, 3>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<1, 3>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<2, 2>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<2, 2>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<2, 2>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<2, 2>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<2, 3>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<2, 3>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<2, 3>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<2, 3>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<3, 3>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<3, 3>, false> > const&, unsigned int, unsigned int)
void FESubfaceValues<3, 3>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<3, 3>, false> > const&, unsigned int, unsigned int)
void FEValues<1, 1>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<1, 1>, false> > const&)
void FEValues<1, 1>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<1, 1>, false> > const&)
void FEValues<1, 2>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<1, 2>, false> > const&)
void FEValues<1, 2>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<1, 2>, false> > const&)
void FEValues<1, 3>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<1, 3>, false> > const&)
void FEValues<1, 3>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<1, 3>, false> > const&)
void FEValues<2, 2>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<2, 2>, false> > const&)
void FEValues<2, 2>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<2, 2>, false> > const&)
void FEValues<2, 3>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<2, 3>, false> > const&)
void FEValues<2, 3>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<2, 3>, false> > const&)
void FEValues<3, 3>::reinit<DoFHandler, false>(TriaIterator<DoFCellAccessor<DoFHandler<3, 3>, false> > const&)
void FEValues<3, 3>::reinit<hp::DoFHandler, false>(TriaIterator<DoFCellAccessor<hp::DoFHandler<3, 3>, false> > const&)

```

**Comment by drwells** [comment] 2017-02-14 18:28
The last time I looked at this I was not able to reproduce the missing symbols. Has anyone been able to do this? This failure seems very dependent on the particular toolchain.

**Comment by bangerth** [comment] 2017-02-14 18:51
Yes, we haven't seen any other reports either indeed. It's a relatively small number of functions. Maybe I have a bit of time looking at how exactly they are defined (must not have `inline` if in the `.cc` file) and if indeed they are *explicitly* instantiated in the `.inst.in` file, not just implicitly.

**Comment by kronbichler** [comment] 2017-03-03 19:14
I ran my usual configuration on static libs, including the whole test suite (which only consumes 1.2 TB of disk storage) and there appear to be only very few problems:
https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=5446
(8 more tests fail on this configuration as compared to the shared libs, 6 of which are due to mpi/renumber_cuthill_mckee).

Since the original problem appeared to be without threads, I will re-run the test suite with that configuration as well...

**Comment by drwells** [comment] 2017-03-03 19:43
That is a frighteningly large amount of disk space.

We need to mark the non-template functions in `mpi.templates.h` as `inline`: do you have a patch for this? If not I can throw something together.

**Comment by kronbichler** [comment] 2017-03-03 20:07
Every debug test is around 500M, release tests around 50M (depending on how much of deal.II gets linked into, of course)... ;-) I'm happy that I didn't try this on my SSD ;-)

**Comment by kronbichler** [comment] 2017-03-04 21:00
I ran without threads which was part of the original problem as far as I can see. I cannot reproduce and the whole test suite runs except for a few unrelated problems:
https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=5456

Without further input I would vote for closing this issue.

**Closed** 2017-03-05 15:59 UTC
Labels: Bug
