### ISSUE TITLE
guard slepc configuration

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#2167] opened 2016-02-11 14:50 UTC
I was able to successfully configure with petsc and slepc while slepc was linking to a different petsc installation. I think we should figure out a way to stop this from happening.

**Comment by tamiko** [comment] 2016-02-28 17:35
This is not an easy task. :-/

I don't see any obvious way to achieve this and still support all possible installation scenarios.
I'll have a look at whether we can make a best-effort guess with the configuration files we already parse.

**Comment by bangerth** [comment] 2016-02-28 18:59
Shouldn't SLEPc store somewhere what PETSc it uses? Or is this never made explicit inside the SLEPc installation?

**Comment by oneliefleft** [comment] 2016-02-28 20:46
What you mean by, "what PETSc it uses"? If you mean version, no it is not
stored, but SLEPc only compiles with the same major and minor versions as
PETSc - if they do not match, SLWPc throws an exception at configure time.

Right?




2016-02-28 19:59 GMT+01:00 Wolfgang Bangerth <notifications@github.com>:

**Comment by bangerth** [comment] 2016-02-28 21:03
I expected that in some SLEPc configuration file it records against which PETSc installation it was compiled. That may not be true. But it must have accessed *some* PETSc installation's header files and libraries during SLEPc compilation and installation.

**Comment by oneliefleft** [comment] 2016-02-29 00:53
Yes, I see. As far as I know SLEPc does not record that information. It
accesses the same info (from petscconf.h) as deal.ii does at configure time
and then stores additional information (in slepcconf.h). Sorry to be a pain
- what was the original problem that this thread concerns? What do we want
to achieve?

2016-02-28 22:03 GMT+01:00 Wolfgang Bangerth <notifications@github.com>:

**Comment by davydden** [comment] 2016-02-29 07:41
i agree with @tamiko , unfortunately it is not straight forward to do. The problem is that SLEPc, AFAIK, does not record in any config file what PETSc it built against. Until something changes in this behaviour, that issue is a `wontfix`.

**Comment by davydden** [comment] 2016-02-29 07:45
i wrote to the mailing list to ask for this feature and gave a link to this discussion.

**Comment by bangerth** [comment] 2016-02-29 07:56
Given that it's not trivial and that the issue is obscure and unlikely to happen to a lot of our users, my vote would be to not sink any more resources into it. What do you think,  @tjheister?

**Comment by tjhei** [comment] 2016-02-29 14:15
I would assume that we could check if our libpetsc is the same one slepc pulls in. But I agree, we have plenty of other stuff to do.

**Comment by davydden** [comment] 2016-02-29 17:59
from Jose Roman on PETSc mailing list

> I have added this:
> https://bitbucket.org/slepc/slepc/branch/jose/configure
>
> However, I am not totally convinced of this change, because PETSC_DIR is then defined both in  petscconf.h and slepcconf.h, so behaviour could change depending on whether user code includes one or the other in the first place.
>
> I will test this further before merging into master.

**Comment by bangerth** [comment] 2016-02-29 21:03
Well, that's asking for trouble. They're stepping on the PETSc namespace this way. They should name the variable `SLEPC_PETSC_DIR` and then let users figure out whether that equals `PETSC_DIR`.

**Comment by bangerth** [comment] 2016-02-29 21:04
Given @tjhei 's comment, let's close this and not try too hard to come up with a solution at this point. If SLEPc at one point in the future has a mechanism to address this, we can always reopen.

**Closed by bangerth** 2016-02-29 21:04 UTC
