### ISSUE TITLE
Double check whether Trilinos's TrilinosConfig.cmake is really correct

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#994] opened 2015-06-04 19:56 UTC
So I found this bug with Trilinos 12.0.1 but it probably exists in older version too. Basically the config file of Trilinos says that a package has been compiled but in reality it wasn't. Trilinos compiles without problem but cmake can't create a Makefile. The problem is that the cause of the bug is not obvious because cmake says that Trilinos was successfully set up.

Here is the error that I got:

CMake Error at /scratch/user/turcksin/trilinos/bin/lib/cmake/Trilinos/TrilinosConfig.cmake:165 (include):
  include could not find load file:

```
/scratch/user/turcksin/trilinos/bin/lib/cmake/Trilinos/../ShyLU/ShyLUConfig.cmake
```

Call Stack (most recent call first):
  cmake/macros/macro_find_package.cmake:27 (_FIND_PACKAGE)
  cmake/modules/FindTRILINOS.cmake:39 (FIND_PACKAGE)
  cmake/macros/macro_find_package.cmake:27 (_FIND_PACKAGE)
  cmake/configure/configure_2_trilinos.cmake:22 (FIND_PACKAGE)
  build/CMakeFiles/CMakeTmp/macro_configure_feature.tmp:1 (FEATURE_TRILINOS_FIND_EXTERNAL)
  cmake/macros/macro_configure_feature.cmake:76 (INCLUDE)
  cmake/macros/macro_configure_feature.cmake:240 (RUN_COMMAND)
  cmake/configure/configure_2_trilinos.cmake:198 (CONFIGURE_FEATURE)
  cmake/macros/macro_verbose_include.cmake:19 (INCLUDE)
  CMakeLists.txt:119 (VERBOSE_INCLUDE)

However, a little after when we check that Trilinos is installed correctly, we check only for a few packages:

-- Found TRILINOS
-- Check whether the found trilinos package contains all required modules:
-- Found Amesos
-- Found Epetra
-- Found Ifpack
-- Found AztecOO
-- Found Sacado
-- Found Teuchos
-- Found ML
-- Found MueLu
-- DEAL_II_WITH_TRILINOS successfully set up with external dependencies.

This what I got at the end: 

 deal.II configuration:
        CMAKE_BUILD_TYPE:       Release
        BUILD_SHARED_LIBS:      ON
        CMAKE_INSTALL_PREFIX:   /scratch/user/turcksin/dealii-master/install_trilinos
        CMAKE_SOURCE_DIR:       /scratch/user/turcksin/dealii-master
                                (version 8.3.pre)
        CMAKE_BINARY_DIR:       /scratch/user/turcksin/dealii-master/build
        CMAKE_CXX_COMPILER:     GNU 4.9.2 on platform Linux x86_64
                                /software/easybuild/software/impi/5.0.3.048-iccifort-2015.2.164-GCC-4.9.2/bin64/mpicxx

  Configured Features (DEAL_II_ALLOW_BUNDLED = ON, DEAL_II_ALLOW_AUTODETECTION = ON):
      ( DEAL_II_WITH_64BIT_INDICES = OFF )
      ( DEAL_II_WITH_ARPACK = OFF )
        DEAL_II_WITH_BOOST set up with bundled packages
      ( DEAL_II_WITH_BZIP2 = OFF )
        DEAL_II_WITH_CXX11 = ON
      ( DEAL_II_WITH_HDF5 = OFF )
        DEAL_II_WITH_LAPACK set up with external dependencies
      ( DEAL_II_WITH_METIS = OFF )
        DEAL_II_WITH_MPI set up with external dependencies
        DEAL_II_WITH_MUPARSER set up with bundled packages
      ( DEAL_II_WITH_NETCDF = OFF )
      ( DEAL_II_WITH_OPENCASCADE = OFF )
        DEAL_II_WITH_P4EST set up with external dependencies
      ( DEAL_II_WITH_PETSC = OFF )
      ( DEAL_II_WITH_SLEPC = OFF )
        DEAL_II_WITH_THREADS set up with bundled packages
        DEAL_II_WITH_TRILINOS set up with external dependencies
      ( DEAL_II_WITH_UMFPACK = OFF )
      ( DEAL_II_WITH_ZLIB = OFF )

  Component configuration:
      ( DEAL_II_COMPONENT_DOCUMENTATION = OFF )
        DEAL_II_COMPONENT_EXAMPLES
        DEAL_II_COMPONENT_MESH_CONVERTER
      ( DEAL_II_COMPONENT_PACKAGE = OFF )
      ( DEAL_II_COMPONENT_PARAMETER_GUI = OFF )

  Detailed information (compiler flags, feature configuration) can be found in detailed.log
  Run  $ make info  to print a help message with a list of top level targets

-- Configuring incomplete, errors occurred!
See also "/scratch/user/turcksin/dealii-master/build/CMakeFiles/CMakeOutput.log".
See also "/scratch/user/turcksin/dealii-master/build/CMakeFiles/CMakeError.log".

I spent a long time trying to find in CMakeError.log what was wrong but there is no indication that the problem came from Trilinos. It would be great if there a way to catch this error.

**Comment by tjhei** [comment] 2015-07-21 15:24
I don't think there is a way to intercept errors inside FIND_PACKAGE(). The problem is that finding the package succeeds (TRILINOS_FOUND is set). Right, @tamiko ?

**Comment by tamiko** [comment] 2015-07-21 15:32
@tjhei No - <code>FIND_PACKAGE()</code> just looks for a config file and includes it. Basically, we're completely out of control. Further, there is no way for introspection - you cannot ask cmake whether it encountered an error during configure so far...

**Comment by tjhei** [comment] 2015-07-21 15:37
That is annoying. The only thing I can think of for Trilinos would be to do a ```CHECK_CXX_SOURCE_RUNS``` if we think that might happen often enough. What do you say?

**Comment by Rombur** [comment] 2015-07-21 16:25
Can't we look at all the packages that are in TrilinosConfig.cmake and then set TRILINOS_FOUND only if we find the PackageConfig.cmake for every package in the list? If we don't find the package, we can just throw a message that package needs to be turned off when configuring Trilinos.

**Comment by tjhei** [comment] 2015-07-21 17:11
That would be possible (assuming they won't change their setup): Trilinos_PACKAGE_LIST contains a list of all packages. I have no idea what to check for in an individual package though. ${package}_LIBRARIES (even if empty)?

**Comment by Rombur** [comment] 2015-07-21 19:23
We can look in TrilinosConfig.cmake At the end of the file, there is the include of the configuration file of all the packages that are supposed to be installed. If the file doesn't exist then the package has not been installed.

**Comment by bangerth** [comment] 2015-11-02 08:42
Guys, what should we do here? Do as @Rombur suggests and go double check Trilinos' install manifest, or simply give up?

**Comment by tjhei** [comment] 2015-11-02 14:26
An alternative would be to run a small test with ```CHECK_CXX_SOURCE_RUNS``` that links to Trilinos if detected. It slows down configuration, but it a) is not intrusive (parsing the TrilinosConfig is quite fragile and will probably break in the future), b) catches other problems too.

**Comment by tamiko** [comment] 2018-10-03 20:11
Let's close this issue - trilinos got significantly better at creating valid cmake configurations in the last 3 years :-)

**Closed by tamiko** 2018-10-03 20:11 UTC
Labels: Enhancement, Linear Algebra
