### ISSUE TITLE
Boost Python run-time related error

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#2920] opened 2016-08-05 05:14 UTC
subj
```
dyld: Symbol not found: _PyBaseObject_Type
  Referenced from: /Users/davydden/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/boost-1.61.0-rkeuqtbzvlolf23rrb6kmtzmykyiyczb/lib/libboost_python-mt.dylib
  Expected in: flat namespace
 in /Users/davydden/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/boost-1.61.0-rkeuqtbzvlolf23rrb6kmtzmykyiyczb/lib/libboost_python-mt.dylib
```

It shall not be related to boost per-se as I did link before deal.II to boost which had `python` module enabled. I will double check it now...

My best guess is that one should not look for python module in Boost for main the deal.II library. The original CMake implementation of @Rombur did not change required Boost modules for the deal.II and had a separate Find for Boost+python. I don't recall having any problems at that time. But these are just speculation as I don't know what the real reason is.

In reference to https://github.com/dealii/dealii/pull/2834

**Comment by davydden** [comment] 2016-08-05 05:29
It looks similar to `Trilinos` configuration bug:  
When trilinos is built with Python, `libpytrilinos` is included
through cmake configure files. Namely, `Trilinos_LIBRARIES` in
`TrilinosConfig.cmake` contains pytrilinos. This leads to a
run-time error: `Symbol not found: _PyBool_Type` and prevents
Trilinos to be used in any C++ code, which links executable
against the libraries listed in `Trilinos_LIBRARIES`.  See for detailed explanation
https://github.com/Homebrew/homebrew-science/issues/2148#issuecomment-103614509
A workaround there is it to remove PyTrilinos from the COMPONENTS_LIST.

**Comment by davydden** [comment] 2016-08-05 06:01
Forgot to mention that the error appears when running make tests, i.e. Outside of python.

@tamiko ping

**Comment by Rombur** [comment] 2016-08-05 11:55
@davydden can you try adding ```boost``` to your LD_LIBRARY_PATH or the equivalent for mac.

**Comment by davydden** [comment] 2016-08-05 11:58
@Rombur that's not an option as DYLD_LIBRARY_PATH on mac can not be used anymore without sacrificing security https://github.com/oracle/node-oracledb/issues/231
I really don't think it has anything to do with LD_LIBRARY_PATH.

I am testing a path with a separate `FIND_PACKAGE(Boost 1.54 COMPONENTS python)`.

**Comment by davydden** [comment] 2016-08-05 12:00
p.s. my current patch does not work... so far i have no solution...

**Comment by davydden** [comment] 2016-08-05 12:10
I am currently building from `experimental/python` to confirm that this problem is not there...

**Comment by Rombur** [comment] 2016-08-05 12:35
Could it be because you disabled rpath on mac @tamiko?

**Comment by davydden** [comment] 2016-08-05 12:36
@Rombur can you check if `make tests` run for you with master?

**Comment by Rombur** [comment] 2016-08-05 12:38
I will try again but the version that was merged was working for me.

**Comment by Rombur** [comment] 2016-08-05 13:00
@davydden master works fine for me.

**Comment by tamiko** [comment] 2016-08-05 14:57
@davydden 

Can it be that you accidentally have two different boost installations in your link interface? Can you post ```detailed.log```?


> My best guess is that one should not look for python module in Boost for main the deal.II library.

The problem is that we have to use CMake's ```FindBoost``` module (to meet a number of expectations distributions and users have and to ensure we use boost components from only one boost version). Unfortunately ```FindBoost``` can only be called once - it stubbornly refuses to pick up additional components. *sigh*

That's the reason why I added ```boost_python``` already to the link interface of the library.


My guess is that the link interface is simply incomplete in your case (i.e, we would have to link for the main library against python as well).

PR incoming. Will be somewhat hacky…

**Comment by davydden** [comment] 2016-08-05 15:51
> Can it be that you accidentally have two different boost installations in your link interface? 

very very unlikely as I build with Spack which uses a single boost for the whole graph of deal.II dependencies.


p.s. the only stackoverflow which appears to be relevant is http://stackoverflow.com/questions/33094585/about-boost-python-dyld-symbol-not-found-pybaseobject-type

**Comment by tamiko** [comment] 2016-08-05 16:03
@davydden That was a stray leftover comment :-D, see #2921

**Closed** 2016-08-05 17:34 UTC
Labels: Bug, Build system
