### ISSUE TITLE
Compilation fails when DEAL_II_WITH_CUDA is combined with ALTIVEC vectorization

### ISSUE THREAD

**Issue by dsambit** [dealii/dealii#7328] opened 2018-10-11 05:23 UTC
[detailed.log](https://github.com/dealii/dealii/files/2467479/detailed.log)
```
[ 71%] Building CXX object source/sundials/CMakeFiles/obj_sundials_release.dir/arkode.cc.o
/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(2915): error: identifier "__builtin_vec_splats" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(2946): error: identifier "__builtin_vec_add" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(2957): error: identifier "__builtin_vec_sub" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(2968): error: identifier "__builtin_vec_mul" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(2979): error: identifier "__builtin_vec_div" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(2991): error: identifier "__builtin_vec_vsx_ld" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3002): error: identifier "__builtin_vec_vsx_st" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3050): error: identifier "__builtin_vec_sqrt" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3063): error: identifier "__builtin_vec_abs" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3076): error: identifier "__builtin_vec_max" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3089): error: identifier "__builtin_vec_min" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3128): error: identifier "__builtin_vec_splats" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3159): error: identifier "__builtin_vec_add" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3170): error: identifier "__builtin_vec_sub" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3181): error: identifier "__builtin_vec_mul" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3192): error: identifier "__builtin_vec_div" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3204): error: identifier "__builtin_vec_vsx_ld" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3215): error: identifier "__builtin_vec_vsx_st" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3263): error: identifier "__builtin_vec_sqrt" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3276): error: identifier "__builtin_vec_abs" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3289): error: identifier "__builtin_vec_max" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3302): error: identifier "__builtin_vec_min" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(2915): error: identifier "__builtin_vec_splats" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(2946): error: identifier "__builtin_vec_add" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(2957): error: identifier "__builtin_vec_sub" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(2968): error: identifier "__builtin_vec_mul" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(2979): error: identifier "__builtin_vec_div" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(2991): error: identifier "__builtin_vec_vsx_ld" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3002): error: identifier "__builtin_vec_vsx_st" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3050): error: identifier "__builtin_vec_sqrt" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3063): error: identifier "__builtin_vec_abs" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3076): error: identifier "__builtin_vec_max" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3089): error: identifier "__builtin_vec_min" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3128): error: identifier "__builtin_vec_splats" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3159): error: identifier "__builtin_vec_add" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3170): error: identifier "__builtin_vec_sub" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3181): error: identifier "__builtin_vec_mul" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3192): error: identifier "__builtin_vec_div" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3204): error: identifier "__builtin_vec_vsx_ld" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3215): error: identifier "__builtin_vec_vsx_st" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3263): error: identifier "__builtin_vec_sqrt" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3276): error: identifier "__builtin_vec_abs" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3289): error: identifier "__builtin_vec_max" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(3302): error: identifier "__builtin_vec_min" is undefined

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/thread_management.h(109): warning: attribute does not apply to any entity

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/thread_management.h(281): warning: attribute does not apply to any entity

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/dofs/deprecated_function_map.h(80): warning: attribute does not apply to any entity

22 errors detected in the compilation of "/tmp/tmpxft_00022da7_00000000-6_read_write_vector.cpp1.ii".
make[2]: *** [source/lac/CMakeFiles/obj_lac_debug.dir/read_write_vector.cu.o] Error 1

```
If I set DEAL_II_WITH_CUDA=OFF compilation works fine.

**Comment by Rombur** [comment] 2018-10-11 12:40
Can you run with `make VERBOSE=1` I want to see if everything is sent to gcc or if the problem is with nvcc

**Comment by dsambit** [comment] 2018-10-12 02:43
@Rombur The error output with `make VERBOSE=1` is follows
```
[ 76%] Building CUDA object source/lac/CMakeFiles/obj_lac_debug.dir/read_write_vector.cu.o
cd /gpfs/gpfs0/groups/gavini/dsambit/software/dealii/buildCudaEssl/source/lac && /gpfs/gpfs0/software/rhel72/packages/cuda/9.2/bin/nvcc  -DBOOST_NO_AUTO_PTR -DDEBUG -I/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/buildCudaEssl/source/lac -I/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/buildCudaEssl/include -I/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include -I/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/bundled/umfpack/UMFPACK/Include -I/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/bundled/umfpack/AMD/Include -I/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/bundled/muparser_v2_2_4/include -isystem=/gpfs/gpfs0/software/rhel72/packages/cuda/9.2/include -isystem=/gpfs/gpfs0/software/rhel72/packages/openmpi/3.0.0/gcc-7.2.0/include -isystem=/usr/local/include -isystem=/gpfs/gpfs0/groups/gavini/dsambit/software/boost/install_1.66/include -isystem=/gpfs/gpfs0/groups/gavini/dsambit/software/p4est/installGcc7.2.0/FAST/include  -Xcompiler "-fPIC -Wall -Wextra -Wpointer-arith -Wwrite-strings -Wsynth -Wsign-compare -Wswitch -Woverloaded-virtual -Wsuggest-override -Wno-placement-new -Wno-deprecated-declarations -Wno-literal-suffix -Wno-psabi -fopenmp-simd -std=c++14 -mcpu=power8 -mtune=power8 -mvsx -Wno-unused-local-typedefs -O0 -ggdb " -arch=sm_35 -std=c++14 -G -x cu -c /gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/source/lac/read_write_vector.cu -o CMakeFiles/obj_lac_debug.dir/read_write_vector.cu.o
/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/thread_management.h(109): warning: attribute does not apply to any entity

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/thread_management.h(281): warning: attribute does not apply to any entity

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/thread_management.h(109): warning: attribute does not apply to any entity

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/thread_management.h(281): warning: attribute does not apply to any entity

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/thread_management.h(109): warning: attribute does not apply to any entity

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/thread_management.h(281): warning: attribute does not apply to any entity

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/thread_management.h(109): warning: attribute does not apply to any entity

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/thread_management.h(281): warning: attribute does not apply to any entity

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/thread_management.h(109): warning: attribute does not apply to any entity

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/thread_management.h(281): warning: attribute does not apply to any entity

/gpfs/gpfs0/groups/gavini/dsambit/software/dealii/dealii/include/deal.II/base/vectorization.h(2915): error: identifier "__builtin_vec_splats" is undefined

```

**Comment by Rombur** [comment] 2018-10-12 12:54
@dsambit You could add `&& !defined(__CUDACC__)` [here](https://github.com/dealii/dealii/blob/master/include/deal.II/base/vectorization.h#L62) and [here](https://github.com/dealii/dealii/blob/master/include/deal.II/base/vectorization.h#L2896). @kronbichler do we have a test that shows that the vectorization is working? I fear that adding this condition that will disable vectorization when cuda is enabled.

**Comment by kronbichler** [comment] 2018-10-12 13:12
We do not have a real test because I tried to minimize the number of tests whose output depends on the system. What we have is `tests/matrix_free/cell_categorization` that has output that depends on the selection. AltiVec should end up in the result file `tests/matrix_free/cell_categorization.with_p4est=true.mpirun=1.output` whereas it will end up matching with `tests/matrix_free/cell_categorization.with_p4est=true.mpirun=1.output.novec` in case vectorization is disabled. Does that help? Alternatively, if you just want to inspect the current setting, you could run `step-37` which should print the setting at the top of the file.

**Comment by bangerth** [comment] 2018-10-12 15:27
On 10/12/2018 06:54 AM, Bruno Turcksin wrote:
> @dsambit <https://github.com/dsambit> You could add |&& 
> !defined(__CUDACC__)| here 
> <https://github.com/dealii/dealii/blob/master/include/deal.II/base/vectorization.h#L62> 
> and here 
> <https://github.com/dealii/dealii/blob/master/include/deal.II/base/vectorization.h#L2896>.

How come |__ALTIVEC__| is defined in these places when you are compiling 
with nvcc? The GPU doesn't have altivec extensions, so nvcc shouldn't 
have this preprocessor define active...

**Comment by bangerth** [comment] 2018-10-12 21:56
On 10/12/2018 03:24 PM, Bruno Turcksin wrote:
> After some digging, here is what happens: |nvcc| knows altivec and 
> correctly include the file.

Isn't this the bug? Isn't it correct that nvcc is only used to compile 
for the device but not the host? (I keep being confused about this point...)

> Now in altivec.h there is a macro that 
> replaces |vec_splats| by |__builtin_vec_splats|. If you compile the code 
> with gcc everything works fine. However if you use |nvcc| you get an 
> error about |__builtin_vec_splats| being undefined. So it looks like 
> |nvcc| is doing something wrong. I have asked help from people at 
> NVidia.

It pays to have someone who has access to the NVidia people ;-)

**Comment by masterleinad** [comment] 2018-10-12 22:37
> Isn't this the bug? Isn't it correct that nvcc is only used to compile for the device but not the host? (I keep being confused about this point...)

`nvcc` compiles `CUDA` code by sending it both through the C++ compiler and its own compiler for the device code.  I like the explanation in https://stackoverflow.com/a/8809924.

**Comment by bangerth** [comment] 2018-10-13 14:45
Ah, thanks. So nvcc compiles the file twice. The question, then, is in which of the two phases the `__ALTIVEC__` is defined -- that should only be the case for the host code, right?

**Comment by bangerth** [comment] 2018-10-14 23:56
I don't know how the compilation works in practice. Does compiling something with nvcc create two object files, one for the host and one for the device? If so, where is the mistaken call to `vec_splats`? If not, what is the way the host and device functions are distinguished name-wise, and can you find out in what kind of functions the problem is?

**Comment by Rombur** [comment] 2018-10-15 00:48
> I don't know how the compilation works in practice.

I am not sure myself. My understanding is the following: `nvcc` splits the code between the CUDA kernels and the C++ code. Then it sends the C++ code to `gcc` and it compiles the CUDA code. Finally, it "merges" everything back together.  In our test there was no CUDA code, so `nvcc` should just have sent everything to `gcc` and the merging phase should have been trivial since there was only C++ code. Ideally `nvcc` should have realized that it doesn't have to do anything and that it should just let `gcc` do its job. This is no what happens and somehow `nvcc` tripped `gcc`.

**Comment by Rombur** [comment] 2018-12-05 14:38
From Nvidia:
```
OK, I heard back from the compiler team. The NVCC front-end, which interprets the file
before passing the host parts to the host compiler, does not support altivec intrinsics and
it would be a significant effort to fix this, so I don’t expect that it will be fixed in 
the near future. You can still build files containing alitvec separately with g++ and link 
them together.
 ```
So the only solution is to make sure that `nvcc` never sees `altivec` intrinsics.

**Comment by dsambit** [comment] 2019-01-30 00:00
Using #7655 still gives the "__builtin_...." not defined compilation error with ALTIVEC.

**Comment by masterleinad** [comment] 2019-01-30 00:09
I am not that surprised. I am not sure what the best solution is here.
We could simpy disable `ALTIVEC` support when `CUDA` support is enabled, but that would also disable all vectorization when using `nvcc_wrapper` needed for `Trilinos` support.

**Comment by dsambit** [comment] 2019-01-30 00:38
What if we move the offending functions inside
```
#if DEAL_II_COMPILER_VECTORIZATION_LEVEL >= 1 && defined(__ALTIVEC__) && \
  defined(__VSX__)
```
like 
`data = vec_splats(x);`

into a separate .cc file and an accompanying .h file. The .h file will have the declaration something like vec_splats_altivec_internal(x) ...
The .cc file can then be separately compiled without nvcc and finally linked.

**Comment by masterleinad** [comment] 2019-01-30 00:51
As I was saying, this is likely not going to work with `nvcc_wrapper` as a compiler because then all code is sent through `nvcc`. On the other hand, we can always improve after fixing compiling.

I currently don't have access to a system supporting `AltiVec`. Go ahead if you want to try something that only affects `AltiVec` builds.

**Comment by Rombur** [comment] 2019-01-30 13:47
> We could simpy disable ALTIVEC support when CUDA support is enabled, but that would also disable all vectorization when using nvcc_wrapper needed for Trilinos support.

I think that's the way to go for now. If you are using a POWER chip, you will probably have a few GPUs attached to it so you won't lose too much performance by losing vectorization. The only place you are going to lose performance is if you do matrix-free on the CPU. However, you should be able to get most of the performance back if you switch to `xlc` instead of `gcc` because `xlc` is a lot more aggressive on vectorization (might need to get rid of `unsigned int` and use `int` instead to help the compiler). I have been able to compile deal.II with `xlc` (CPU only) if I don't use the `-g` flag. I haven't tried to use `xlc` and CUDA together though. Another possibility would be to use OpenMP simd pragma to do the vectorization instead of using intrinsics. This would simplify the code and make it more portable but I am not sure about the implication for performance, maybe @kronbichler can comment?

**Comment by kronbichler** [comment] 2019-01-30 13:58
> Another possibility would be to use OpenMP simd pragma to do the vectorization instead of using intrinsics. This would simplify the code and make it more portable but I am not sure about the implication for performance, maybe @kronbichler can comment?

The automatic vectorization would not get us very far in the general case (at least as far as the matrix-free/sum factorization code is concerned). It is because the `VectorizedArray` merges operation in an outer loop (over cells), not an inner loop (over the local dofs) that the compiler would see when trying to vectorize. So I think that the amount of SIMD could will be reduced. On the other hand, AltiVec is not really a wide SIMD, so the performance loss is not really worth bothering about. Especially since Power CPUs seem to be focusing on non-vectorizable loads in general and offload the rest to the GPU where we have a proper model. So I'm also in favor of this change, yes.

**Comment by bangerth** [comment] 2019-01-30 14:17
I am curious how this all is supposed to work anyway in practical codes, i.e., how the CUDA people foresee that the CUDA compilation model is defined as far as vectorization is concerned? The device (GPU) does not have vectorization, or at least its vectorization uses intrinsics that are independent of those used on the host (CPU) simply because these are completely different architectures. So it is clear that one can't use intrinsics and associated data types in code that may be compiled for the device. That is, any function that is marked as `__device__` or that is called by a `__device__` function, regardless of whether it is *also* used by the host. This would suggest that one really can't use intrinsics at all in a code that is supposed to be compiled for both host and device.

But even if one might find a way to only use intrinsics in functions that are used *exclusively* on the host, there is still the question of how, say, an `_m256` data object would be transferred to the device when necessary. Imagine that we had a vector that was built as an array of `_m256` objects -- how would one call a device function that works on it and for that transfers the data to the device?

**Comment by masterleinad** [comment] 2019-01-30 14:30
> That is, any function that is marked as `__device__` or that is called by a `__device__` function, regardless of whether it is _also_ used by the host. This would suggest that one really can't use intrinsics at all in a code that is supposed to be compiled for both host and device.

So far, all the tests worked for older `CUDA` versions so I guess that `CUDA` internally mapped the intrinsics to something compatible on the devices... If such a conversion does not exist (as seems to be the case for newer `CUDA` versions), the user has to make sure to use the intrinsics depending on the compile path as we do now. In the end, the `CUDA` compiler and the host compiler really differ in their capabilities so I don't find it too surprising if the code has to differ at least slightly.

**Comment by masterleinad** [comment] 2019-01-30 14:34
> In the end, it is just an array of doubles and it is common to just reference by it via a double pointer; it is, as far as I know, the official arrangement in the x86/Intel world to allow aliasing between a vector type `__m256` and a scalar `double` type or vector types of different lengths such as `__m512` and `__m256`. So it is a lot of casting - remember all the `reinterpret_cast` stuff from last week?

I guess the question is how these data is supposed to be interpreted on the device. I would not be surprised if you have to use an explicit compatibility conversion somewhere, i.e. first convert a vector type to an array of scalars and then copy to the device.

**Comment by bangerth** [comment] 2019-01-30 14:37
On 1/30/19 7:26 AM, Martin Kronbichler wrote:
> [...] how the CUDA people foresee that the CUDA compilation model is 
> defined as far as vectorization is concerned?
> 
> I guess NVIDIA is not really unhappy that the CPU vector units cannot be 
> served efficiently - at least I do not see an incentive to really work on a
>  solution from the CUDA side that allows to also run the host optimally.

Ha :-) That's the Microsoft approach of just not specifying how something is
supposed to work and define it by an actual implementation. But fair enough.

> So far, all the tests worked for older |CUDA| versions so I guess that
> |CUDA| internally mapped the intrinsics to something compatible on the
> devices...

That's a tall order, given that the device may be in a system that could in 
principle have pretty much any processor architecture -- nvcc would then have 
to understand the intrinsics not only of the x86 world, but also Power and ARM 
(in all of its millions of variations). It does seem to make sense to me that 
nvcc would simply punt in that case.

**Comment by dsambit** [comment] 2019-01-30 23:38
I agree with @Rombur and @kronbichler, that CPU vectorization is not needed on POWER systems if all key computational steps are ported to GPU. In our code we have a Poisson solve which is done on CPU but that is not the key computational step in our algorithm, and we should be fine without vectorization as we will be anyway scaling on many nodes.

**Comment by kronbichler** [comment] 2019-05-10 16:41
I guess there is not much more we can do here. Feel free to reopen in case we should extend our documentation and be more specific on how to disable vectorization.

**Closed by kronbichler** 2019-05-10 16:41 UTC
Labels: GPU, SIMD, but definitely not our fault :rage:
