### ISSUE TITLE
Possible build failure with gcc-6.2

### ISSUE THREAD

**Issue by finkandreas** [dealii/dealii#7204] opened 2018-09-17 14:01 UTC
I stumbled upon a build failure with gcc-6.2, where the following must be true 
- building with zlib
- zlib header is installed in /usr/include

Then there will be an include problem with `#include <cmath>`, because the path `/usr/include` will be included with `-isystem /usr/include`.

The following test program fails to build with the command `g++ -isystem /usr/include test.cpp`:
```
#include <cmath>
#include <iostream>

int main() {
  std::cout << std::sqrt(std::abs(-100)) << std::endl;
  return 0;
}
```
This test program builds fine with gcc-5.3.0, but fails with gcc-6.2.0. It fails also with gcc-7.3.0 and gcc-8.2.0. So I assume that deal.ii would have problems with any newer g++ version, where zlib would be used from the system directory.

I can see the following output in `detailed.log`:
```
        DEAL_II_WITH_ZLIB set up with external dependencies
#            ZLIB_VERSION = 1.2.8
#            ZLIB_INCLUDE_DIRS = /usr/include
#            ZLIB_LIBRARIES = /usr/lib64/libz.so
```

**Comment by finkandreas** [comment] 2018-09-17 14:57
Test program build failure:
```
g++ -isystem /usr/include test_cmath.cpp
In file included from test_cmath.cpp:1:0:
/opt/gcc/6.2.0/snos/include/g++/cmath:45:23: fatal error: math.h: No such file or directory
 #include_next <math.h>
                       ^
compilation terminated.
```
Removing `-isystem /usr/include` will build fine.

And trying to build deal.ii, I get the following build error (same error message, and full compile command):
```
[ 31%] Building CXX object source/sundials/CMakeFiles/obj_sundials_release.dir/arkode.cc.o
cd /scratch/snx1600/anfink/build/cpu/20180917_test/dealii/build.trilinos/source/sundials && /opt/cray/pe/craype/2.5.12/bin/CC  -DBOOST_NO_AUTO_PTR -I/scratch/snx1600/anfink/build/cpu/20180917_test/dealii/build.trilinos/source/sundials -I/scratch/snx1600/anfink/build/cpu/20180917_test/dealii/build.trilinos/include -I/scratch/snx1600/anfink/build/cpu/20180917_test/dealii/src/include -I/scratch/snx1600/anfink/build/cpu/20180917_test/dealii/src/bundled/tbb-2018_U2/include -I/scratch/snx1600/anfink/build/cpu/20180917_test/dealii/src/bundled/boost-1.62.0/include -I/scratch/snx1600/anfink/build/cpu/20180917_test/dealii/src/bundled/umfpack/UMFPACK/Include -I/scratch/snx1600/anfink/build/cpu/20180917_test/dealii/src/bundled/umfpack/AMD/Include -I/scratch/snx1600/anfink/build/cpu/20180917_test/dealii/src/bundled/muparser_v2_2_4/include -isystem /usr/include -isystem /scratch/snx1600/anfink/shared_pasc/20180917_cpu/trilinos/include -isystem /scratch/snx1600/anfink/shared_pasc/20180917_cpu/petsc/include -isystem /opt/cray/pe/hdf5-parallel/1.10.0.3/GNU/5.1/include -isystem /scratch/snx1600/anfink/shared_pasc/20180917_cpu/boost/include -isystem /scratch/snx1600/anfink/shared_pasc/20180917_cpu/p4est/include  -pedantic -fPIC -Wall -Wextra -Wpointer-arith -Wwrite-strings -Wsynth -Wsign-compare -Wswitch -Woverloaded-virtual -Wsuggest-override -Wno-placement-new -Wno-deprecated-declarations -Wno-literal-suffix -Wno-psabi -fopenmp-simd -std=c++11 -fopenmp -march=native -Wno-parentheses -Wno-unused-local-typedefs -O2 -funroll-loops -funroll-all-loops -fstrict-aliasing -o CMakeFiles/obj_sundials_release.dir/arkode.cc.o -c /scratch/snx1600/anfink/build/cpu/20180917_test/dealii/src/source/sundials/arkode.cc
In file included from /scratch/snx1600/anfink/build/cpu/20180917_test/dealii/src/include/deal.II/base/numbers.h:28:0,
                 from /scratch/snx1600/anfink/build/cpu/20180917_test/dealii/build.trilinos/include/deal.II/base/config.h:424,
                 from /scratch/snx1600/anfink/build/cpu/20180917_test/dealii/src/source/sundials/arkode.cc:17:
/opt/gcc/6.2.0/snos/include/g++/cmath:45:23: fatal error: math.h: No such file or directory
 #include_next <math.h>
                       ^
compilation terminated.
```

It boils down to the same error as the test program... Does the test program build for you with the flag `-isystem /usr/include`? Because I tried it on different systems with different gcc versions and they all fail for gcc > 6.2 (didn't try gcc-6.0 or gcc-6.1 though)

**Comment by drwells** [comment] 2018-09-17 15:28
I can confirm that I get the same error with GCC 8 on Arch Linux (i.e., everything is in /usr/lib or /usr/include). What a strange error!

**Comment by drwells** [comment] 2018-09-17 15:30
I can also confirm that I get the same error with `clang++`.

**Comment by drwells** [comment] 2018-09-17 15:34
A description of the problem is here:

https://stackoverflow.com/questions/37218953/isystem-on-a-system-include-directory-causes-errors

**Comment by drwells** [comment] 2018-09-17 15:49
@finkandreas; what version of CMake are you using? Would it be possible for you to post one line of `compile_commands.json` (CMake generates this automatically if you pass `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON`) here so that we can see where `-isystem` was added?

**Comment by finkandreas** [comment] 2018-09-17 16:35
Here my cmake version:
```
cmake --version
cmake version 3.10.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

Here a line from compile_commands.json
```
  "directory": "/scratch/snx1600/anfink/build/cpu/20180917_test/dealii/build.trilinos/source/numerics",
  "command": "/opt/cray/pe/craype/2.5.12/bin/CC  -DBOOST_NO_AUTO_PTR -I/scratch/snx1600/anfink/build/cpu/20180917_test/dealii/build.trilinos/source/numerics -I/scratch/snx1600/anfink/build/cpu/20180917_test/dealii/build.trilinos/include -I/scratch/snx1600/anfink/build/cpu/20180917_test/dealii/src/include -I/scratch/snx1600/anfink/build/cpu/20180917_test/dealii/src/bundled/tbb-2018_U2/include -I/scratch/snx1600/anfink/build/cpu/20180917_test/dealii/src/bundled/boost-1.62.0/include -I/scratch/snx1600/anfink/build/cpu/20180917_test/dealii/src/bundled/umfpack/UMFPACK/Include -I/scratch/snx1600/anfink/build/cpu/20180917_test/dealii/src/bundled/umfpack/AMD/Include -I/scratch/snx1600/anfink/build/cpu/20180917_test/dealii/src/bundled/muparser_v2_2_4/include -isystem /usr/include -isystem /scratch/snx1600/anfink/shared_pasc/20180917_cpu/trilinos/include -isystem /scratch/snx1600/anfink/shared_pasc/20180917_cpu/petsc/include -isystem /opt/cray/pe/hdf5-parallel/1.10.0.3/GNU/5.1/include -isystem /scratch/snx1600/anfink/shared_pasc/20180917_cpu/boost/include -isystem /scratch/snx1600/anfink/shared_pasc/20180917_cpu/p4est/include    -pedantic -fPIC -Wall -Wextra -Wpointer-arith -Wwrite-strings -Wsynth -Wsign-compare -Wswitch -Woverloaded-virtual -Wsuggest-override -Wno-placement-new -Wno-deprecated-declarations -Wno-literal-suffix -Wno-psabi -fopenmp-simd -std=c++11 -fopenmp -march=native -Wno-parentheses -Wno-unused-local-typedefs -O2 -funroll-loops -funroll-all-loops -fstrict-aliasing -o CMakeFiles/obj_numerics_release.dir/data_out_rotation.cc.o -c /scratch/snx1600/anfink/build/cpu/20180917_test/dealii/src/source/numerics/data_out_rotation.cc",
  "file": "/scratch/snx1600/anfink/build/cpu/20180917_test/dealii/src/source/numerics/data_out_rotation.cc"
```

The `-isystem` is added in the file `cmake/macro/macro_deal_ii_insource_setup_target.cmake`, and the path `/usr/include` comes from the module FindZLIB.cmake. Changing the variable `ZLIB_INCLUDE_DIR` in `FindZLIB.cmake` to a dummy value, e.g. /usr/local/include will make it compile (and I will see `-isystem /usr/local/include` in the compile commands)

**Comment by drwells** [comment] 2018-09-17 17:09
Thanks. This is approximately what I expected.

I did some more looking around: here is a CMake bug report on this very issue:

https://gitlab.kitware.com/cmake/cmake/issues/16291

A possible fix is here:

https://trac.webkit.org/changeset/205672/webkit/trunk/Source/cmake/OptionsCommon.cmake

**Comment by drwells** [comment] 2019-03-09 14:04
It looks like recent versions of CMake fixed this: see

https://gitlab.kitware.com/cmake/cmake/commit/5990ecb74133e1a9c885fc0ea62896b501d37fef

Our best advice for users who have compilers installed in odd locations is to use the newest version of CMake. Since there are not any changes that we can make from our side I will close this issue.

**Closed by drwells** 2019-03-09 14:04 UTC
Labels: Build system, but definitely not our fault :rage:
