### ISSUE TITLE
Static analysis: include/deal.II/lac/block_matrix_array.h

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3534] opened 2016-11-11 20:05 UTC

**Comment by bangerth** [comment] 2016-11-11 20:18
Close. I accidentally deleted the text of in the issue :-(

**Comment by bangerth** [comment] 2016-11-11 20:51
We should address these warnings and errors from the static analysis tool PVS:
```
include/deal.II/lac/block_matrix_array.h	268	warn	V690 The 'Entry' class implements a copy constructor, but lacks the '=' operator. It is dangerous to use such a class.
```

In response to #3342.

**Comment by drwells** [comment] 2016-11-11 22:23
This is a duplicate of #3356. Please reopen if I am mistaken.

**Closed by drwells** 2016-11-11 22:23 UTC
Labels: Low priority, Starter project
