### ISSUE TITLE
operator* for Tensor<2> and SymmetricTensor<2>

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#6260] opened 2018-04-18 13:19 UTC
looks like we have inconsistency between the two classes. 

For symmetric tensors `A*B = A_{ij} B_{ij}` (double contraction, returns scalar). 
Whereas for non-symmetric tensor `A*B = A_{ij} B_{jk}` (single contraction, returns 2nd order tensor).
Double contraction can be done with `double_contract<0,0,1,1>(A,B)`.

Not sure how would one fix it but it makes code look strange.
But if we are to fix it by breaking backward compatability, this should happen for 9.0.

@bangerth @jppelteret @tamiko  what do you think?

**Comment by jppelteret** [comment] 2018-04-18 14:04
As the documentation of `SymmetricTensor::operator*` [suggests](https://www.dealii.org/8.5.0/doxygen/deal.II/classSymmetricTensor.html#a3586fe5da69c834e642026d1dc310c65), most contraction operations involving two symmetric tensors are double contractions. I find that in most applications this is suitable and would be reticent to change it. I expect that such a change would break a lot of code. At this point, to fill the gap it would be better to make a `contract()` function with two symmetric tensors as arguments.

**Comment by davydden** [comment] 2018-04-18 14:09
>  I find that in most applications this is suitable and would be reticent to change it.

true, it's suitable in many places, but it just not-ideal that `A*B` means completely different things for symmetric and non-symmetric 2nd order tensors.

> to fill the gap it would be better to make a contract() function with two symmetric tensors as arguments.

that would fill the gap of contraction but won't really address the issue of inconsistency between two tensor classes.


I guess it's a _wontfix_ issue.

**Comment by jppelteret** [comment] 2018-04-18 14:14
Yes, I'd say its a "by design" inconsistency. I'd suggest we wait for the input of the others before saying outright that its _wontfix_, but I personally wouldn't support any change to this interface knowing the havoc it would wreak in all of my codes and, presumably, in the library itself.

**Comment by tamiko** [comment] 2018-04-18 15:04
We at least have `contract` and `double_contract` that should do the same thing in both instances.

When I cleaned up the `tensor.h` header (and wrote the `tensor_accessors.h` stuff), my masterplan was to also provide specialized symmetric variants and after that clean up `symmetric_tensor.h` as well. Unfortunately, I never found the time for that :-(

For reasons of backward compatibility I am not sure whether we can change `operator*` at all.

The only save thing we can do is to deprecate the operator syntax for `Tensor` and `SymmetricTensor` and simply remove the short notation alltogether. But I am not sure whether we should do that either.

**Comment by tjhei** [comment] 2018-04-18 15:11
> The only safe thing we can do is to deprecate the operator syntax for Tensor and SymmetricTensor and simply remove the short notation alltogether. But I am not sure whether we should do that either.

This might not be as bad as you make it sound as there are some advantages to this:
1. You can no longer accidentally make a more expensive operation (``scalar*tensor1*tensor2`` vs ``scalar*(tensor1*tensor2)``
2. It is consistent between tensor and symmetric tensor.
3. There is no room for ambiguity.
4. It makes it more obvious what is happening under the hood (especially for beginners)
5. It is easier to look up the definition of this operation

**Comment by bangerth** [comment] 2018-04-18 16:10
You can't overload `operator*` as a double contraction for regular tensors because the operator already does something different there. So the only option you have is to deprecate the `operator*` for symmetric tensors and instead rely on the `double_contract()` function, which I believe exists for symmetric tensors.

I don't see a particularly good reason why we should do this. The algebra of symmetric tensors is not closed under the one-index multiplication (the product of a symmetric tensor and a symmetric tensor is, in general, not a symmetric tensor). So from a mathematical perspective, one could argue that *there is no* multiplication of symmetric tensors, and that `operator*` must then clearly be the scalar product between two symmetric tensors -- which is exactly what it is.

**Comment by davydden** [comment] 2018-04-18 17:29
> So from a mathematical perspective, one could argue that there is no multiplication of symmetric tensors

I agree and IMO this is a very important side of the story. For consistency reasons I would say `operator*` should not be there at all for rank2 symmetric tensor.

@dealii/dealii  Let's give a poll to see where we stand 

👍 deprecate `operator*` for symmetric tensor and rely on `double_contract()` to do `A:B`. We would still have `operator*` for 4th order symmetric and second order which is a valid operation.
🎉 deprecate `operator*` for both Tensor and SymmetricTensor and simply remove the short notation alltogether. This has some additional advantages outlined by @tjhei  [above](https://github.com/dealii/dealii/issues/6260#issuecomment-382421758), which are also partly there for the first option.
👎  keep things as is and take it as "inconsistency by design" which would probably be what @jppelteret prefer.


That should be more-or-less all the options we have here.

**Comment by tamiko** [comment] 2018-04-27 18:14
Blocks #6156

**Comment by tamiko** [comment] 2018-05-04 01:48
Let's postpone this to the next release.

**Comment by bangerth** [comment] 2020-03-21 00:12
Seems like nobody's particular gung-ho about the issue... Postponing to 9.3.

**Comment by bangerth** [comment] 2022-01-08 04:30
It seems like nobody feels particularly adamant about this issue, so let us close it (via #13196). I have added to the documentation of the various `operator*()` functions involved to document the issue, see the linked to PR.

**Closed** 2022-01-10 10:26 UTC
Labels: Discussion
