### ISSUE TITLE
Mismatch in vectorization capabilities (AVX) on i7-Comet Lake 

### ISSUE THREAD

**Issue by jfriedlein** [dealii/dealii#9164] opened 2019-12-11 20:21 UTC
I run dealii@9.1.1 installed via spack on a laptop with a Comet Lake processor (more system details see below). When calling "make" on a script that contains a header that uses "vectorization.h", I receive the following error message leading to a failed compilation:

$ make
Scanning dependencies of target step-1_with_vectorization_header
[ 50%] Building CXX object CMakeFiles/step-1_with_vectorization_header.dir/step-1_with_vectorization_header.cc.o
In file included from /spack/opt/spack/linux-ubuntu16.04-broadwell/gcc-5.4.0/dealii-9.1.1-tprxjb7z5u7bux2jnncusam6ol4etv4v/include/deal.II/fe/mapping_q_generic.h:25:0,
                 from /spack/opt/spack/linux-ubuntu16.04-broadwell/gcc-5.4.0/dealii-9.1.1-tprxjb7z5u7bux2jnncusam6ol4etv4v/include/deal.II/fe/mapping_q1.h:22,
                 from /spack/opt/spack/linux-ubuntu16.04-broadwell/gcc-5.4.0/dealii-9.1.1-tprxjb7z5u7bux2jnncusam6ol4etv4v/include/deal.II/grid/grid_tools.h:30,
                 from /AVX-test/step-1_with_vectorization_header.cc:26:
/spack/opt/spack/linux-ubuntu16.04-broadwell/gcc-5.4.0/dealii-9.1.1-tprxjb7z5u7bux2jnncusam6ol4etv4v/include/deal.II/base/vectorization.h:47:6: **error**: #error "Mismatch in vectorization capabilities: AVX was detected during configuration of deal.II and switched on, but it is apparently not available for the file you are trying to compile at the moment. Check compilation flags controlling the instruction set, such as -march=native."
    error \
CMakeFiles/step-1_with_vectorization_header.dir/build.make:62: recipe for target 'CMakeFiles/step-1_with_vectorization_header.dir/step-1_with_vectorization_header.cc.o' failed
make[2]: *** [CMakeFiles/step-1_with_vectorization_header.dir/step-1_with_vectorization_header.cc.o] Error 1
CMakeFiles/Makefile2:190: recipe for target 'CMakeFiles/step-1_with_vectorization_header.dir/all' failed
make[1]: *** [CMakeFiles/step-1_with_vectorization_header.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Exemplary, I used the step-1 tutorial and added the grid_tools.h-header (in line 26), which uses the vectorization.h file.
[CMakeLists.txt](https://github.com/dealii/dealii/files/3952240/CMakeLists.txt)
[step-1_with_vectorization_header.cc.txt](https://github.com/dealii/dealii/files/3952243/step-1_with_vectorization_header.cc.txt)
The error message directly results from the latter header file, where the following conditions are checked:
https://github.com/dealii/dealii/blob/767d832842d06d37180e96e6602163cb49b7414c/include/deal.II/base/vectorization.h#L45-L49
For some reason, my processor does not seem to meet this condition.
To sum up, the following questions arise:

1. Does this error come from the Comet Lake processor architecture? While running spack install the following warning came up: "==> Warning: gcc@5.4.0 cannot build optimized binaries for "skylake". Using best target possible: "broadwell"". So spack identified the processor as skylake and choose broadwell as best match (probably with regard to the architecture, because actually it's a Comet Lake i7-10510U)

2. What is protected by this condition? By simply commenting out the above condition, the file compiles and runs fine. (Of course, this is not a sufficient test.)

3. From the error message: How to make AVX available for the current file and how to use -march=native?

4. How can this be fixed? It might be related to files referred to in https://github.com/spack/spack/pull/13820, which would not, however, be within the scope of deal.ii.

I included some information about my spack installation, Linux OS (Lubuntu 16.04) and the processor.
[spack install deal.ii - warning and spack list.txt](https://github.com/dealii/dealii/files/3952225/spack.install.deal.ii.-.warning.and.spack.list.txt)
[OS specs.txt](https://github.com/dealii/dealii/files/3952226/OS.specs.txt)
[Processor specs.txt](https://github.com/dealii/dealii/files/3952227/Processor.specs.txt)

**Comment by kronbichler** [comment] 2019-12-11 20:40
I am not familiar with all specific settings of spack, so I could miss some parts there, but I wrote most of the mechanisms that trigger here. What I believe happens is that you compiled deal.II with `-march=native`, but when compiling the program like step-1 in your case, the compile line does not include `-march=native`. To assess whether that is really the case, I would need the `detailed.log` file from your deal.II build directory, and the compiler details when compiling step-1 where you observe the error, e.g. obtained by `make VERBOSE=1`.

The fact that your compiler might or might not detect Comet Lake/Skylake/Broadwell should be tangential to the actual problem.

The reason why we need to check this is that we create some data structures in selected classes (mostly related to `MatrixFree` and friends) that use data types based on the widest available vector length. If the compiled version of deal.II differs from what the compiler sees in application programs, this will lead to big problems because the size of classes changes and all other nasty stuff.

That said, the use of those data structures is limited, so we should try if we can limit the exposure of the default sizes of vectorization to a few headers only.

**Comment by Rombur** [comment] 2019-12-11 20:42
Can you show the flags that are used when using spack? Not long ago, spack decided to compile every library for the specific architecture you are compiling on and I bet that deal.II and spack disagree on the architecture. What I think happens is that deal.II correctly finds that your processor support AVX but spack injects the wrong flags because it found the wrong architecture.

**Comment by masterleinad** [comment] 2019-12-11 20:43
What is the configuration that `spack` installs? In particular, what is `DEAL_II_CXX_FLAGS`, `DEAL_II_CXX_FLAGS_DEBUG` and `DEAL_II_CXX_FLAGS_RELEASE` in `deal.IIConfig.cmake`?

**Comment by jfriedlein** [comment] 2019-12-13 12:49
First of all, thank you for your replies and insight into what's going on.
I attached the files: `detailed.log`, `deal.IIConfig.cmake` and the output of `make VERBOSE=1`. Here an extract based on `deal.IIConfig-cmake`:
- SET(DEAL_II_CXX_FLAGS "-pedantic -fPIC -Wall -Wextra -Woverloaded-virtual -Wpointer-arith -Wsign-compare  -Wswitch -Wsynth -Wwrite-strings  -Wno-literal-suffix -Wno-psabi -fopenmp-simd -std=c++14 -std=c++14 -Wno-unused-local-typedefs")
- SET(DEAL_II_CXX_FLAGS_DEBUG "-O0 -ggdb -Wa,--compress-debug-sections")
- SET(DEAL_II_CXX_FLAGS_RELEASE "-O2 -funroll-loops -funroll-all-loops -fstrict-aliasing -Wno-unused-local-typedefs")

[detailed.log](https://github.com/dealii/dealii/files/3960798/detailed.log)
[deal.IIConfig.cmake.txt](https://github.com/dealii/dealii/files/3960802/deal.IIConfig.cmake.txt)
[compiler details from make VERBOSE=1.txt](https://github.com/dealii/dealii/files/3960803/compiler.details.from.make.VERBOSE.1.txt)

The `DEAL_II_CXX_FLAGS` in `detailed.log` file deviates from this by the following additional phrases:
- Wsuggest-override
- Wno-deprecated-declarations

**Comment by krishnakumarg1984** [comment] 2020-01-10 11:53
I have exactly the same issue! 

>Mismatch in vectorization capabilities (AVX) 

This is on a Skylake Xeon with the same spack install

**Comment by masterleinad** [comment] 2020-01-10 13:40
For debugging this, it would be useful to know if everything works as expected if you don't use `spack` for building `deal.II`.

The error is really surprising since we only detect `DEAL_II_COMPILER_VECTORIZATION_LEVEL=2`, if `__AVX__` is defined and that is precisely what we check for in `include/deal.II/base/vectorization.h`. I would expect that the compiler only defines `__AVX__` if you specify the architecture to build/optimize for. Can you check that this is the case indeed?
Then, the question is why `DEAL_II_COMPILER_VECTORIZATION_LEVEL=2` is detected nonetheless. https://github.com/dealii/dealii/blob/9d68f83878132d958222cf1e4a69ee5e12496317/cmake/checks/check_01_cpu_features.cmake#L116-L169 should fail. Maybe `spack` is skipping this check by passing `-DDEAL_II_COMPILER_VECTORIZATION_LEVEL=2` to `cmake`?

**Comment by tjhei** [comment] 2020-01-10 13:55
> Maybe `spack` is skipping this check by passing `-DDEAL_II_COMPILER_VECTORIZATION_LEVEL=2` to `cmake`?

I checked the recipe and the only thing relevant that is set is CMAKE_CXX_FLAGS_RELEASE (to something).

**Comment by tjhei** [comment] 2020-01-10 14:12
Maybe that is the problem? spack set ``march=native`` and deal.II detects vectorization but then this is not stored in the cxx flags (see the detailed.log above).

**Comment by masterleinad** [comment] 2020-01-10 14:29
> Maybe that is the problem? spack set `march=native` and deal.II detects vectorization but then this is not stored in the cxx flags (see the detailed.log above).

Maybe, we would need to see the `cmake` call. On the other hand, this is exactly how you would normally enable vectorization and normally the flag is stored then.

**Comment by Rombur** [comment] 2020-01-10 14:38
I am not sure that it is how the flags are injected see [here](https://spack.readthedocs.io/en/latest/basic_usage.html#support-for-specific-microarchitectures). I wonder if they decided to inject the flags directly themselves bypassing deal.II. Then, you could have problem if you don't compile the examples yourselves because the flags are only known by spack.

**Comment by tjhei** [comment] 2020-01-10 15:07
I can reproduce the error here. Weirdly, no optimization flags are in the call to cmake:
```
==> Executing phase: 'cmake'
==> [2020-01-10-09:49:49.458610] 'cmake' '/tmp/heister/spack-stage/spack-stage-dealii-9.1.1-zy4gqbudubhfhmdmet2itmdgn4kjkt4b/spack-src' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:PATH=/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/dealii-9.1.1-zy4gqbudubhfhmdmet2itmdgn4kjkt4b' '-DCMAKE_BUILD_TYPE:STRING=DebugRelease' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=FALSE' '-DCMAKE_INSTALL_RPATH:STRING=/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/dealii-9.1.1-zy4gqbudubhfhmdmet2itmdgn4kjkt4b/lib;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/dealii-9.1.1-zy4gqbudubhfhmdmet2itmdgn4kjkt4b/lib64;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/suite-sparse-5.2.0-45urvb2cbt6czwajjvxkjx2lpvtkrz6t/lib;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/p4est-2.2-4mxjexiqswttmjgrbbfpraldqrbprl4s/lib;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/boost-1.70.0-vtxviasqijnwme5f4fzaplijfaqxu2ma/lib;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/muparser-2.2.6.1-sccxloofmjp7czt25kakxc53hwtqxoex/lib;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/hdf5-1.10.5-k4xqvzgtesg5vcfueophciixfs43gxbz/lib;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/nanoflann-1.2.3-es3ti3jjsvwpvvxvg73vl7bzoe5xtexg/lib;/usr/lib;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/netlib-scalapack-2.1.0-iylvf2giimufgyjhh6mmr2l4mt5u4py4/lib;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/zlib-1.2.11-j2fbkwedsy7j4vszqjtkifwuupbdhcyh/lib;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/sundials-3.2.1-7onauc6r2mfgi4dx6d5t2binraxdrma7/lib;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/metis-5.1.0-knrnwapawvlnokckaj4gzpvztxkz3pkv/lib;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/openblas-0.3.7-oa5gwhvc6ftssausautruzk4osmn6u4e/lib;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/intel-tbb-2019.8-de62cyyydizhpzp7bkgwbhsky3hqsea5/lib;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/adol-c-develop-vnkvalkrpvapeyawfarmujm4ltd3rm44/lib64' '-DCMAKE_PREFIX_PATH:STRING=/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/suite-sparse-5.2.0-45urvb2cbt6czwajjvxkjx2lpvtkrz6t;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/cmake-3.16.2-ffq4kpfeqjtgl5jwfsfcu5qssyfophrb;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/p4est-2.2-4mxjexiqswttmjgrbbfpraldqrbprl4s;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/boost-1.70.0-vtxviasqijnwme5f4fzaplijfaqxu2ma;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/muparser-2.2.6.1-sccxloofmjp7czt25kakxc53hwtqxoex;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/hdf5-1.10.5-k4xqvzgtesg5vcfueophciixfs43gxbz;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/nanoflann-1.2.3-es3ti3jjsvwpvvxvg73vl7bzoe5xtexg;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/netlib-scalapack-2.1.0-iylvf2giimufgyjhh6mmr2l4mt5u4py4;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/zlib-1.2.11-j2fbkwedsy7j4vszqjtkifwuupbdhcyh;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/sundials-3.2.1-7onauc6r2mfgi4dx6d5t2binraxdrma7;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/metis-5.1.0-knrnwapawvlnokckaj4gzpvztxkz3pkv;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/openblas-0.3.7-oa5gwhvc6ftssausautruzk4osmn6u4e;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/intel-tbb-2019.8-de62cyyydizhpzp7bkgwbhsky3hqsea5;/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/adol-c-develop-vnkvalkrpvapeyawfarmujm4ltd3rm44' '-DDEAL_II_COMPONENT_EXAMPLES=ON' '-DBOOST_DIR=/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/boost-1.70.0-vtxviasqijnwme5f4fzaplijfaqxu2ma' '-DLAPACK_FOUND=true' '-DLAPACK_INCLUDE_DIRS=/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/openblas-0.3.7-oa5gwhvc6ftssausautruzk4osmn6u4e/include' '-DLAPACK_LIBRARIES=/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/openblas-0.3.7-oa5gwhvc6ftssausautruzk4osmn6u4e/lib/libopenblas.so' '-DUMFPACK_DIR=/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/suite-sparse-5.2.0-45urvb2cbt6czwajjvxkjx2lpvtkrz6t' '-DZLIB_DIR=/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/zlib-1.2.11-j2fbkwedsy7j4vszqjtkifwuupbdhcyh' '-DDEAL_II_ALLOW_BUNDLED=OFF' '-DDEAL_II_WITH_THREADS:BOOL=ON' '-DTBB_DIR=/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/intel-tbb-2019.8-de62cyyydizhpzp7bkgwbhsky3hqsea5' '-DDEAL_II_COMPONENT_PYTHON_BINDINGS=OFF' '-DDEAL_II_EXAMPLES_RELDIR=share/deal.II/examples' '-DDEAL_II_DOCREADME_RELDIR=share/deal.II/' '-DDEAL_II_DOCHTML_RELDIR=share/deal.II/doc' '-DDEAL_II_WITH_CUDA=OFF' '-DDEAL_II_WITH_MPI:BOOL=ON' '-DCMAKE_C_COMPILER=/usr/bin/mpicc' '-DCMAKE_CXX_COMPILER=/usr/bin/mpic++' '-DCMAKE_Fortran_COMPILER=/usr/bin/mpif90' '-DDEAL_II_WITH_GSL:BOOL=OFF' '-DHDF5_DIR=/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/hdf5-1.10.5-k4xqvzgtesg5vcfueophciixfs43gxbz' '-DDEAL_II_WITH_HDF5:BOOL=ON' '-DP4EST_DIR=/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/p4est-2.2-4mxjexiqswttmjgrbbfpraldqrbprl4s' '-DDEAL_II_WITH_P4EST:BOOL=ON' '-DDEAL_II_WITH_PETSC:BOOL=OFF' '-DDEAL_II_WITH_SLEPC:BOOL=OFF' '-DDEAL_II_WITH_TRILINOS:BOOL=OFF' '-DMETIS_DIR=/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/metis-5.1.0-knrnwapawvlnokckaj4gzpvztxkz3pkv' '-DDEAL_II_WITH_METIS:BOOL=ON' '-DSUNDIALS_DIR=/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/sundials-3.2.1-7onauc6r2mfgi4dx6d5t2binraxdrma7' '-DDEAL_II_WITH_SUNDIALS:BOOL=ON' '-DNANOFLANN_DIR=/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/nanoflann-1.2.3-es3ti3jjsvwpvvxvg73vl7bzoe5xtexg' '-DDEAL_II_WITH_NANOFLANN:BOOL=ON' '-DDEAL_II_WITH_ASSIMP:BOOL=OFF' '-DDEAL_II_WITH_GMSH:BOOL=OFF' '-DMUPARSER_DIR=/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/muparser-2.2.6.1-sccxloofmjp7czt25kakxc53hwtqxoex' '-DDEAL_II_WITH_MUPARSER:BOOL=ON' '-DDEAL_II_WITH_SYMENGINE:BOOL=OFF' '-DDEAL_II_WITH_GINKGO:BOOL=OFF' '-DADOLC_DIR=/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/adol-c-develop-vnkvalkrpvapeyawfarmujm4ltd3rm44' '-DDEAL_II_WITH_ADOLC=ON' '-DDEAL_II_COMPONENT_DOCUMENTATION=OFF' '-DDEAL_II_WITH_ARPACK=OFF' '-DDEAL_II_WITH_NETCDF=OFF' '-DSCALAPACK_FOUND=true' '-DSCALAPACK_INCLUDE_DIRS=/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/netlib-scalapack-2.1.0-iylvf2giimufgyjhh6mmr2l4mt5u4py4/include' '-DSCALAPACK_LIBRARIES=/hdscratch/heister/spack/opt/spack/linux-ubuntu16.04-haswell/gcc-5.4.0/netlib-scalapack-2.1.0-iylvf2giimufgyjhh6mmr2l4mt5u4py4/lib/libscalapack.so' '-DDEAL_II_WITH_SCALAPACK=ON' '-DDEAL_II_WITH_OPENCASCADE=OFF' '-DDEAL_II_WITH_64BIT_INDICES=False'
```

The only thing I could find is
```
SPACK_TARGET_ARGS='-march=haswell -mtune=haswell'; export SPACK_TARGET_ARGS
```
but how this is used I don't know.

Also notice that the release flags (https://github.com/spack/spack/blob/4af630308619afb40b1de89d1f7bac0f57b70a38/var/spack/repos/builtin/packages/dealii/package.py#L447-L453) are not even set.

**Comment by Rombur** [comment] 2020-01-10 15:22
If you look [here](https://github.com/spack/spack/blob/develop/lib/spack/env/cc#L398-L409) and [here](https://github.com/spack/spack/blob/develop/lib/spack/env/cc#L398-L409), it does look like they inject their own flags to every call to the compiler that's why CMake detects the vectorization flags.

**Comment by tjhei** [comment] 2020-01-10 15:42
> If you look [here](https://github.com/spack/spack/blob/develop/lib/spack/env/cc#L9-L20) and [here](https://github.com/spack/spack/blob/develop/lib/spack/env/cc#L398-L409), it does look like they inject their own flags to every call to the compiler that's why CMake detects the vectorization flags.

so maybe the fix is to set ``+optflags``?

**Comment by krishnakumarg1984** [comment] 2020-01-10 16:02
Ok, I just tried this spack-build on a MacBook Pro running Catalina. And everything works fine!

So, what does this mean? `clang` is able to set the correct flags while `gcc` is unable to?

Secondly, can we reduce the impact of this vectorization calls to only a subset of the header files to minimize this impact?

**Comment by krishnakumarg1984** [comment] 2020-01-10 16:04
@masterleinad Yes, everything works fine on a non-spack build. I just installed using `candi` and was able to run the tutorials without error.

**Comment by Rombur** [comment] 2020-01-10 16:08
One fix it's for people to do `spack install dealii target=x86_64` That will disable architecture dependent flags. I think we will have to change the recipe in spack for a real fix.

**Comment by masterleinad** [comment] 2020-01-10 16:33
Indeed, `spack` adds `${SPACK_TARGET_ARGS}` to the `flags` used: https://github.com/spack/spack/blob/4af630308619afb40b1de89d1f7bac0f57b70a38/lib/spack/env/cc#L399-L409
We should be good if we could pass these to `DEAL_II_CXX_FLAGS` as well.

**Comment by krishnakumarg1984** [comment] 2020-01-10 18:34
What would be the workaround for those people who have already installed `dealii` using `spack`? It takes an entire day to do this, and a fair amount of HDD space, so I don't want to do a spack install again.

**Comment by Rombur** [comment] 2020-01-10 19:28
@krishnakumarg1984 I think that adding `-march=native` to `DEAL_II_CXX_FLAGS` in `/path/to/install/lib/cmake/deal.II/deal.IIConfig.cmake` should work.

**Comment by jfriedlein** [comment] 2020-01-11 15:32
@Rombur I can confirm that adding `-march=native` works (at least for me).
In detail:
In the file `deal.IIConfig.cmake`, add the phrase `-march=native` into the quotation marks like this:
`SET(DEAL_II_CXX_FLAGS "[...] -march=native")`

**Comment by krishnakumarg1984** [comment] 2020-01-11 15:36
Ah. I see. I didn't figure out the correct quotes to use. Thank you for the workaround.

There is one or two points not yet fully clear to me.

- Why does it correctly work on macOs without this workaround?
- Will there be a fix to the `spack` build recipe from deal.ii maintainers?

**Comment by Rombur** [comment] 2020-01-13 03:08
> Why does it correctly work on macOs without needing this workaround?

I don't think that's related to the operating system. It depends on the CPU on the machine. Depending on the CPU, we enable different optimizations. It's very probable that you don't AVX on your Mac

> Will there be a fix to the spack build recipe from deal.ii maintainers?

I will look into but I don't know when I'll have time.

**Comment by krishnakumarg1984** [comment] 2020-01-13 12:37
>I don't think that's related to the operating system. It depends on the CPU on the machine. Depending on the CPU, we enable different optimizations. It's very probable that you don't AVX on your Mac

This does not look like the case.  Mine is a late 2018 model MacBook Pro, and it definitely has AVX. In fact, I just confirmed this by running `sysctl -a | grep machdep.cpu.features` on it whcih produces
>machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C

So, clearly `AVX` is present on this Mac, whose CPU is Intel i7-8850H (12) @ 2.60GHz. This can also be confirmed on Intel's [specification page](https://ark.intel.com/content/www/us/en/ark/products/134899/intel-core-i7-8850h-processor-9m-cache-up-to-4-30-ghz.html) for this CPU.

There is clearly something else going on with this spack installation that makes it work on macs, but not on a linux machine.

**Comment by masterleinad** [comment] 2020-01-13 17:07
What is the reported value of  `DEAL_II_COMPILER_VECTORIZATION_LEVEL`  in `detailed.log`? I would assume that you either get 1 or you get 2 and you don't need special flags for `__AVX__` to be defined for that compiler.

**Comment by krishnakumarg1984** [comment] 2020-01-13 17:17
Yes, I get a value of 1 for ` DEAL_II_COMPILER_VECTORIZATION_LEVEL` in the macOS spack installation.

Why is this difference arising for the same spack installer for Linux and Mac?

**Comment by masterleinad** [comment] 2020-01-13 18:06
> Why is this difference arising for the same spack installer for Linux and Mac?

This might be a compiler issue. E.g. we know that `clang-3.6.0` doesn't support our needs for `AVX`. You would need to look into the logs to know exactly why it's not enabled for `Mac`.

**Comment by krishnakumarg1984** [comment] 2020-01-13 18:43
Sigh. This is a very modern (late 2018) MacBook with the latest Catalina OS, and the latest clang compiler.

> Apple clang version 11.0.0 (clang-1100.0.33.16)
> Target: x86_64-apple-darwin19.2.0
> Thread model: posix
> InstalledDir: /Library/Developer/CommandLineTools/usr/bin

The spack-install of deal.ii 9.1.1 on this works fine,  whereas on my workstation running Linux (Ubuntu 18.04) which is a Skylake, the same spack-installer errors out with this issue reported here. Can one of the developers look into this a bit more when they have the time (maybe before next release?)

**Comment by krishnakumarg1984** [comment] 2020-02-18 16:20
I can also confirm that adding `-march=native` to the CXX_FLAGS in the library's cmake config file works.

**Comment by jppelteret** [comment] 2020-03-28 19:10
I've opened up a pull request with Spack to fix this: https://github.com/spack/spack/pull/15731
@jfriedlein Would you mind please checking if this sorts out the issue for you?

**Comment by jfriedlein** [comment] 2020-04-15 17:17
@jppelteret The fix solves the issue on my machine. Thanks, I appreciate it. (Sorry to keep you waiting so long)
I tested this with the current develop versions of spack and dealii.
@krishnakumarg1984 Can you also confirm this?

Can/Shall we close this issue then?

**Comment by krishnakumarg1984** [comment] 2020-04-15 18:09
The fix is just a manual workaround. People normally expect spack packages to just work immediately after installation without the need to tweak any config files. 

I still think that the spack install recipe need to be updated, and the fix PR be linked to this issue before formally closing this. Else the developers will never remember that this issue exists.

**Comment by masterleinad** [comment] 2020-04-15 18:19
@krishnakumarg1984 We are referring to the fix in https://github.com/spack/spack/pull/15731 which is merged in `spack`.

**Comment by krishnakumarg1984** [comment] 2020-04-15 21:25
Ah I am sorry. I shall kick off a spack-based install, and test it out soon.

**Comment by krishnakumarg1984** [comment] 2020-04-19 16:14
Yup. this now works!

**Closed** 2020-04-19 16:14 UTC
