### ISSUE TITLE
Possible bug in DoFRenumbering::hierarchical for p::s::Triangulation

### ISSUE THREAD

**Issue by adamqc** [dealii/dealii#5622] opened 2017-12-14 14:05 UTC
The functionality of `DoFRenumbering::hierarchical` for `p::s::Triangulation` may be broken.

The following example shows the problem:
```
#include <deal.II/base/utilities.h>
#include <deal.II/dofs/dof_handler.h>
#include <deal.II/dofs/dof_renumbering.h>
#include <deal.II/distributed/shared_tria.h>
#include <deal.II/distributed/tria.h>
#include <deal.II/fe/fe_dgq.h>
#include <deal.II/grid/grid_generator.h>
#include <deal.II/lac/petsc_parallel_vector.h>
#include <deal.II/numerics/data_out.h>

int main(int argc, char **argv) {
  dealii::Utilities::MPI::MPI_InitFinalize mpi_initialization(argc, argv, 1);

  const int dim = 2;

  size_t comm_rank = dealii::Utilities::MPI::this_mpi_process(MPI_COMM_WORLD);

  size_t comm_id;
  if (comm_rank < 2) {
    comm_id = 0;
  } else {
    comm_id = 1;
  }

  MPI_Comm comm;
  MPI_Comm_split(MPI_COMM_WORLD, comm_id, comm_rank, &comm);

  dealii::FE_DGQ<dim> fe(0);

  dealii::parallel::shared::Triangulation<dim> tria_global(MPI_COMM_WORLD);
  // dealii::parallel::distributed::Triangulation<dim> tria_global(MPI_COMM_WORLD);
  dealii::GridGenerator::hyper_cube(tria_global, -1, 1);
  tria_global.refine_global(4);

  dealii::DoFHandler<dim> dh_global(tria_global);
  dh_global.distribute_dofs(fe);
  dealii::DoFRenumbering::hierarchical(dh_global);

  dealii::parallel::shared::Triangulation<dim> tria(comm);
  // dealii::parallel::distributed::Triangulation<dim> tria(comm);
  dealii::GridGenerator::hyper_cube(tria, -1, 1);
  tria.refine_global(4);

  dealii::DoFHandler<dim> dh(tria);
  dh.distribute_dofs(fe);
  dealii::DoFRenumbering::hierarchical(dh);

  dealii::Vector<double> v(dh_global.n_dofs());
  for (size_t i = 0; i < dh_global.n_dofs(); ++i) {
    v[i] = i;
  }

  dealii::DataOut<dim> data_out_global;
  data_out_global.attach_dof_handler(dh_global);
  data_out_global.add_data_vector(v, "v", dealii::DataOut<dim>::type_dof_data);
  data_out_global.build_patches();
  data_out_global.write_vtu_in_parallel("mesh.vtu", MPI_COMM_WORLD);

  dealii::DataOut<dim> data_out;
  data_out.attach_dof_handler(dh);
  data_out.add_data_vector(v, "v", dealii::DataOut<dim>::type_dof_data);
  data_out.build_patches();
  data_out.write_vtu_in_parallel(("mesh-" + dealii::Utilities::to_string(comm_id) + ".vtu").c_str(), comm);

  MPI_Comm_free(&comm);

  return 0;
}
```

Here is the result using 5 MPI processors:

![snipaste_2017-12-14_21-53-51](https://user-images.githubusercontent.com/5762792/33995719-cf43494c-e119-11e7-9ee6-28769b5765d4.png)
mesh.vtu.png (5 proc)

![snipaste_2017-12-14_21-54-11](https://user-images.githubusercontent.com/5762792/33995724-d1537fa4-e119-11e7-820e-0ac21798073d.png)
mesh-0.vtu.png (2 proc)

![snipaste_2017-12-14_21-54-42](https://user-images.githubusercontent.com/5762792/33995727-d34043a6-e119-11e7-8d52-a735ed5ef312.png)
mesh-1.vtu.png (3 proc)

These figures are expected to be identical.

**Comment by adamqc** [comment] 2017-12-19 02:02
@davydden Any clue? I'd like to give it a try, but I am not aware of where the problem is. Could you please give me some hints?

**Comment by bangerth** [comment] 2017-12-19 17:22
I'm having a bit of trouble understanding the problem. What is the role of the split communicator? Could you simplify the code so that it only outputs one image that looks wrong? I guess you expect the second picture to be correct, right?

**Comment by masterleinad** [comment] 2017-12-19 19:55
I can reproduce the problem also without splitting the communicator with the exact same result. @adamqc's idea was probably to only need to run once to get the results for different number of processors.
What we expect is that all these pictures look the same. I can confirm that this is the case for a `parallel::distributed::Triangulation`.

**Comment by adamqc** [comment] 2017-12-20 03:07
@bangerth `DoFRenumbering::hierarchical` guarantees the same DoF ordering for different MPI processes. So these three figures need to be the same. The reason I split communicator is that we can get the results for different number of processes in only one run, just as @masterleinad said.

**Comment by bangerth** [comment] 2017-12-20 04:07
OK, I see. But can one of you attach a shorter testcase that is easier to debug? The shorter a testcase, the easier it's generally to debug. It's enough if it produces different output when run with different numbers of processors -- for example, in an ideal world, with one and two processors.

Also, the fewer cells the better. Do you still see the bug if you globally refine, say, twice?

**Comment by adamqc** [comment] 2017-12-20 05:19
The following is a simplified example to show the problem:
```
#include <deal.II/base/utilities.h>
#include <deal.II/dofs/dof_handler.h>
#include <deal.II/dofs/dof_renumbering.h>
#include <deal.II/distributed/shared_tria.h>
#include <deal.II/fe/fe_dgq.h>
#include <deal.II/grid/grid_generator.h>

int main(int argc, char **argv) {
  dealii::Utilities::MPI::MPI_InitFinalize mpi_initialization(argc, argv, 1);

  const int dim = 2;

  dealii::FE_DGQ<dim> fe(0);

  dealii::parallel::shared::Triangulation<dim> tria_world(MPI_COMM_WORLD);
  dealii::GridGenerator::hyper_cube(tria_world, -1, 1);
  tria_world.refine_global(2);

  dealii::DoFHandler<dim> dh_world(tria_world);
  dh_world.distribute_dofs(fe);
  dealii::DoFRenumbering::hierarchical(dh_world);

  dealii::parallel::shared::Triangulation<dim> tria_self(MPI_COMM_SELF);
  dealii::GridGenerator::hyper_cube(tria_self, -1, 1);
  tria_self.refine_global(2);

  dealii::DoFHandler<dim> dh_self(tria_self);
  dh_self.distribute_dofs(fe);
  dealii::DoFRenumbering::hierarchical(dh_self);

  typename dealii::DoFHandler<dim>::active_cell_iterator cell_world = dh_world.begin_active(),
           endc_world = dh_world.end(), cell_self = dh_self.begin_active(), endc_self = dh_self.end();
  for (; cell_world != endc_world && cell_self != endc_self; ++cell_world, ++cell_self) {
    if (cell_world->is_locally_owned()) {
      if (cell_world->dof_index(0) != cell_self->dof_index(0)) {
        std::cout << "Failed" << std::endl;
      }
    }
  }

  return 0;
}
```

**Comment by bangerth** [comment] 2017-12-30 22:12
That's an excellent test case!

I've looked into it a bit and tried to first understand how the code works, but ran into another bug (#5686) that I need to fix first. I'll get to the issue here next.

**Comment by bangerth** [comment] 2018-01-11 02:06
#5718 (and the previous patches referenced above) make sure that `DoFRenumbering::hierarchical()` returns something sensible and well-defined for `parallel::shared::Triangulation`. In particular, when using "Z order partitioning", this is probably what you want.

But after some consideration, I don't think what you are asking for makes sense for general partitioning. That's because partitioners such as METIS or Zoltan do not respect Z order. In other words, this part of the documentation in #5718 applies:
```
   * For meshes based on parallel::shared::Triangulation, the situation is
   * more complex. Here, the set of locally owned cells is determined by
   * a partitioning algorithm (selected by passing an object of type
   * parallel::shared::Triangulation::Settings to the constructor of the
   * triangulation), and in general these partitioning algorithms may
   * assign cells to @ref GlossSubdomainId "subdomains" based on
   * decisions that may have nothing to do with the Z order. (Though it
   * is possible to select these flags in a way so that partitioning
   * uses the Z order.) As a consequence, the cells of one subdomain
   * are not contiguous in Z order, and if one renumbered degrees of freedom
   * based on the Z order of cells, one would generally end up with DoF
   * indices that on each processor do not form a contiguous range.
   * This is often inconvenient (for example, because PETSc cannot store
   * vectors and matrices for which the locally owned set of indices
   * is not contiguous), and consequently this function uses the following
   * algorithm for parallel::shared::Triangulation objects:
   * - It determines how many degrees of freedom each processor owns.
   *   This is an invariant under renumbering, and consequently we can
   *   use how many DoFs each processor owns at the beginning of the current
   *   function. Let us call this number $n_P$ for processor $P$.
   * - It determines for each processor a contiguous range of new
   *   DoF indices $[b_P,e_P)$ so that $e_P-b_P=n_P$, $b_0=0$, and
   *   $b_P=e_{P-1}$.
   * - It traverses the <i>locally owned cells</i> in Z order and
   *   renumbers the locally owned degrees of freedom on these cells
   *   so that the new numbers fit within the interval $[b_P,e_P)$.
   * In other words, the <i>locally owned degrees of freedom</i> on each
   * processor are sorted according to the Z order of the locally
   * owned cells they are on, but this property may not hold globally,
   * across cells. This is because the partitioning algorithm may have
   * decided that, for example, processor 0 owns a cell that comes
   * <i>later</i> in Z order than one of the cells assigned to processor 1.
   * On the other hand, the algorithm described above assigns the
   * degrees of freedom on this cell <i>earlier</i> indices than
   * all of the indices owned by processor 1.
```

That is, if we really did renumber based on Z-order, we would get non-contiguous locally owned DoF indices. Is that really what you would want? (This may be what @tjhei alluded to in #5686 and that I simply didn't understand at the time.)

**Comment by bangerth** [comment] 2018-01-16 21:16
@adamqc -- do you have an opinion?

**Comment by bangerth** [comment] 2018-01-23 18:09
I'll close this for now. @adamqc -- if you have something to add to the discussion above, please feel free to re-open the issue!

**Closed by bangerth** 2018-01-23 18:09 UTC
Labels: Bug, Parallel shared
