### ISSUE TITLE
External boost 1.64 is missing a function we use

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#4302] opened 2017-04-24 16:44 UTC
Specifically, as reported by @cpraveen on the mailing list, we have this problem:
```
/Users/praveen/Applications/deal.II/git/include/deal.II/base/aligned_vector.h:863:31: error: 
      no member named 'make_array' in namespace 'boost::serialization'
    ar &boost::serialization::make_array(_data, vec_size);
        ~~~~~~~~~~~~~~~~~~~~~~^
```
This is because the `make_array` function is apparently no longer in the BOOST files we include in `aligned_vector.h` when using BOOST 1.64.

But, @cpraveen also reports this:
```
$ grep -r make_array serialization/*
serialization/array_wrapper.hpp:    // make_array.  So I make make_array a friend
serialization/array_wrapper.hpp:    friend const boost::serialization::array_wrapper<Tx> make_array(Tx * t, S s);
serialization/array_wrapper.hpp:const array_wrapper< T > make_array(T* t, S s){
serialization/valarray.hpp:        ar << serialization::make_array<const U, collection_size_type>(
serialization/valarray.hpp:        ar >> serialization::make_array<U, collection_size_type>(
serialization/vector.hpp:        ar << serialization::make_array<const U, collection_size_type>(
serialization/vector.hpp:        ar >> serialization::make_array<U, collection_size_type>(
```
So we may get away with `#include`ing `array_wrappers.hpp` instead of `array.hpp`. Annoyingly, however, `array_wrappers.hpp` doesn't exist in the bundled BOOST 1.62. We may have to wrap the additional `#include` into a `#ifdef` that checks the BOOST version number.

This is all not very difficult, it's just a hassle to try out for someone.

**Comment by bangerth** [comment] 2017-04-24 16:49
@cpraveen -- if we came up with a patch, would you be willing to try it on your system?

**Comment by cpraveen** [comment] 2017-04-24 16:54
ok

**Comment by masterleinad** [comment] 2017-04-24 17:30
Changing 
```#include <boost/serialization/array.hpp>```
to
```#include <boost/serialization/array_wrapper.hpp>```
works for me. I will create a PR.

**Comment by bangerth** [comment] 2017-04-24 17:34
But it's not going to work with the bundled boost, is it? `array_wrappers.hpp` doesn't exist there...

**Comment by masterleinad** [comment] 2017-04-24 17:38
@bangerth The only thing I wanted to say is that this change fixes the issue for `boost-1.64.0`.
I agree that we probably need a `#ifdef ` switch.

**Comment by bangerth** [comment] 2017-04-24 17:50
Yes. I think it needs to look like this:
```
#include <bboost/serialization/array.hpp>
#if BOOST_VERSION >= 106300  // or 64, need to check
#  include <bboost/serialization/array_wrapper.hpp>
#endif
```

**Comment by davydden** [comment] 2017-04-24 17:59
FYI, boost `1.64` appears to be buggy, i.e. you can't build it with both `mpi` and `python` enabled, see https://github.com/LLNL/spack/issues/3963 . That is why Spack kind of black-lists it, see https://github.com/LLNL/spack/pull/3964 . So if the patch does not work with `1.64`, we may as well throw an error requiring other version.

**Comment by bangerth** [comment] 2017-04-24 21:16
The new header appears in boost 1.64.

**Comment by bangerth** [comment] 2017-04-24 21:50
@cpraveen -- can you try whether this patch works with your external boost version?
```
diff --git a/include/deal.II/base/aligned_vector.h b/include/deal.II/base/aligned_vector.h
index 9f3c431..6a1b196 100644
--- a/include/deal.II/base/aligned_vector.h
+++ b/include/deal.II/base/aligned_vector.h
@@ -23,6 +23,12 @@
 #include <deal.II/base/utilities.h>
 #include <deal.II/base/parallel.h>
 #include <boost/serialization/array.hpp>
+
+// boost::serialization::make_array used to be in array.hpp, but was
+// moved to a different file in BOOST 1.64
+#if BOOST_VERSION >= 106300  // or 64, need to check
+#  include <boost/serialization/array_wrapper.hpp>
+#endif
 #include <boost/serialization/split_member.hpp>

 #include <cstring>
```

**Comment by masterleinad** [comment] 2017-04-24 21:52
It seems that boostorg/serialization@6b33d1cd4e11daaf97612561ecd9d4848843897c is guilty. This is after `boost-1.63.0`. Since the problem seems to be fixed in boostorg/serialization@1d86261, it should be sufficient to only check for `BOOST_VERSION == 1006400`.

**Comment by bangerth** [comment] 2017-04-24 21:57
Oh, they saw the problem too. Is there a github issue that goes with the second of these patches?

**Comment by masterleinad** [comment] 2017-04-24 22:34
No, I don't see any PR's or Issues attached to these commits.

Reading the first commit, again it seems that including `boost/serialization/array_wrapper.hpp`
instead of `boost/serialization/array.hpp` is the intended way now. This works since the latter file is included in the former.

**Comment by cpraveen** [comment] 2017-04-25 03:22
On Tue, Apr 25, 2017 at 3:20 AM, Wolfgang Bangerth <notifications@github.com
> wrote:

> diff --git a/include/deal.II/base/aligned_vector.h b/include/deal.II/base/aligned_vector.h
> index 9f3c431..6a1b196 100644 --- a/include/deal.II/base/aligned_vector.h
> +++ b/include/deal.II/base/aligned_vector.h @@ -23,6 +23,12 @@ #include
> <deal.II/base/utilities.h> #include <deal.II/base/parallel.h> #include
> <boost/serialization/array.hpp> + +// boost::serialization::make_array
> used to be in array.hpp, but was +// moved to a different file in BOOST
> 1.64 +#if BOOST_VERSION >= 106300 // or 64, need to check +# include
> <boost/serialization/array_wrapper.hpp> +#endif #include
> <boost/serialization/split_member.hpp> #include <cstring>


This patch did not fix the problem for me.

Best
praveen

**Comment by bangerth** [comment] 2017-04-25 03:37
What is the error you get with it?

**Comment by cpraveen** [comment] 2017-04-25 03:48
@bangerth I see that now the error comes at a later stage of compilation. So your patch worked for that file. Using #4309  should fix it.

**Closed** 2017-04-25 15:39 UTC

**Comment by marcfehling** [comment] 2018-06-01 05:33
I just tried building the current release of <code>dealii-9.0.0</code> with the Intel compiler and an older version of boost, and encountered another issue with the <code>array_wrapper</code> function.

I am using <code> icpc (ICC) 17.0.2 20170213</code> for compilation and CMake found <code>BOOST_VERSION: 1.61.0</code>. For some weird reason this error manifests while linking <code>step-12</code>:
```
Scanning dependencies of target step-12.release
[ 80%] Building CXX object examples/CMakeFiles/step-12.release.dir/step-12/step-12.cc.o
NOTE: Use of this header (bool_trait_def.hpp) is deprecated
NOTE: Use of this header (template_arity_spec.hpp) is deprecated
NOTE: Use of this header (template_arity_spec.hpp) is deprecated
[ 80%] Linking CXX executable ../bin/step-12.release
../lib/libdeal_II.so.9.0.0: undefined reference to `boost::serialization::array_wrapper<unsigned long long> const boost::serialization::make_array<unsigned long>(unsigned long long*, unsigned long)'
../lib/libdeal_II.so.9.0.0: undefined reference to `boost::serialization::array_wrapper<unsigned int> const boost::serialization::make_array<boost::serialization::collection_size_type>(unsigned int*, boost::serialization::collection_size_type)'
../lib/libdeal_II.so.9.0.0: undefined reference to `boost::serialization::array_wrapper<std::pair<unsigned long long, double> > const boost::serialization::make_array<unsigned long>(std::pair<unsigned long long, double>*, unsigned long)'
../lib/libdeal_II.so.9.0.0: undefined reference to `boost::serialization::array_wrapper<unsigned int> const boost::serialization::make_array<unsigned long>(unsigned int*, unsigned long)'
../lib/libdeal_II.so.9.0.0: undefined reference to `boost::serialization::array_wrapper<char> const boost::serialization::make_array<unsigned long>(char*, unsigned long)'
make[2]: *** [bin/step-12.release] Error 1
make[1]: *** [examples/CMakeFiles/step-12.release.dir/all] Error 2
make: *** [all] Error 2
```

I'm puzzled since @masterleinad's fix takes care of older version of boost as well.

Can someone try to reproduce this?

(This is probably also worth mentioning in context of #6488)

**Comment by marcfehling** [comment] 2018-06-03 18:19
Using <code>icpc (ICC) 18.0.2.20180210</code> together with the bundled version of boost, compilation of deal.II works.

**Comment by bangerth** [comment] 2018-06-07 01:32
Yes, and we already do something like this. Poke around the `cmake/` directory a bit -- probably in a file called `FindBoost.cmake` or similar. We hardcode some version there. We could update that minimum version.

**Comment by masterleinad** [comment] 2018-06-07 08:37
> Using icpc (ICC) 18.0.2.20180210 together with the bundled version of boost, compilation of deal.II works.

Does ICC-18 + boost-1.61.0 work for you? I am struggling to reproduce the issue with ICC-19 + boost-1.61.0 (no iostreams) in a recent developer version.

**Comment by marcfehling** [comment] 2018-06-08 23:09
I compiled <code>deal.II-9.0.0</code> with <code>boost-1.61.0</code> and <code>icc-18.0.0</code> and did not experience any issues at all. There seems to be something wrong with <code>icc-17.0.x</code>. So I tried to localize it further.

On the workstation where I got the above error first, I tried to compile <code>deal.II-9.0.0</code> with <code>icc-17.0.2</code> and both bundled and 1.61.0 versions of <code>boost</code>, but it always lead to the same error:
```
/usr/include/c++/4.8/functional(1873) (col. 30): internal error: assertion failed: be_value_from_constant: unknown constant kind (shared/cfe/edgglue/edg_decl.c, line 1356)
compilation aborted for .../dealii-9.0.0-modified/examples/step-44/step-44.cc (code 4)
```
However, to get of the error of the previous post, one needs to add some additional flags <code>-DDEAL_II_WITH_MPI=ON</code> and <code>-DDEAL_II_WITH_THREADS=OFF</code> and has to use <code>boost 1.61.0</code>. This particular error does not occur with the bundled version of boost, but compilation terminates anyway with the above error. Strangely, a different tutorial is now concerned.
```
../lib/libdeal_II.g.so.9.0.0: undefined reference to `boost::serialization::array_wrapper<unsigned int> const boost::serialization::make_array<boost::serialization::collection_size_type>(unsigned int*, boost::serialization::collection_size_type)'
../lib/libdeal_II.g.so.9.0.0: undefined reference to `boost::serialization::array_wrapper<std::pair<unsigned int, double> > const boost::serialization::make_array<unsigned long>(std::pair<unsigned int, double>*, unsigned long)'
../lib/libdeal_II.g.so.9.0.0: undefined reference to `boost::serialization::array_wrapper<unsigned int> const boost::serialization::make_array<unsigned long>(unsigned int*, unsigned long)'
examples/CMakeFiles/step-37.debug.dir/build.make:112: recipe for target 'bin/step-37.debug' faile
```

On our supercomputer, compilation with <code>icc-17.0.0, icc-17.0.1, icc-17.0.2</code> yields the following error:
```
.../dealii-9.0.0/source/base/data_out_base.cc(1415): internal error: assertion failed at: "shared/cfe/edgcpfe/interpret.c", line 2310
              nodes[GeometryInfo<dim>::ucd_to_deal[2]] = start+d2;
                                                   ^
```
Versions <code>icc-17.0.4, icc-17.0.5</code> also fail, but with a similar error compared to the workstation:
```
/usr/include/c++/5.4.0/functional(1673) (col. 30): internal error: assertion failed: be_value_from_constant: unknown constant kind (shared/cfe/edgglue/edg_decl.c, line 1356)
compilation aborted for .../dealii-9.0.0-modified/examples/step-44/step-44.cc (code 4)
```

So it doesn't look like to be the fault of an outdated <code>boost</code>, but some compiler bug in <code>icc-17.0.x</code>, that was already frequently addressed in the mailing group (see e.g. [this entry](https://groups.google.com/forum/#!topic/dealii/sKlWdNexZ5A)).

Shall we drop the pull request then?
