### ISSUE TITLE
test failure: fe/fe_enriched_step-36.debug

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#3188] opened 2016-10-04 19:50 UTC
(and  fe/fe_enriched_step-36b.debug):

```
$ ./fe_enriched_step-36.debug
Cycle 0
   Number of active cells:       120
     FE / POUFE :                120 / 8
   Number of degrees of freedom: 1432
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal number 8 FPE: Floating Point Exception,probably divide by zero
```

(inside gmres)

**Comment by davydden** [comment] 2016-10-04 19:51
more info would be helpful (compiler/system/alike).

**Comment by tjhei** [comment] 2016-10-04 20:13
ubuntu 12.04
#        CMAKE_CXX_COMPILER:     Clang 3.7.1 on platform Linux x86_64
#        DEAL_II_WITH_PETSC set up with external dependencies
#            PETSC_VERSION = 3.6.3.0

do you have DEAL_II_HAVE_FP_EXCEPTIONS=ON ?

**Comment by davydden** [comment] 2016-10-04 20:18
> do you have DEAL_II_HAVE_FP_EXCEPTIONS=ON ?

that is `OFF` on macOS with `clang`. I will check this on Ubuntu tomorrow...

**Comment by bangerth** [comment] 2016-10-04 20:28
I think a backtrace in the debugger might be helpful. The location will usually be quite obvious.

**Comment by davydden** [comment] 2016-10-05 11:09
@tjhei: i can't reproduce it on Ubuntu 16 + GCC@5.4.0 with `DEAL_II_HAVE_FP_EXCEPTIONS=ON`. Please run it through debugger on your system.

**Comment by davydden** [comment] 2016-10-05 11:13
@tjhei 

> (inside gmres)

there is not `gmres` there. Shift-and-invert spectral transformation is done via `cg` + `gamg`. Maybe `PETScWrappers::set_option_value` does not work as expected?

**Comment by bangerth** [comment] 2017-01-09 00:53
I can't reproduce this on Ubuntu 16.10 with FP exceptions on. Since @davydden can't either, let's close this; we can always reopen if someone can come up with a system that reproduces this.

**Closed by bangerth** 2017-01-09 00:53 UTC
Labels: Bug
