### ISSUE TITLE
Images on the main web page

### ISSUE THREAD

**Issue by cuneytsert** [dealii/dealii#6791] opened 2018-06-19 13:39 UTC
The images on the main web page of deal.II do not reflect the quality of this library. They are blurred, with no appeal. I think deal.II deserves better images on its main web page.

**Comment by davydden** [comment] 2018-06-19 13:51
Absolutely agree! I think this issue was also brought up in some discussion recently.

@dealii/dealii we might want to ask users and devs for most interesting hi-res pictures of the research (1 per user/dev) and choose best 10 or so.

**Comment by bangerth** [comment] 2018-06-19 14:22
We have lots of good images in the directory of the repo right above where we store the low-res ones. If someone could change the script that shows the rotating cast of pictures so that it automatically scales high res ones to a uniform size, then we are ready to go :-)

**Comment by jppelteret** [comment] 2018-06-19 14:34
I've been meaning to add some images to the gallery, so @bangerth here are a few more to add to the collection.

![magnetoelastic_composite](https://user-images.githubusercontent.com/10460610/41603988-69a2143a-73de-11e8-8ed7-5de29343a323.png)
![magnetoelastic_strip](https://user-images.githubusercontent.com/10460610/41603989-69e158b6-73de-11e8-8e74-7e5bdf7c641c.png)
![tongue-genioglossus_activation](https://user-images.githubusercontent.com/10460610/41603990-6a17ec78-73de-11e8-980d-32c8b0649dc8.png)
![tongue-posterior_genioglossus_activation](https://user-images.githubusercontent.com/10460610/41603991-6a3d022e-73de-11e8-99c5-0ed9d457039a.png)

**Comment by davydden** [comment] 2018-06-19 19:01
let me through in one pic while we are at it:
![c60_dft](https://user-images.githubusercontent.com/8023934/41618605-e9d95b70-7403-11e8-8391-1ebf1f8704b2.png)

**Comment by drwells** [comment] 2018-06-19 19:06
I have a nice picture of a POD vector from my thesis that I have been meaning to put up: I'll add it here :)
![pod-vec-1](https://user-images.githubusercontent.com/3917035/41618835-4370c448-73d2-11e8-9122-141bbf9f20c9.png)

**Comment by bangerth** [comment] 2018-07-06 01:39
Nice pictures, y'all! I've added them to the repository now. Below is one I've recently added as well.

Now we just need to find a way to update the script so that it draws from the other directory as mentioned above.

![njinju](https://user-images.githubusercontent.com/7504421/42355617-2d6f6d82-808b-11e8-8d70-29f29db611cf.png)

**Comment by luca-heltai** [comment] 2018-07-06 05:51
Can I use it for the poster of our workshop?

Luca

**Comment by bangerth** [comment] 2018-07-06 16:42
Which one? The one I posted? I think so, though I only did the visualization. The simulation is by Emmanuel Njinju. I suspect that he's not opposed to it either, but let's ask: @njinju, any objections?

**Comment by njinju** [comment] 2018-07-06 17:10
No objection at all.

Emmanuel Njinju
Ph.D. Student
Virginia Tech
Department of Geosciences
2405050201
njinju85@vt.edu



On Fri, Jul 6, 2018 at 12:42 PM, Wolfgang Bangerth <notifications@github.com

**Comment by davydden** [comment] 2018-07-06 17:12
> Now we just need to find a way to update the script

can you point to the current version?

**Comment by bangerth** [comment] 2018-07-06 17:54
@davydden : The problem is that (i) the script is in a repo to which only a couple of us seem to have access, and (ii) that the script is executed server-side. I've found this arrangement difficult to test because I can't run things locally without installing a full web server.

Either way, I've made a couple of changes -- let's see if we now get the higher quality pictures.

Of course the downside is that we may get much longer load times. The carousel seems to load all pictures in the directory. For the low-res ones, this added up to 612 kB. For the high-res ones, it's around 11 MB. But maybe bandwidths today are good enough for this. I could also try to throw out some of the less flashy ones.

**Comment by davydden** [comment] 2018-07-06 18:04
> Either way, I've made a couple of changes -- let's see if we now get the higher quality pictures.

thanks!

Maybe eventually we should switch to something like Wordpress, which is easier to manage. I am running 3 websites on wordpress for a while now...

**Comment by bangerth** [comment] 2018-07-06 20:59
I think this looks better now. I've also removed a bunch of pictures that are visually not at the same level as the ones I've left. We have enough good ones.

Take a look now -- I think this can be closed now. @cuneytsert -- do you agree?

**Comment by drwells** [comment] 2018-07-07 13:17
I need to regenerate the step-32 pictures without the grey background.

**Comment by bangerth** [comment] 2018-07-08 02:21
Let's close the issue for now. We can open other issues for separate (though related) issues as necessary.

**Closed by bangerth** 2018-07-08 02:21 UTC

**Comment by cuneytsert** [comment] 2018-07-08 17:19
Several images on https://github.com/dealii/dealii/wiki/Gallery seem to be missing. Maybe it is related with the modifications done for this issue.

**Comment by bangerth** [comment] 2018-07-09 14:40
Good point -- I had forgotten that these pictures aren't just used for the carousel. Since the gallery is supposed to show only the best pictures, I've just removed those sections referencing pictures that I had previously deleted.
