### ISSUE TITLE
Build error on cori/nersc [via spack]

### ISSUE THREAD

**Issue by balay** [dealii/dealii#7543] opened 2018-12-21 15:14 UTC
I'm seeing errors building deallii via spack today.

However the same build worked before [a week back] - suggesting something on the machine - so this is a bit wierd.

Any idea what could trigger this error?

```
[ 77%] Built target obj_fe_release
lac/CMakeFiles/obj_lac_debug.dir/la_parallel_block_vector.cc.o:la_parallel_block_vector.cc:vtable for dealii::LinearAlgebra::distributed::BlockVector<double>: error: relocation refers to global symbol
"non-virtual thunk to dealii::LinearAlgebra::distributed::BlockVector<double>::~BlockVector()", which is defined in a discarded section
  section group signature: "_ZN6dealii13LinearAlgebra11distributed11BlockVectorIdED1Ev"
  prevailing definition is from numerics/CMakeFiles/obj_numerics_debug.dir/vector_tools_interpolate.cc.o
lac/CMakeFiles/obj_lac_debug.dir/la_parallel_block_vector.cc.o:la_parallel_block_vector.cc:vtable for dealii::LinearAlgebra::distributed::BlockVector<float>: error: relocation refers to global symbol
"non-virtual thunk to dealii::LinearAlgebra::distributed::BlockVector<float>::~BlockVector()", which is defined in a discarded section
  section group signature: "_ZN6dealii13LinearAlgebra11distributed11BlockVectorIfED1Ev"
  prevailing definition is from numerics/CMakeFiles/obj_numerics_debug.dir/vector_tools_interpolate.cc.o
lac/CMakeFiles/obj_lac_debug.dir/la_parallel_block_vector.cc.o:la_parallel_block_vector.cc:vtable for dealii::LinearAlgebra::distributed::BlockVector<std::complex<double> >: error: relocation refers to
global symbol "non-virtual thunk to dealii::LinearAlgebra::distributed::BlockVector<std::complex<double> >::~BlockVector()", which is defined in a discarded section
  section group signature: "_ZN6dealii13LinearAlgebra11distributed11BlockVectorISt7complexIdEED1Ev"
  prevailing definition is from numerics/CMakeFiles/obj_numerics_debug.dir/vector_tools_interpolate.cc.o
lac/CMakeFiles/obj_lac_debug.dir/la_parallel_block_vector.cc.o:la_parallel_block_vector.cc:vtable for dealii::LinearAlgebra::distributed::BlockVector<std::complex<float> >: error: relocation refers to global
symbol "non-virtual thunk to dealii::LinearAlgebra::distributed::BlockVector<std::complex<float> >::~BlockVector()", which is defined in a discarded section
  section group signature: "_ZN6dealii13LinearAlgebra11distributed11BlockVectorISt7complexIfEED1Ev"
  prevailing definition is from numerics/CMakeFiles/obj_numerics_debug.dir/vector_tools_interpolate.cc.o
source/CMakeFiles/deal_II.g.dir/build.make:818: recipe for target 'lib/libdeal_II.g.so.9.0.1' failed
```
[cori-dealii-spack-build-old.out.txt](https://github.com/dealii/dealii/files/2703284/cori-dealii-spack-build-old.out.txt)
[spack-build.env.txt](https://github.com/dealii/dealii/files/2703285/spack-build.env.txt)

**Comment by drwells** [comment] 2018-12-21 17:22
It looks like this is for the 9.0.1 release which has not been updated recently, so I suspect the issue is with spack. Did things work before spack/spack#10008?

**Comment by balay** [comment] 2018-12-21 20:38
I've attempted a rebuild by reverting the above change - and still get the same error.

I'm pretty sure this build worked before (I think last on dec-13) - and its strange its breaking now.

**Comment by drwells** [comment] 2018-12-24 01:16
I had forgotten about it, but this is actually a problem with intel's compiler: see also #6705.

Lets close this as a duplicate of that issue.

**Closed by drwells** 2018-12-24 01:16 UTC
Labels: Build system
