### ISSUE TITLE
Missing symbol in xSDK link

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#12501] opened 2021-06-26 05:07 UTC
As reported at https://github.com/xsdk-project/xsdk-issues/issues/144, we must be forgetting to explicitly instantiate the following symbol:
```
Undefined symbols for architecture x86_64:
  "void dealii::MGLevelGlobalTransfer<dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >::copy_to_mg<2, double, 2>(dealii::DoFHandler<2, 2> const&, dealii::MGLevelObject<dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> const&, bool) const", referenced from:
      void dealii::MGTransferMatrixFree<2, float>::interpolate_to_mg<double, 2>(dealii::DoFHandler<2, 2> const&, dealii::MGLevelObject<dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> const&) const in step-66.cc.o
  "void dealii::MGLevelGlobalTransfer<dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >::copy_to_mg<3, double, 3>(dealii::DoFHandler<3, 3> const&, dealii::MGLevelObject<dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> const&, bool) const", referenced from:
      void dealii::MGTransferMatrixFree<3, float>::interpolate_to_mg<double, 3>(dealii::DoFHandler<3, 3> const&, dealii::MGLevelObject<dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> const&) const in step-66.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Does anyone see right away where that would have to be instantiated and where we are forgetting it?

**Comment by bangerth** [comment] 2021-06-26 05:08
To be very specific, this is about `void MGLevelGlobalTransfer::copy_to_mg`.

@peterrum ?

**Comment by peterrum** [comment] 2021-06-26 07:45
The implementation of that function is in the header:

https://github.com/dealii/dealii/blob/779a3a250fc869cf98e03e7689db775d0e7cf554/include/deal.II/multigrid/mg_transfer_global_coarsening.h#L471-L475

https://github.com/dealii/dealii/blob/779a3a250fc869cf98e03e7689db775d0e7cf554/include/deal.II/multigrid/mg_transfer_global_coarsening.h#L565-L586

Would it help to add a inline keyword?

**Comment by tjhei** [comment] 2021-06-26 12:14
Duplicate of #12490?

**Comment by peterrum** [comment] 2021-06-26 12:17
@tjhei Could you I ask to add an inline keyword. I don't have a way to reproduce this error.

**Closed** 2021-06-27 06:45 UTC

**Comment by tjhei** [comment] 2021-06-27 12:03
@bangerth can you report back if this fixes it?

**Comment by bangerth** [comment] 2021-06-30 23:55
Yes, seems to have worked!
