### ISSUE TITLE
Regression tester regressed 270aba

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#17665] opened 2024-09-05 17:35 UTC
[start automated regression testsuite report]

Dear all,

this is the automated regression testsuite reporting a new regression between
- new revision: 270abaaf202f1953f32e31e22cb5912b7f00293c  [regression testsuite results](https://cdash.dealii.org/index.php?project=deal.II&filtercount=1&showfilters=1&field1=revision&compare1=63&value1=270aba)
- old revision: 72b6a305289c7093c9b5aaecdf94ca2ca570cd28  [regression testsuite results](https://cdash.dealii.org/index.php?project=deal.II&filtercount=1&showfilters=1&field1=revision&compare1=63&value1=72b6a3)

Summary:
- :disappointed: new build warnings introduced for configuration [GNU-10.2.1-master-debian-11](https://cdash.dealii.org/build/2574) on site tester-tng
- :disappointed: new build warnings introduced for configuration [GNU-11.4.0-master-ubuntu-lts-22.04](https://cdash.dealii.org/build/2575) on site tester-tng
- :disappointed: new build warnings introduced for configuration [GNU-12.2.0-master-debian-12](https://cdash.dealii.org/build/2587) on site tester-tng
- :disappointed: new build warnings introduced for configuration [GNU-13.2.0-master-avx256-lts-24.04](https://cdash.dealii.org/build/2588) on site tester-tng
- :angry: new test failures introduced for configuration [GNU-13.2.0-master-avx256-lts-24.04](https://cdash.dealii.org/build/2588) on site tester-tng
- :disappointed: new build warnings introduced for configuration [GNU-13.2.0-master-ubuntu-24.10](https://cdash.dealii.org/build/2591) on site tester-tng
- :disappointed: new build warnings introduced for configuration [GNU-13.2.0-master-ubuntu-lts-24.04](https://cdash.dealii.org/build/2590) on site tester-tng
- :disappointed: new build warnings introduced for configuration [GNU-13.3.0-master-debian-13](https://cdash.dealii.org/build/2585) on site tester-tng
- :disappointed: new build warnings introduced for configuration [GNU-9.4.0-master-ubuntu-lts-20.04](https://cdash.dealii.org/build/2576) on site tester-tng
- :disappointed: new build warnings introduced for configuration [Clang-13.0.1-master-autodetection-20230116](https://cdash.dealii.org/build/2595) on site tester-tos
- :disappointed: new build warnings introduced for configuration [Clang-14.0.6-master-autodetection-20230116](https://cdash.dealii.org/build/2594) on site tester-tos
- :disappointed: new build warnings introduced for configuration [Clang-15.0.6-master-autodetection-20230116](https://cdash.dealii.org/build/2593) on site tester-tos
- :disappointed: new build warnings introduced for configuration [Clang-16.0.6-master-autodetection-20230507](https://cdash.dealii.org/build/2589) on site tester-tos
- :disappointed: new build warnings introduced for configuration [Clang-16.0.6-master-taskflow-20230708](https://cdash.dealii.org/build/2586) on site tester-tos
- :disappointed: new build warnings introduced for configuration [Clang-17.0.6-master-autodetection-20240704](https://cdash.dealii.org/build/2584) on site tester-tos
- :disappointed: new build warnings introduced for configuration [Clang-18.1.8-master-unity_build-20240704](https://cdash.dealii.org/build/2582) on site tester-tos
- :disappointed: new build warnings introduced for configuration [GNU-10.4.1-master-autodetection-20230116](https://cdash.dealii.org/build/2581) on site tester-tos
- :disappointed: new build warnings introduced for configuration [GNU-11.3.1-master-autodetection-20230116](https://cdash.dealii.org/build/2580) on site tester-tos
- :disappointed: new build warnings introduced for configuration [GNU-12.2.1-master-autodetection-20230116](https://cdash.dealii.org/build/2579) on site tester-tos
- :disappointed: new build warnings introduced for configuration [GNU-13.1.1-master-autodetection-20230507](https://cdash.dealii.org/build/2578) on site tester-tos
- :disappointed: new build warnings introduced for configuration [GNU-13.1.1-master-standalone_kokkos-20230507](https://cdash.dealii.org/build/2577) on site tester-tos
- :disappointed: new build warnings introduced for configuration [GNU-14.1.1-master-autodetection-20240704](https://cdash.dealii.org/build/2596) on site tester-tos

I have identified the following pull requests as possible candidates:
- #17611 (authored-by: @marcfehling; merged-by: @kronbichler)
- #17134 (authored-by: @dario-coscia; merged-by: @kronbichler)
- #17658 (authored-by: @tjhei; merged-by: @masterleinad)
- #17661 (authored-by: @kronbichler; merged-by: @peterrum)
- #17374 (authored-by: @bangerth; merged-by: @kronbichler)
- #17647 (authored-by: @bangerth; merged-by: @kronbichler)

Notes:
 - The regression reported above is a subset of the following full set of regressions compared to the baseline:
   - :disappointed: build warnings for configuration [GNU-10.2.1-master-debian-11](https://cdash.dealii.org/build/2574) on site tester-tng
   - :disappointed: build warnings for configuration [GNU-11.4.0-master-ubuntu-lts-22.04](https://cdash.dealii.org/build/2575) on site tester-tng
   - :disappointed: build warnings for configuration [GNU-12.2.0-master-debian-12](https://cdash.dealii.org/build/2587) on site tester-tng
   - :disappointed: build warnings for configuration [GNU-13.2.0-master-avx256-lts-24.04](https://cdash.dealii.org/build/2588) on site tester-tng
   - :angry: test failures for configuration [GNU-13.2.0-master-avx256-lts-24.04](https://cdash.dealii.org/build/2588) on site tester-tng
   - :disappointed: build warnings for configuration [GNU-13.2.0-master-ubuntu-24.10](https://cdash.dealii.org/build/2591) on site tester-tng
   - :disappointed: build warnings for configuration [GNU-13.2.0-master-ubuntu-lts-24.04](https://cdash.dealii.org/build/2590) on site tester-tng
   - :disappointed: build warnings for configuration [GNU-13.3.0-master-debian-13](https://cdash.dealii.org/build/2585) on site tester-tng
   - :disappointed: build warnings for configuration [GNU-9.4.0-master-ubuntu-lts-20.04](https://cdash.dealii.org/build/2576) on site tester-tng
   - :disappointed: build warnings for configuration [Clang-13.0.1-master-autodetection-20230116](https://cdash.dealii.org/build/2595) on site tester-tos
   - :disappointed: build warnings for configuration [Clang-14.0.6-master-autodetection-20230116](https://cdash.dealii.org/build/2594) on site tester-tos
   - :disappointed: build warnings for configuration [Clang-15.0.6-master-autodetection-20230116](https://cdash.dealii.org/build/2593) on site tester-tos
   - :disappointed: build warnings for configuration [Clang-16.0.6-master-autodetection-20230507](https://cdash.dealii.org/build/2589) on site tester-tos
   - :disappointed: build warnings for configuration [Clang-16.0.6-master-taskflow-20230708](https://cdash.dealii.org/build/2586) on site tester-tos
   - :disappointed: build warnings for configuration [Clang-17.0.6-master-autodetection-20240704](https://cdash.dealii.org/build/2584) on site tester-tos
   - :disappointed: build warnings for configuration [Clang-18.1.8-master-unity_build-20240704](https://cdash.dealii.org/build/2582) on site tester-tos
   - :disappointed: build warnings for configuration [GNU-10.4.1-master-autodetection-20230116](https://cdash.dealii.org/build/2581) on site tester-tos
   - :disappointed: build warnings for configuration [GNU-11.3.1-master-autodetection-20230116](https://cdash.dealii.org/build/2580) on site tester-tos
   - :disappointed: build warnings for configuration [GNU-12.2.1-master-autodetection-20230116](https://cdash.dealii.org/build/2579) on site tester-tos
   - :disappointed: build warnings for configuration [GNU-13.1.1-master-autodetection-20230507](https://cdash.dealii.org/build/2578) on site tester-tos
   - :disappointed: build warnings for configuration [GNU-13.1.1-master-standalone_kokkos-20230507](https://cdash.dealii.org/build/2577) on site tester-tos
   - :disappointed: build warnings for configuration [GNU-14.1.1-master-autodetection-20240704](https://cdash.dealii.org/build/2596) on site tester-tos
 - I will close and unpin this issue automatically once a full run is complete and compares cleanly to the baseline.
 - If closed I will reopen the issue if the testsuite run identified an additional regression compared to what I have reported so far.

[end automated regression testsuite report]

**Comment by bangerth** [comment] 2024-09-05 19:06
This is caused by #17647 but already fixed by #17663.

**Comment by tamiko** [comment] 2024-09-05 19:35
[automated regression testsuite]
Reopening issue due to a change in the summary message.

**Closed** 2024-09-18 19:24 UTC
Labels: Regression tester
