### ISSUE TITLE
dealii-9.0.0 wrongly detects the PETSc version: 3.10.1 is detected as 3.0.1.0

### ISSUE THREAD

**Issue by yurivict** [dealii/dealii#7260] opened 2018-10-03 03:19 UTC
```/usr/local/include/petscversion.h``` has
```
#define PETSC_VERSION_RELEASE    1
#define PETSC_VERSION_MAJOR      3
#define PETSC_VERSION_MINOR      10
#define PETSC_VERSION_SUBMINOR   1
#define PETSC_VERSION_PATCH      0
#define PETSC_RELEASE_DATE       "Sep, 12, 2018"
#define PETSC_VERSION_DATE       "Sep, 26, 2018"
```

but ```configure``` complains:
```
--   PETSC_VERSION: 3.0.1.0
--   PETSC_LIBRARIES: /usr/local/lib/libpetsc.so;/usr/local/lib/liblapack.so;/usr/local/lib/libblas.so;m;/usr/local/lib/libX11.so;pthread;dl;/usr/local/lib/libmpifort.so;/usr/local/lib/libmpi.so;m;m;/usr/local/lib/gcc7/libssp_nonshared.a;/usr/lib/libc++.so;dl;/usr/local/lib/libmpicxx.so;/usr/local/lib/libmpi.so;m;dl
```

FreeBSD 11.2

**Comment by drwells** [comment] 2018-10-03 03:54
I believe that this is a duplicate of #7203. Can you confirm that the issue appears on `master`?

**Comment by yurivict** [comment] 2018-10-03 04:16
I see it in ```9.0.0```.
It's fine, I'll just wait for the fix.

**Comment by davydden** [comment] 2018-10-03 05:01
It should be already fixed in master, but of course it is not in 9.0.0.

**Comment by yurivict** [comment] 2018-10-03 05:05
I am working on the FreeBSD port for deal.II. I'll be able to check/add this feature later once it is released.

**Comment by davydden** [comment] 2018-10-13 20:45
Closing as this is fixed now

**Closed by davydden** 2018-10-13 20:45 UTC
Labels: Bug, Build system, External libraries
