### ISSUE TITLE
Geometry problems with MappingQ and MappingQGeneric

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#3874] opened 2017-01-30 22:34 UTC
I am using a circular grid with the following refinement strategy:
1. Set the manifold on all boundary cells to `SphericalManifold`.
2. Refine globally several times.
3. Reset all interior manifolds to be straight lines and just the boundary to be described by `SphericalManifold`.

This makes a very nice grid but the finite element solution is wrong :(

The relevant lines of code are
```cpp
213  triangulation.refine_global(n_global_refines);
214
215  for (auto cell : triangulation.active_cell_iterators())
216    {
217      for (unsigned int face_n = 0;
218           face_n < GeometryInfo<dim>::faces_per_cell;
219           ++face_n)
220        {
221          if (cell->face(face_n)->at_boundary())
222            {
223              cell->face(face_n)->set_boundary_id(circle_boundary_id);
224            }
225        }
226    }
227
228  // this part causes trouble: redo the manifolds after refining the grid
229  triangulation.set_all_manifold_ids(straight_manifold_id);
230  triangulation.set_all_manifold_ids_on_boundary(circular_manifold_id);
```

There is some problem with this approach and higher order mappings (though everything works just fine with `MappingQ1`). In particular, for an order 4 approximation we get the following rates of convergence:

```
L2 error: 1.04605
L2 slope: 4.29124
L2 error: 0.038681
L2 slope: 4.75718
L2 error: 0.00127104
L2 slope: 4.92754
L2 error: 4.53956e-05
L2 slope: 4.80731
L2 error: 2.32217e-06
L2 slope: 4.28901
L2 error: 1.76846e-07
L2 slope: 3.7149
L2 error: 1.52587e-08
L2 slope: 3.5348
```

the reason for this is that the boundary is polluted in some way:

https://raw.githubusercontent.com/drwells/bad-laplace/master/mapping-q.png

I have the test case I used to generate this available at (it is a couple hundred lines of code)

https://github.com/drwells/bad-laplace

Is this just a bad way to generate grids? I can't figure out why this would not work.

**Comment by drwells** [comment] 2017-02-07 19:38
I went back and redid my calculations with the manufactured solution `u = x*y` and the same grid as `step-5` and am still getting the same result (asymptotically the error in boundary cells is `O(h^3)`, leading to an overall L2 convergence rate of 3.5). With fourth order elements this error should be zero so something bad is going on here.

I am not sure why the error is essentially third order instead of second but I am now convinced that this is a bug.

I repeated these computations with a `ChartManifold` implementing a cubic boundary description and got the same order of convergence so I am fairly certain that this is not a problem with `SphericalManifold` but, like #3886, this error shows up when we have two manifolds defined on the same cell (in this case a curved boundary description and a straight interior).

**Comment by drwells** [comment] 2017-02-07 23:59
My conclusion from these tests is that the approach we use in `step-5` and other places is fundamentally limited to third order (which means we hardly benefit at all from isoparametric elements on the boundary). I would appreciate some advice on where to look to fix this: I don't know the mapping/manifold code that well.

**Comment by kronbichler** [comment] 2017-02-08 06:56
I find it a bit strange that the result you get is third order convergence also with the manufactured solution. If I remember correctly, I have done convergence tests with manufactured solutions and curved boundaries (without manifolds in the interior) and got optimal `O(h^{p+1})` convergence at least up to degree 6.

I need to have a closer look at this problem. Together with a PhD student, I'm facing a similar problem where increasing the polynomial degree beyond 5 or 6 does not yield any benefit (in the setting of #3886, both in 2D and 3D) even though the solution is smooth and one should in principle get spectral convergence. It might be that we broke something when going to the new manifold code - or it might never have worked.

**Comment by kronbichler** [comment] 2017-02-08 10:54
@drwells Have you checked that an old version of deal.II (say 8.3 or 8.4) shows the same behavior? I'm curious whether this is a regression we introduced recently or whether we have had this bug for a long time already.

**Comment by drwells** [comment] 2017-02-08 14:50
@kronbichler It is possible that I am switching back and forth between manifolds in a bad way, or that I set up the test problem incorrectly: I would appreciate it if you could glance over it to see if I did anything obviously wrong (the whole file is about 350 lines). I updated my test case to use an annular grid (so that one can test things by using `SphericalManifold` and `MappingQGeneric` everywhere: this works correctly).

I reran my test case with both 8.3 and 8.4 and the results are identical to what I see on 8.5-pre: there is an `O(h^3)` error on the face opposite to the boundary, which results in the overall `O(h^3.5)` rate of convergence.

**Comment by kronbichler** [comment] 2017-02-08 18:02
@drwells I had a look at your code and it looks very reasonable in what it is doing. In particular, the fact that everything works well for the `SphericalManifold` everywhere suggests that we do something strange when choosing the interior points in `MappingQGeneric` that leads to non-optimal convergence behavior. I could imagine that the fact that we always switch from the curved manifold to the linear one within a single element layer leads to the case that we create a non-smooth interpolation inside the elements that only converges linearly or quadratically as the elements are refined. I think that one can construct a similar case in 1D with high-order elements: If one places the "support" points in a non-equidistant way inside the element, then convergence as the mesh is refined is very slow. I will try to create a test for this tomorrow and check if that can be the cause.

It appears that switching from the spherical manifold to a planar manifold "automatically" and not via a smooth manifold description could be problematic. I would be curious to see what happens if we created a manifold that implements a transition between spherical and planar shapes over a distance that does not depend on the mesh size. We would probably have to implement the `pull_back` and `push_forward` functions by hand...

**Comment by bangerth** [comment] 2017-02-08 18:09
Have either of you verified that the two mappings on the two cells really do produce a continuous geometry? E.g., if you created a large number of quadrature points on each cell and plotted their (mapped) locations, do they cover the entire geometry in a unique way?

**Comment by drwells** [comment] 2017-02-08 21:09
@bangerth I am not really sure what to look for here, but I plotted a large (something like 600 quadrature points per cell) number of quadrature points on the coarsest grid and got the following for the purely spherical case:

![spherical-everywhere](https://cloud.githubusercontent.com/assets/3917035/22756402/05d2db56-ee15-11e6-940e-2b9b78053bea.png)

and just at the boundary:

![spherical-boundary](https://cloud.githubusercontent.com/assets/3917035/22756413/0ba866b8-ee15-11e6-98ac-69d73b0d18e9.png)

after refining twice, with the manifold everywhere:

![spherical-everywhere-refined](https://cloud.githubusercontent.com/assets/3917035/22757413/a0c38482-ee18-11e6-8bec-212a0bdc0a1f.png)

and with the manifold just at the boundary:

![spherical-boundary-refined](https://cloud.githubusercontent.com/assets/3917035/22757423/a9d1a676-ee18-11e6-989b-4b47848b5240.png)

**Comment by drwells** [comment] 2017-02-08 22:12
Here is one where I use a composite trapezoid rule. Things *look* right: the cells are not placing quadrature points outside of the cell.

![spherical-boundary-refined](https://cloud.githubusercontent.com/assets/3917035/22759779/b8ae48da-ee21-11e6-82fd-eb0d2a017113.png)

**Comment by bangerth** [comment] 2017-02-08 23:17
Yes, I agree this looks reasonable. In particular, it is nice to see that the rows of (concentric) points have a kink at the edge between cells in the interior domain, but form a smooth curve at the inner and outer radii. It surely doesn't look obviously wrong...

At the same time, the difference in solutions between one that is O(h^3) and one that is O(h^4) or O(h^3.5) is very small...

**Comment by kronbichler** [comment] 2017-02-09 09:42
Thanks for the figures, David. They look very nice and exactly as expected.

I've investigated the issue a bit more on a 1D example. I set up the problem with `MappingQEulerian` and tried various mappings. In 1D, the `MappingQEulerian` is simply associated with the solution vector of the Laplacian.

Variant 1:
```
    eulerian_vector.reinit(dof_handler.n_dofs());
    AssertThrow(dim == 1, ExcInternalError());
    Quadrature<dim> quad(fe->get_unit_support_points());
    FEValues<dim> fe_values(*fe, quad, update_values | update_quadrature_points);
    Vector<double> local_vec(fe->dofs_per_cell);
    for (typename DoFHandler<dim>::active_cell_iterator cell = dof_handler.begin_active();
         cell != dof_handler.end(); ++cell)
      {
        fe_values.reinit(cell);
        for (unsigned int q=0; q<quad.size(); ++q)
          {
            local_vec(q) = std::tanh(2.*fe_values.quadrature_point(q)[0])/std::tanh(2.);
          }
        cell->set_dof_values(local_vec, eulerian_vector);
      }
    mapping.reset(new MappingQEulerian<dim,Vector<double> > (fe->degree, dof_handler, eulerian_vector));
```
This sets a smooth deformation in form of a tangent hyperbole function, representing refinement towards the boundary of the element. (The program is slight extension of step-7.)

Variant 2 replaces the smooth deformation by a deformation inside one element, so instead of the loop over the cells I simply do the following:
```
    const double length = dof_handler.begin_active()->diameter();
    for (unsigned int i=2; i<fe->dofs_per_cell; ++i)
      local_vec(i) = length * 0.8 * quad.point(i)[0] * (1.-quad.point(i)[0]);
    dof_handler.begin_active()->set_dof_values(local_vec, eulerian_vector);
```
Here I move the points inside the unit element by a fixed amount. In global coordinates, this corresponds to multiplication by the length of the element.

In the first case, I get optimal convergence rates `N+1` for all polynomial degrees `N` between 1 and 6. In the second case, however, I get the following rates. I apologize for the long tables but I really wanted to get a large set of data points to be sure about the convergence rates:
```
Solving with Q1 elements, global refinement
===========================================
cycle cells dofs       L2             H1        Linfty   
    0     4    5 1.111e+00    - 4.637e+00    - 1.835e+00 
    1     8    9 2.075e-01 2.42 2.819e+00 0.72 3.430e-01 
    2    12   13 7.304e-02 2.58 1.606e+00 1.39 1.464e-01 
    3    16   17 5.702e-02 0.86 1.493e+00 0.25 9.954e-02 
    4    20   21 3.776e-02 1.85 1.226e+00 0.89 7.831e-02 
    5    24   25 2.665e-02 1.91 1.034e+00 0.93 5.386e-02 
    6    28   29 1.977e-02 1.94 8.929e-01 0.95 3.610e-02 
    7    32   33 1.523e-02 1.95 7.850e-01 0.96 3.109e-02 
    8    40   41 9.817e-03 1.97 6.315e-01 0.97 1.971e-02 
    9    48   49 6.844e-03 1.98 5.279e-01 0.98 1.415e-02 
   10    56   57 5.040e-03 1.98 4.533e-01 0.99 1.011e-02 
   11    64   65 3.865e-03 1.99 3.971e-01 0.99 7.992e-03 
   12    80   81 2.478e-03 1.99 3.181e-01 0.99 5.112e-03 
   13    96   97 1.723e-03 1.99 2.653e-01 1.00 3.542e-03 
   14   112  113 1.266e-03 2.00 2.275e-01 1.00 2.598e-03 
   15   128  129 9.699e-04 2.00 1.991e-01 1.00 2.000e-03 
   16   160  161 6.210e-04 2.00 1.594e-01 1.00 1.284e-03 
   17   192  193 4.314e-04 2.00 1.328e-01 1.00 8.914e-04 
   18   224  225 3.170e-04 2.00 1.139e-01 1.00 6.541e-04 
   19   256  257 2.427e-04 2.00 9.964e-02 1.00 5.016e-04 
   20   288  289 1.918e-04 2.00 8.857e-02 1.00 3.965e-04 
   21   320  321 1.553e-04 2.00 7.972e-02 1.00 3.210e-04 
   22   352  353 1.284e-04 2.00 7.247e-02 1.00 2.653e-04 
   23   384  385 1.079e-04 2.00 6.644e-02 1.00 2.230e-04 
   24   416  417 9.193e-05 2.00 6.133e-02 1.00 1.900e-04 
   25   448  449 7.927e-05 2.00 5.695e-02 1.00 1.638e-04 
   26   480  481 6.905e-05 2.00 5.315e-02 1.00 1.427e-04 
   27   512  513 6.069e-05 2.00 4.983e-02 1.00 1.255e-04 
   28   576  577 4.795e-05 2.00 4.429e-02 1.00 9.912e-05 
   29   640  641 3.884e-05 2.00 3.986e-02 1.00 8.029e-05 
   30   704  705 3.210e-05 2.00 3.624e-02 1.00 6.636e-05 
   31   768  769 2.697e-05 2.00 3.322e-02 1.00 5.576e-05 
   32   832  833 2.298e-05 2.00 3.067e-02 1.00 4.751e-05 
   33   896  897 1.982e-05 2.00 2.847e-02 1.00 4.097e-05 
   34   960  961 1.726e-05 2.00 2.658e-02 1.00 3.569e-05 
   35  1024 1025 1.517e-05 2.00 2.492e-02 1.00 3.137e-05 

Solving with Q2 elements, global refinement
===========================================
cycle cells dofs       L2             H1        Linfty   
    0     4    9 2.011e+00    - 3.502e+00    - 2.701e+00 
    1     8   17 7.976e-02 4.66 1.552e+00 1.17 1.229e-01 
    2    12   25 2.487e-02 2.87 8.705e-01 1.43 4.954e-02 
    3    16   33 8.037e-03 3.93 3.916e-01 2.78 1.931e-02 
    4    20   41 3.822e-03 3.33 2.422e-01 2.15 8.195e-03 
    5    24   49 2.147e-03 3.16 1.669e-01 2.04 3.824e-03 
    6    28   57 1.342e-03 3.05 1.228e-01 1.99 2.979e-03 
    7    32   65 9.042e-04 2.96 9.468e-02 1.95 1.955e-03 
    8    40   81 4.781e-04 2.86 6.181e-02 1.91 1.030e-03 
    9    48   97 2.890e-04 2.76 4.394e-02 1.87 8.125e-04 
   10    56  113 1.906e-04 2.70 3.307e-02 1.84 7.059e-04 
   11    64  129 1.336e-04 2.66 2.594e-02 1.82 6.021e-04 
   12    80  161 7.447e-05 2.62 1.739e-02 1.79 4.397e-04 
   13    96  193 4.647e-05 2.59 1.262e-02 1.76 3.300e-04 
   14   112  225 3.128e-05 2.57 9.653e-03 1.74 2.553e-04 
   15   128  257 2.224e-05 2.55 7.675e-03 1.72 2.027e-04 
   16   160  321 1.262e-05 2.54 5.259e-03 1.69 1.362e-04 
   17   192  385 7.953e-06 2.53 3.879e-03 1.67 9.752e-05 
   18   224  449 5.389e-06 2.52 3.008e-03 1.65 7.319e-05 
   19   256  513 3.849e-06 2.52 2.418e-03 1.64 5.691e-05 
   20   288  577 2.861e-06 2.52 1.997e-03 1.62 4.551e-05 
   21   320  641 2.195e-06 2.52 1.685e-03 1.61 3.721e-05 
   22   352  705 1.728e-06 2.51 1.446e-03 1.60 3.098e-05 
   23   384  769 1.389e-06 2.51 1.259e-03 1.60 2.620e-05 
   24   416  833 1.136e-06 2.51 1.108e-03 1.59 2.244e-05 
   25   448  897 9.430e-07 2.51 9.856e-04 1.58 1.944e-05 
   26   480  961 7.931e-07 2.51 8.839e-04 1.58 1.700e-05 
   27   512 1025 6.746e-07 2.51 7.985e-04 1.57 1.499e-05 
   28   576 1153 5.021e-07 2.51 6.637e-04 1.57 1.191e-05 
   29   640 1281 3.855e-07 2.51 5.630e-04 1.56 9.689e-06 
   30   704 1409 3.036e-07 2.51 4.853e-04 1.56 8.036e-06 
   31   768 1537 2.442e-07 2.51 4.240e-04 1.55 6.773e-06 
   32   832 1665 1.998e-07 2.50 3.745e-04 1.55 5.786e-06 
   33   896 1793 1.660e-07 2.50 3.340e-04 1.55 4.999e-06 
   34   960 1921 1.396e-07 2.50 3.003e-04 1.54 4.363e-06 
   35  1024 2049 1.188e-07 2.50 2.718e-04 1.54 3.841e-06 

Solving with Q3 elements, global refinement
===========================================
cycle cells dofs       L2             H1        Linfty   
    0     2    7 9.005e+00    - 5.248e+00    - 7.255e+00 
    1     4   13 4.169e-01 4.43 2.336e+00 1.17 6.121e-01 
    2     6   19 4.986e-02 5.24 1.072e+00 1.92 9.104e-02 
    3     8   25 1.206e-02 4.93 4.878e-01 2.74 2.031e-02 
    4    10   31 6.286e-03 2.92 2.887e-01 2.35 1.455e-02 
    5    12   37 3.393e-03 3.38 1.684e-01 2.96 9.253e-03 
    6    14   43 2.525e-03 1.92 1.453e-01 0.96 6.780e-03 
    7    16   49 1.712e-03 2.91 1.114e-01 1.99 5.012e-03 
    8    20   61 8.190e-04 3.31 6.529e-02 2.39 2.825e-03 
    9    24   73 4.400e-04 3.41 4.160e-02 2.47 1.717e-03 
   10    28   85 2.601e-04 3.41 2.847e-02 2.46 1.120e-03 
   11    32   97 1.655e-04 3.39 2.058e-02 2.43 7.739e-04 
   12    40  121 7.874e-05 3.33 1.214e-02 2.37 4.212e-04 
   13    48  145 4.356e-05 3.25 8.017e-03 2.28 2.595e-04 
   14    56  169 2.672e-05 3.17 5.717e-03 2.19 1.740e-04 
   15    64  193 1.766e-05 3.10 4.306e-03 2.12 1.241e-04 
   16    80  241 8.994e-06 3.02 2.734e-03 2.04 7.160e-05 
   17    96  289 5.264e-06 2.94 1.918e-03 1.95 4.631e-05 
   18   112  337 3.379e-06 2.88 1.436e-03 1.88 3.231e-05 
   19   128  385 2.317e-06 2.83 1.125e-03 1.83 2.379e-05 
   20   144  433 1.668e-06 2.79 9.111e-04 1.79 1.823e-05 
   21   160  481 1.247e-06 2.76 7.572e-04 1.76 1.441e-05 
   22   176  529 9.610e-07 2.73 6.420e-04 1.73 1.167e-05 
   23   192  577 7.589e-07 2.71 5.533e-04 1.71 9.645e-06 
   24   208  625 6.115e-07 2.70 4.832e-04 1.69 8.102e-06 
   25   224  673 5.013e-07 2.68 4.267e-04 1.68 6.901e-06 
   26   240  721 4.170e-07 2.67 3.804e-04 1.66 5.949e-06 
   27   256  769 3.512e-07 2.66 3.419e-04 1.65 5.180e-06 
   28   288  865 2.572e-07 2.64 2.818e-04 1.64 4.030e-06 
   29   320  961 1.950e-07 2.63 2.375e-04 1.62 3.225e-06 
   30   352 1057 1.519e-07 2.62 2.037e-04 1.61 2.638e-06 
   31   384 1153 1.211e-07 2.61 1.772e-04 1.60 2.199e-06 
   32   416 1249 9.838e-08 2.60 1.560e-04 1.59 1.860e-06 
   33   448 1345 8.119e-08 2.59 1.387e-04 1.59 1.594e-06 
   34   480 1441 6.793e-08 2.58 1.243e-04 1.58 1.381e-06 
   35   512 1537 5.752e-08 2.58 1.123e-04 1.57 1.209e-06 

Solving with Q4 elements, global refinement
===========================================
cycle cells dofs       L2             H1        Linfty   
    0     2    9 3.303e+00    - 5.132e+00    - 4.282e+00 
    1     4   17 7.582e-02 5.45 1.215e+00 2.08 1.145e-01 
    2     6   25 1.413e-02 4.14 4.915e-01 2.23 3.156e-02 
    3     8   33 7.022e-03 2.43 2.920e-01 1.81 1.923e-02 
    4    10   41 3.106e-03 3.66 1.587e-01 2.73 9.892e-03 
    5    12   49 1.536e-03 3.86 9.508e-02 2.81 5.361e-03 
    6    14   57 8.072e-04 4.17 5.812e-02 3.19 3.143e-03 
    7    16   65 4.674e-04 4.09 3.849e-02 3.09 1.977e-03 
    8    20   81 1.926e-04 3.97 1.992e-02 2.95 9.206e-04 
    9    24   97 9.494e-05 3.88 1.182e-02 2.86 4.993e-04 
   10    28  113 5.277e-05 3.81 7.672e-03 2.80 3.004e-04 
   11    32  129 3.194e-05 3.76 5.310e-03 2.75 1.945e-04 
   12    40  161 1.396e-05 3.71 2.903e-03 2.71 9.507e-05 
   13    48  193 7.161e-06 3.66 1.787e-03 2.66 5.337e-05 
   14    56  225 4.090e-06 3.63 1.191e-03 2.63 3.290e-05 
   15    64  257 2.525e-06 3.61 8.398e-04 2.61 2.169e-05 
   16    80  321 1.132e-06 3.59 4.708e-04 2.59 1.086e-05 
   17    96  385 5.902e-07 3.57 2.944e-04 2.58 6.191e-06 
   18   112  449 3.408e-07 3.56 1.983e-04 2.56 3.857e-06 
   19   128  513 2.120e-07 3.55 1.410e-04 2.55 2.563e-06 
   20   144  577 1.396e-07 3.55 1.044e-04 2.55 1.789e-06 
   21   160  641 9.613e-08 3.54 7.988e-05 2.54 1.298e-06 
   22   176  705 6.862e-08 3.54 6.271e-05 2.54 9.710e-07 
   23   192  769 5.045e-08 3.53 5.030e-05 2.54 7.454e-07 
   24   208  833 3.802e-08 3.53 4.107e-05 2.53 5.846e-07 
   25   224  897 2.927e-08 3.53 3.405e-05 2.53 4.669e-07 
   26   240  961 2.295e-08 3.53 2.860e-05 2.53 3.788e-07 
   27   256 1025 1.828e-08 3.53 2.430e-05 2.53 3.115e-07 
   28   288 1153 1.207e-08 3.52 1.805e-05 2.52 2.181e-07 
   29   320 1281 8.329e-09 3.52 1.384e-05 2.52 1.586e-07 
   30   352 1409 5.956e-09 3.52 1.088e-05 2.52 1.189e-07 
   31   384 1537 4.386e-09 3.52 8.742e-06 2.52 9.135e-08 
   32   416 1665 3.310e-09 3.52 7.148e-06 2.52 7.180e-08 
   33   448 1793 2.551e-09 3.51 5.932e-06 2.52 5.740e-08 
   34   480 1921 2.003e-09 3.50 4.987e-06 2.51 4.669e-08 
   35   512 2049 1.596e-09 3.52 4.241e-06 2.51 3.837e-08 

Solving with Q5 elements, global refinement
===========================================
cycle cells dofs       L2             H1        Linfty   
    0     1    6 2.385e+01    - 6.195e+00    - 1.876e+01 
    1     2   11 1.228e+00 4.28 2.872e+00 1.11 1.494e+00 
    2     3   16 8.068e-02 6.72 1.229e+00 2.09 7.407e-02 
    3     4   21 3.348e-02 3.06 8.103e-01 1.45 1.037e-01 
    4     5   26 1.661e-02 3.14 5.444e-01 1.78 4.187e-02 
    5     6   31 8.305e-03 3.80 3.082e-01 3.12 1.757e-02 
    6     7   36 3.804e-03 5.07 1.626e-01 4.15 7.577e-03 
    7     8   41 1.781e-03 5.68 8.806e-02 4.60 3.991e-03 
    8    10   51 4.487e-04 6.18 2.910e-02 4.96 1.266e-03 
    9    12   61 1.284e-04 6.86 1.048e-02 5.60 4.538e-04 
   10    14   71 4.625e-05 6.62 4.760e-03 5.12 1.843e-04 
   11    16   81 1.959e-05 6.43 2.477e-03 4.89 8.380e-05 
   12    20  101 4.936e-06 6.18 8.667e-04 4.71 2.347e-05 
   13    24  121 1.792e-06 5.56 3.966e-04 4.29 1.014e-05 
   14    28  141 8.267e-07 5.02 2.168e-04 3.92 5.208e-06 
   15    32  161 4.578e-07 4.43 1.353e-04 3.53 3.162e-06 
   16    40  201 2.180e-07 3.33 7.277e-05 2.78 1.716e-06 
   17    48  241 1.383e-07 2.49 5.052e-05 2.00 1.102e-06 
   18    56  281 9.543e-08 2.41 3.864e-05 1.74 7.620e-07 
   19    64  321 6.815e-08 2.52 3.070e-05 1.72 5.513e-07 
   20    72  361 4.990e-08 2.65 2.489e-05 1.78 4.120e-07 
   21    80  401 3.733e-08 2.75 2.049e-05 1.85 3.158e-07 
   22    88  441 2.847e-08 2.84 1.708e-05 1.91 2.473e-07 
   23    96  481 2.210e-08 2.91 1.439e-05 1.97 1.972e-07 
   24   104  521 1.742e-08 2.97 1.224e-05 2.02 1.597e-07 
   25   112  561 1.393e-08 3.02 1.051e-05 2.06 1.311e-07 
   26   120  601 1.128e-08 3.06 9.102e-06 2.09 1.089e-07 
   27   128  641 9.235e-09 3.09 7.937e-06 2.12 9.142e-08 
   28   144  721 6.383e-09 3.14 6.155e-06 2.16 6.624e-08 
   29   160  801 4.565e-09 3.18 4.882e-06 2.20 4.949e-08 
   30   176  881 3.360e-09 3.22 3.947e-06 2.23 3.795e-08 
   31   192  961 2.533e-09 3.25 3.243e-06 2.26 2.971e-08 
   32   208 1041 1.950e-09 3.27 2.702e-06 2.28 2.380e-08 
   33   224 1121 1.529e-09 3.29 2.279e-06 2.30 1.946e-08 
   34   240 1201 1.219e-09 3.28 1.943e-06 2.31 1.614e-08 
   35   256 1281 9.864e-10 3.28 1.672e-06 2.33 1.351e-08 
```
You see that all of a sudden one gets distorted convergence numbers, which solely depends on what happens inside the very first element.

What this experiment tells me is that the function underlying the mapping has to converge in some reasonable measure. If it does not as in my second example, convergence is clearly affected. In the setup where we have one edge along a curved manifold but the others along a plain manifold, we end up in a similar situation: We always have just one element layer where we go from the curved edge to the linear edge on the other end of a cell. Thus, the resulting mapping *does not converge* in a smooth way - in that case, we would eventually spread the transition from the spherical manifold to a planar manifold over several elements.

David, do you happen to know more about variational crimes or the convergence theory of high order finite elements? As far as I can tell, when one inserts a high-order polynomial description in form of `MappingQGeneric`, we do not work with the usual space of polynomials that guarantees convergence but the image of the unit cell polynomials under the mapping. If the mapping is non-smooth, we have no guarantee that we cover all polynomials. My intuition in the case of the quadratic "bubble" I used above tells me that the image can contain `N+1` polynomials with degrees between `0` and `2N` (because `x(xi)` is a quadratic function). So one cannot expect completeness of the polynomial space.

The bottom line appears to be that it is not a good idea to set "discontinuous" mapping descriptions that need to be smoothed inside one element as we do in `MappingQ` and my patch #3886 tries to rectify. I think that we should warn users that convergence might be bad at some high order, but how should we do this?

- Introduce an additional argument to the constructor of `MappingQGeneric` (and `MappingQ`) that specifies that we want to smooth the points inside elements but that might limit convergence to orders 2 or 3 depending on the particular form of the manifold? If no smoothing is applied, `add_weighted_interior_point` is bypassed and the manifold decides based on only the cell vertices.

- Get rid of `add_weighted_interior_point` altogether, which will make the situation worse because we do not smooth at all and trigger inverted transformations. For high-order computations, this would usually trigger some assertions because the Jacobian gets singular and would help to better spot the problem. But linear or quadratic finite elements will usually be fine and the additional smoothing would be appreciated.

**Comment by drwells** [comment] 2017-02-10 01:20
> do you happen to know more about variational crimes or the convergence theory of hih order finite elements? 

I thought you were the expert here :) I spent most of this morning going over what Zienkiewicz and Ciarlet have to say about isoparametric finite elements and I was not able to locate description of this phenomenon. I am certainly not an expert but I have done some reading recently while working on this (and a related project) and I have a few more sources to check but I have not yet found a clear description of how to do what we want (curve exterior edges).

I'll go through what Strang and Fix have to say about variational crimes.

I find it strange that it is this hard to find a simple description of how to do what we want: I will keep looking.

This 1D example is a good idea. I suspect that there is a jump in the derivative of the Jacobian (and formally that transformation needs to be a diffeomorphism on each cell for this to work) so we should be able to plot all this in 1D and see how to fix things.

**Comment by kronbichler** [comment] 2017-02-10 07:39
> I thought you were the expert here :)

Well, I do know quite a lot about high-order methods but when it comes to curved boundaries I have not that much experience.

> This 1D example is a good idea. 

Are you able to reproduce the example or do you want me to upload it?

**Comment by drwells** [comment] 2017-02-10 13:59
It would help me if you send me the 1D code. I believe I understand what you did but this way I don't have to write my own version.

**Comment by drwells** [comment] 2017-02-13 13:12
Thanks for sending that along. I'll try to make some progress on understanding the underlying 1D fault later this week.

**Comment by drwells** [comment] 2017-03-02 20:28
In case anyone is interested, it turns out that this exact error rate (`O(h^3)`) is documented in the literature: Strang and Fix cite it on page 108.

**Comment by kronbichler** [comment] 2017-03-17 20:48
@drwells Since we understand what is going on and there does not appear anything that we could do (apart from a smoothing of the mapping that we apply in #3886 with the latest generalization), I would suggest we close this issue. Do you think we should document this more clearly somewhere?

**Comment by drwells** [comment] 2017-03-17 22:56
@kronbichler I reread your patch and I think it provides a suggestion at the right way to fix this problem and I agree that we should document this somewhere.

I do not really understand how the jump in the Jacobian influences the rate of convergence: if my boundary cell were, in 1D, half the width of all of my other cells then the method would converge normally but there would be a jump in the Jacobian in that case. Do we have a way of precisely qualifying the problem that arises from jumps in the Jacobian? As you mention in your PR the blending is not enough (and I still get an order 3.5 convergence).

If you have an answer (I am still figuring things out) then I am willing to write up whatever fix works for this annular test problem somewhere in the documentation.

**Comment by bangerth** [comment] 2017-03-19 18:39
I'm still a bit mystified by this. We know from theory that the finite element error for the Laplace equation, for example is given by
```
 ||| e |||  \le  C  \inf_{\varphi_h \in V_j}   ||| u - \varphi_h |||
```
This is the best-approximation property, and the constant `C` only depends on the domain, not on its subdivision into cells. So mappings don't play a role. Now, we then usually estimate
```
 \inf_{\varphi_h \in V_j}   ||| u - \varphi_h |||    \le    ||| u - I_h u |||
```
with the interpolant `I_h u`. It is possible that the quality of this estimate depends on the shape of cells. I've never heard of this problem, but I could see it happen. It's easy to test, though, so my Question 1 would be: Does the right hand side already show the diminished convergence order in your case? (It must, because otherwise the overall error would have to have optimal order -- this being an upper bound.)

The last step is that we use the Bramble-Hilbert lemma to estimate
```
 ||| u - I_h u |||  \le  C_I h^p  || u ||_{H^{p+1}}
```
where the interpolation constant `C_I` now definitely depends on the mapping of cells because it contains the Jacobian of the mapping in some form. On the other hand, it is a *purely local* estimate on each cell separately, so there is no dependency on *how the mapping connects from one cell to the next*.

There is of course the possibility that we compute the error wrongly because we also map quadrature points. So it is conceivable that
```
  ||| e |||
```
has optimal order, but the approximation
```
  \sum_K \sum_q  |\nabla e(x_q^K)|^2  JxW_q
```
does not because of some quirk in the mapping. This would imply that the results you compute above *wrongly* show a diminished convergence order on poorly chosen meshes. So, Question 2: Do you think this could be an issue? We could test this by using a different form of quadrature, e.g., using equidistant quadrature points throughout the domain (as opposed to the reference cell), or Monte-Carlo integration.

**Comment by drwells** [comment] 2017-03-19 21:39
@bangerth I left a comment in my test code, when I wrote it, that the projection (calculated by forming the mass matrix as the system matrix) also suffered from the same convergence problem. I'll double check this.

Graphically, the error seems to occur on the faces parallel to the boundary, so we may be able to check (2) by just integrating over all non-boundary cells (i.e., only integrate where we may use a Q1 mapping): that would rule out that class of consistency errors.

**Comment by bangerth** [comment] 2017-03-19 21:58
On 03/19/2017 03:39 PM, David Wells wrote:
> @bangerth <https://github.com/bangerth> I left a comment in my test code, when
> I wrote it, that the projection (calculated by forming the mass matrix as the
> system matrix) also suffered from the same convergence problem. I'll double
> check this.

That is interesting because the same arguments I laid out above are true for 
the L2 projection if you only replace the energy norm by the L2 norm. 
Everything else is the same -- the L2 norm also satisfies the 
best-approximation property, and all you need to do is apply the 
Bramble-Hilbert lemma to the L2 norm of the interpolant.

**Comment by kronbichler** [comment] 2017-06-01 14:21
Fixed by `TransfiniteInterpolationManifold`, can attach that to the interior of the cells. ;-)

**Closed by kronbichler** 2017-06-01 14:21 UTC
Labels: Bug, Mapping

**Comment by drwells** [comment] 2017-06-01 14:38
Yes, that was exactly my thought. I realized that the documentation in #3886 completely explains this issue with a nice citation of Strang's book a few days ago. I really should reread the third chapter (on isoparametric elements).

My only remaining concern is that this work implies that `MappingQ` is broken on a theoretical level for anything past quadratic elements (i.e., the only time one uses this class and gets the optimal order of convergence is with quadratics). Is this correct? If so, I think we need a stronger warning than the one currently in `MappingQ`

**Comment by kronbichler** [comment] 2017-06-01 15:41
You mean that one should use `MappingQGeneric`? I definitely agree on that. Even more, `MappingQ` is not just broken for high orders, it is also broken as soon as you put a manifold on the cells for quadratic interpolation. The first layer of cells will be quadratic, but the second will be straight, leaving gaps or overlaps in the computational domain. This is why I now mostly use `MappingQGeneric` everywhere, even though it is slower in the interior of the computational domain for non-curved cases. But for me the risk to miss those voids is too high.

**Comment by bangerth** [comment] 2017-06-01 17:36
I think I had always thought of `MappingQ` as an optimization because we *don't need* the higher order mapping in the interior. Your experiments show that that is not actually true -- and I think you should write this up into a paper because I don't think that it is generally understood or known. 

That leaves the question of what to do with `MappingQ`. Do you think it should be removed (or renamed, if we wanted to be backward compatible) and replaced by `MappingQGeneric`? The latter clearly also has cleaner code...

**Comment by drwells** [comment] 2017-06-01 17:52
@bangerth I think that we should remove `MappingQ`: see #4462.

It would be very nice to write up a note on this and I am definitely interested. We could write up a little proof on the nonconvergence of the torturous 1D case @kronbichler had and then follow up with some numerical experiments comparing my bad Laplace solver with `MappingQ` to one with the proper `TransfiniteInterpolationManifold`.

We should consider writing a tutorial program showcasing the possible variational crimes one can commit with deal.II :)

The last time I checked FENICS does not implement any sort of higher order mappings. It might be useful to poke around and see what other people do (I could not find a lot when I last looked in February).

**Comment by bangerth** [comment] 2017-06-01 19:14
I have contributed nothing, so I don't think that I should be part of any paper -- you and @kronbichler and @luca-heltai should figure that out. But I think a tutorial program would definitely be nice!

**Comment by Rombur** [comment] 2017-06-01 19:29
@drwells I don't know much about any of this but I think that [MFEM](http://mfem.org) can use high order mapping see http://mfem.org/examples/ and http://mfem.github.io/doxygen/html/classmfem_1_1Mesh.html#ae4113e6e1838d76dd3e85f3399adc7da

**Comment by kronbichler** [comment] 2017-06-01 20:14
@Rombur Yes mfem has a number of nice features. However, I don't know how sophisticated their "mapping" mechanism is and whether it could do things like we can do now. I have met Tzanio Kolev several times and looked into their approaches but I've seem them mostly moving around nodes in a `MappingFEField` or `MappingQEulerian` way. I don't remember if I ever discussed with him how they interact with the mesh generation, maybe something for the next time I see him... ;-)
