### ISSUE TITLE
Step-77: compatibility issues and no convergence

### ISSUE THREAD

**Issue by lpsaavedra** [dealii/dealii#12594] opened 2021-07-23 16:57 UTC
Step-77 solves a non-linear equation using the Kinsol solver of the Sundials library. deal.ii must be compiled with Sundials on. The tutorial does not compile with the Sundials 3.1.0 distributed with candi, getting the following error in debug mode:
```
--------------------------------------------------------
An error occurred in line <427> of file </home/blaisb/work/dealii/dealii/source/sundials/kinsol.cc> in function
    unsigned int dealii::SUNDIALS::KINSOL<VectorType>::solve(VectorType&) [with VectorType = dealii::Vector<double>]
The violated condition was: 
    solve_jacobian_system
Additional information: 
    Please provide an implementation for the function
    "solve_jacobian_system"

Stacktrace:
-----------
#0  /home/blaisb/work/dealii/inst/lib/libdeal_II.g.so.10.0.0-pre: dealii::SUNDIALS::KINSOL<dealii::Vector<double> >::solve(dealii::Vector<double>&)
#1  ./step-77.debug: Step77::MinimalSurfaceProblem<2>::run()
#2  ./step-77.debug: main
------------------------------------------------------
```

In release mode, only a segfault is obtained. Using the last version of Sundials (5.7.0) the code compiles but it does not converge. The following error is obtained in Debug mode:

```
Mesh refinement step 0
  Target_tolerance: 0.001

  Computing residual vector... norm=0.231202
  Computing Jacobian matrix
  Factorizing Jacobian matrix
  Solving linear system
  Computing residual vector... norm=0.231202
  Computing residual vector... norm=0.402211
  Computing residual vector... norm=0.627191
  Computing residual vector... norm=0.857696
  Computing residual vector... norm=1.08878
  Computing residual vector... norm=1.31995
  Computing residual vector... norm=1.55112
  Computing residual vector... norm=1.78231
  Computing residual vector... norm=2.0135
  Computing residual vector... norm=2.24469
  Computing residual vector... norm=2.47588
  Computing residual vector... norm=2.70708

[KINSOL ERROR]  KINSol
  The line search algorithm was unable to find an iterate sufficiently distinct from the current iterate.


--------------------------------------------------------
An error occurred in line <518> of file </home/laura/Local/dealii/source/sundials/kinsol.cc> in function
    unsigned int dealii::SUNDIALS::KINSOL<VectorType>::solve(VectorType&) [with VectorType = dealii::Vector<double>]
The violated condition was: 
    status >= 0
Additional information: 
    One of the SUNDIALS KINSOL internal functions returned a negative
    error code: -5. Please consult SUNDIALS manual.

Stacktrace:
-----------
#0  /home/laura/Local/dealii-build-sundials/lib/libdeal_II.g.so.10.0.0-pre: dealii::SUNDIALS::KINSOL<dealii::Vector<double> >::solve(dealii::Vector<double>&)
#1  ./step-77: Step77::MinimalSurfaceProblem<2>::run()
#2  ./step-77: main
--------------------------------------------------------

```
Anyone has any idea of how to fix this and make the tutorial work? 

FYI @blaisb @oguevremont

**Comment by blaisb** [comment] 2021-07-23 17:09
@lpsaavedra I know how to allow 3.1 to run with step-77 (a function needs to be added), however, it does not change the fact that it does not converge :). Good catch.

**Comment by bangerth** [comment] 2021-07-29 00:12
This is aggravating -- it used to work just fine when I wrote the program not long before the release, and must have broken in the relatively short amount of time between the merge and the release :-( We will have to find which patch broke this -- in any case, I can confirm exactly the error @lpsaavedra shows above.

If you wanted to help, do you know how to bisect a git history?

**Comment by bangerth** [comment] 2021-07-29 00:19
I would specifically see if #12254 introduced the problem.

**Comment by lpsaavedra** [comment] 2021-07-29 17:50
> If you wanted to help, do you know how to bisect a git history?

Yes, I will do it and let you know how it goes. Hopefully we find the patch soon.

**Comment by bangerth** [comment] 2021-07-29 19:24
Awesome! The number of patches between #11953 was merged and the 9.3 release is not huge, so hopefully you'll find it soon!

**Comment by lpsaavedra** [comment] 2021-07-31 13:57
#12216 was the one that introduced the problem

**Comment by peterrum** [comment] 2021-07-31 14:01
@lpsaavedra Maybe you could also take a look at the PRs referenced in issue https://github.com/dealii/dealii/issues/12223.

**Comment by blaisb** [comment] 2021-08-04 21:04
@peterrum , @luca-heltai , @bangerth  What do you think is the best forward? @lpsaavedra has pinpointed the commit. I'd like to help her fix this, but I have to admit that this part of the KINSOL wrappers will take me a long time to understand. How would you like to approach this? It's a bit sad that step-77 is not working right now. Additionally, the KINSOL wrapper implementation right now seems fragile, yet we'd like to transition to using KINSOL as a non-linear solver in Lethe. If I can do anything to help fix this, please tell me. :)

**Comment by blaisb** [comment] 2021-09-14 22:50
Bumpity Bump :). I tried to look into this from numerous angles, but I still don't understand what's going on :(

**Comment by luca-heltai** [comment] 2021-09-15 13:01
So the error that KINSOL is throwing out seems to be: KIN LINESEARCH NONCONV (-5), that is  `The linesearch algorithm was unable to find an iterate sufficiently distinct from the current iterate.` This looks like it could be a setting not being correct.

My guess is that in the earlier versions of the kinsol wrapper, some of the settings were not read correctly (we were, in fact, initializing KINSOL in the wrong manner). Maybe we are using the wrong tolerances somewhere, or we are not passing them correctly to KINSOL. I'll try to explore a bit.

**Comment by blaisb** [comment] 2021-09-15 16:31
> So the error that KINSOL is throwing out seems to be: KIN LINESEARCH NONCONV (-5), that is `The linesearch algorithm was unable to find an iterate sufficiently distinct from the current iterate.` This looks like it could be a setting not being correct.
> 
> My guess is that in the earlier versions of the kinsol wrapper, some of the settings were not read correctly (we were, in fact, initializing KINSOL in the wrong manner). Maybe we are using the wrong tolerances somewhere, or we are not passing them correctly to KINSOL. I'll try to explore a bit.

That makes sense. I have found the behavior to be very erratic right now, so clearly there is a setting not set correctly (or maybe not even initialized). @lpsaavedra and I implemented KINSOL in Lethe and for some cases, the behavior of the first iteration is identical to a classical Newton's method, which is what I found expect ( a full newton step is taken), but for other cases, KINSOL is unable to proceed past a first iteration, even though a classical Newton method works perfectly well in that case. It is a very erratic behavior :). Don't hesitate to ping me if you need help with something.

**Comment by bangerth** [comment] 2021-09-20 20:56
Since we know which patch broke step-77, is there a way to undo individual parts of the patch to see what part broke the functionality?

**Comment by blaisb** [comment] 2021-09-22 16:44
> Since we know which patch broke step-77, is there a way to undo individual parts of the patch to see what part broke the functionality?

That could be done. I just don't have a good understanding of the KINSOL wrappers. I can take a jab at it though and see which removed element broke things. It's just that it's such a blackbox wrapper that it is difficult to see what's going on.
My best bet right now is to solve problems and compare the results with what I obtain using a regular Newton method, at least for the first iteration, to see what breaks or not. I have not been able to find a logic regarding which cases work and which fails. I feel like this cat debugging this :  

https://tenor.com/view/qa-cat-leak-flood-broken-pipe-gif-12195496

(which is by far my favorite programming gif :) ).

**Comment by blaisb** [comment] 2021-10-17 18:33
So I have taken another look at this problem.
It seems that a lot of the default parameter value that we set are not adequate (and they do not correspond to the default value specified by KINSOL)

The problematic variables are : 
function_tolerance (KINSetFuncNormTol)
step_tolerance (KINSetScaledStepTol)
maximum_newton_step (KINSetMaxNewtonStep)


In the documentation, everything is defined here:
![image](https://user-images.githubusercontent.com/7850307/137640281-36b59434-355e-4523-9520-151677da918b.png)


We see that some of these parameters are dependent on the value of uround and of the norm of the scaling. Our default values of zero right now are, I think, incorrect.

I have tried to disable using our input parameters to these options in order to use KINSOL default values. It works well in Lethe and enables the use of KINSOL (I'm still not sure I fully understand it's behaviour though, but it can converge for very non-linear equations). However, this does not fix step-77 which, no-matter what I try, does not want to converge.

@luca-heltai Do you have any idea regarding this? I'd like to find a fix.
@lpsaavedra FYI.

**Comment by tamiko** [comment] 2021-11-03 19:37
I will go ahead and revert #12216 on the dealii-9.3 release branch for the point release.

**Comment by peterrum** [comment] 2022-05-25 17:51
@bangerth

**Closed** 2022-06-05 15:19 UTC
Labels: Bug
