### ISSUE TITLE
Tests Fail in Parameter_Handler

### ISSUE THREAD

**Issue by sairajat** [dealii/dealii#3969] opened 2017-02-12 21:59 UTC
Upon running the tests for parameter handler while fixing  #3927, I found these tests in the parameter handler fail. 

```
83% tests passed, 20 tests failed out of 121

Total Test time (real) =  42.66 sec

The following tests FAILED:
	 13 - parameter_handler/parameter_handler_read_xml_error_04.debug (Failed)
	 14 - parameter_handler/parameter_handler_read_xml_error_04.release (Failed)
	 23 - parameter_handler/parameter_handler_11.debug (Failed)
	 24 - parameter_handler/parameter_handler_11.release (Failed)
	 25 - parameter_handler/parameter_handler_read_xml_error_03.debug (Failed)
	 26 - parameter_handler/parameter_handler_read_xml_error_03.release (Failed)
	 63 - parameter_handler/parameter_handler_read_xml_error_02.debug (Failed)
	 64 - parameter_handler/parameter_handler_read_xml_error_02.release (Failed)
	 67 - parameter_handler/parameter_handler_backslash_05.debug (Failed)
	 68 - parameter_handler/parameter_handler_backslash_05.release (Failed)
	 71 - parameter_handler/parameter_handler_read_xml_error_01.debug (Failed)
	 72 - parameter_handler/parameter_handler_read_xml_error_01.release (Failed)
	 98 - parameter_handler/parameter_handler_backslash_03.debug (Failed)
	 99 - parameter_handler/parameter_handler_backslash_03.release (Failed)
	100 - parameter_handler/parameter_handler_10.debug (Failed)
	101 - parameter_handler/parameter_handler_10.release (Failed)
	104 - parameter_handler/parameter_handler_backslash_04.debug (Failed)
	105 - parameter_handler/parameter_handler_backslash_04.release (Failed)
	108 - parameter_handler/parameter_handler_1_include_fail.debug (Failed)
	109 - parameter_handler/parameter_handler_1_include_fail.release (Failed)
Errors while running CTest

```

**Comment by davydden** [comment] 2017-02-12 22:03
please check the logs why they fail. For starters, try running in verbose mode:
```
ctest -V -R "parameter_handler/parameter_handler_read_xml_error_04.debug"
```

**Comment by drwells** [comment] 2017-02-14 01:16
@sairajat I have not been able to reproduce this. Would you please run these tests again?

**Comment by sairajat** [comment] 2017-02-14 05:17
@drwells  I was able to update my fork and run the tests again. 
I am seeing the error in the DIFF stage for all these failed tests. 
Infact I was able to remove the error by adding extra space in output file for the test
```	 13 - parameter_handler/parameter_handler_read_xml_error_04.debug (Failed)
	 14 - parameter_handler/parameter_handler_read_xml_error_04.release (Failed)```
These tests then were successful.

I am attaching the verbose output from the ctest output for your perusal. This problem may be machine or compiler specific if you are not able to reproduce it. I just installed deal.ii without any linkage to external package. I just the the simplest possible installation. 

[LastTest.txt](https://github.com/dealii/dealii/files/773205/LastTest.txt)

**Comment by davydden** [comment] 2017-02-14 05:50
@sairajat 

you did not attach anything, please run the command I mentioned already above, namely:
```
ctest -V -R "parameter_handler/parameter_handler_read_xml_error_04.debug"
```
and post the output. If it tells that something is different, then please also post the failing diff file (in the folder of the test).

> extra space in output file for the test

that suggests that probably those tests output extra space somewhere which is not present in output files.

**Comment by davydden** [comment] 2017-02-14 06:04
@sairajat also please read https://www.dealii.org/developer/ for extra info on setting up and running  tests.

**Comment by sairajat** [comment] 2017-02-14 06:26
[LastTest.txt](https://github.com/dealii/dealii/files/773293/LastTest.txt)

@davydden  Sir, here is the file.

**Comment by bangerth** [comment] 2017-02-14 17:25
The current and the saved output for this test are indeed different. Nobody is seeing this because we are all using `numdiff`, which ignores leading whitespace.

In other words, if you install `numdiff`, then these errors should disappear.

**Comment by sairajat** [comment] 2017-02-14 19:12
@bangerth  Yes Sir, Indeed this is the issue. I installed numdiff and no tests are failing now.
It took me a long time to adjust spaces while doing tests for the earlier patch due to these leading whitespaces. Now I know why :) Thanks.

**Comment by davydden** [comment] 2017-02-14 19:15
since the issue is resolved, i am closing it.

**Closed by davydden** 2017-02-14 19:15 UTC
Labels: Tests
