### ISSUE TITLE
Update readme.html for Nanoflann and ADOL-C and SUNDIALS

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#4850] opened 2017-08-14 23:11 UTC
`doc/readme.html` lists our external dependencies. These have recently grown to include nanoflann and ADOL-C, and these should be listed there as well.

**Comment by bangerth** [comment] 2017-08-14 23:37
...also SUNDIALS

**Comment by tjhei** [comment] 2017-08-20 19:08
nanoflann is easy enough: https://github.com/dealii/candi/pull/47 (cmake with ``-D BUILD_SHARED_LIBS=ON`` and then ``make install``, then set NANOFLANN_DIR.)

**Comment by davydden** [comment] 2017-08-20 23:29
i just tried building `dealii` with `adol-c` and got:
```
deal.II needs ADOL-C version 2.6.4 or newer
```
but the latest release is `2.6.3`: https://www.coin-or.org/download/source/ADOL-C/

@jppelteret ping.

**Comment by tamiko** [comment] 2017-08-21 00:08
> i just tried building `dealii` with `adol-c` and got:
> ```
> deal.II needs ADOL-C version 2.6.4 or newer
> ```
> but the latest release is `2.6.3`: https://www.coin-or.org/download/source/ADOL-C/

This is correct and intended behavior ;-)
After all, we're from the future :-P

(aka we require the current development version that hopefully gets the
version number 2.6.4 one day.)

**Comment by jppelteret** [comment] 2017-08-21 07:35
^ what @tamiko said :-)

**Comment by drwells** [comment] 2018-05-12 03:37
Fixed by #6360 :)

**Closed by drwells** 2018-05-12 03:37 UTC
Labels: Documentation
