### ISSUE TITLE
doxygen grouping broken

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#2088] opened 2016-01-20 17:04 UTC
It seems like grouping of functions into subgroups is broken, see https://www.dealii.org/developer/doxygen/deal.II/namespaceGridGenerator.html for example. Here ```simplex``` is repeated twice, once outside the group and not clickable.

**Comment by tjhei** [comment] 2016-01-20 17:05
Another example is ```get_manifold``` in https://www.dealii.org/developer/doxygen/deal.II/classTriangulation.html

**Comment by jppelteret** [comment] 2016-01-21 06:45
This seems to be a hot topic! Maybe its finally time for it to be dealt with? #1957 #320

**Comment by jppelteret** [comment] 2016-01-21 06:48
The same seems to be the case in [VectorTools](https://www.dealii.org/developer/doxygen/deal.II/namespaceVectorTools.html) for `create_boundary_right_hand_side`. It seems like it appears when there's template specialisations?

**Comment by jppelteret** [comment] 2016-01-21 06:48
And [FETools](https://www.dealii.org/developer/doxygen/deal.II/namespaceFETools.html) for `hierarchic_to_lexicographic_numbering`.

**Comment by jppelteret** [comment] 2016-01-21 06:52
The non-clickable link issue is [all](https://www.dealii.org/developer/doxygen/deal.II/namespaceGridTools.html) [over](https://www.dealii.org/developer/doxygen/deal.II/namespaceDoFRenumbering.html) [the](https://www.dealii.org/developer/doxygen/deal.II/namespaceMatrixTools.html) [place](https://www.dealii.org/developer/doxygen/deal.II/namespaceDoFTools.html) actually.

**Comment by bangerth** [comment] 2016-01-21 12:36
I wonder if this is caused by #1356 that changed things so we now also run doxygen over the .cc files. Anyone want to try out locally whether undoing that change makes the problem go away?

**Comment by jppelteret** [comment] 2016-01-21 13:17
@bangerth Yip, that removed the offending lines in `GridTools` etc. for me at the obvious expense of having access to the source definitions through the documentation.

**Comment by bangerth** [comment] 2016-01-21 13:20
Bummer :-( What to do? We can manually exclude parts of the .cc files via `#ifndef DOXYGEN`, but I suspect just assessing what needs to be excluded is impossible given the number of files and classes we have...

**Comment by jppelteret** [comment] 2016-01-21 15:24
The [`HIDE_UNDOC_MEMBERS`](http://www.stack.nl/~dimitri/doxygen/manual/config.html#cfg_hide_undoc_members) option is the closest to a global setting that would ignore template specialisations that I can find. Changing this entry in `doc/doxygen/options.dox.in` appears (well, to me at least) to produce the desired result `GridTools` and the like. However, since I've only taken a quick glance at the result its hard to say if there are any ill effects that I haven't noticed.

**Comment by tjhei** [comment] 2016-01-21 19:18
Yes, I tried  HIDE_UNDOC* and this looks good. I will make a PR...

**Comment by bangerth** [comment] 2016-01-21 19:27
I was wondering how many undocumented functions and classes we have that would now become undiscoverable. But I think the answer is likely "very few". This may be the way to go.

**Comment by bangerth** [comment] 2016-01-21 22:58
I merged #2096. Let's see how that affects the documentation we get updated in a couple of hours.

**Comment by bangerth** [comment] 2016-01-25 04:12
It looks to me like this is working again now.

**Closed by bangerth** 2016-01-25 04:12 UTC

**Comment by jppelteret** [comment] 2016-01-25 16:38
Thanks, it seems to have fixed all of the concerns that I had in #1957!
